#!/bin/bash -vx
#

########################################
# PARTS_DETAIL/LIST SHOW.CGI
#
#   $1:必須 $$
#
#	Written by hiramatsu


########################################
#基本設定
export LANG=ja_JP.utf8
echo $LANG
SYSD=$(cd $(dirname $0) && pwd | awk '{print substr($0, 0, index($0, "sureshotsystem")+13)}')
#exec 2> $SYSD/LOG/LOG.$(basename $0).$(date +%Y%m%d).$(date +%H%M%S).$$
tmp=/tmp/tmp_$1
LANG=ja_JP.UTF-8
#PATH=/home/:/home/UTL:/home/TOOL/open-usp-tukubai-2014061402/COMMANDS:$PATH
CATEGORY=`cat $tmp-category`
FUNC=`cat $tmp-func`
SUBFUNC=`cat $tmp-sub-func`
DATAD=${SYSD}/DATA/${CATEGORY}/LISTS

#######################################
#Check error
ERROR_CHECK(){
	[ $(plus ${PIPESTATUS[@]}) -eq 0 ] && return
cat <<- FIN
	Context-type: text/html
	NG input
FIN
	cat $tmp-result
	exit 1
}

########################################
#GETパラメーターを取得
#GETパラメーターの順番は、action,page,serach,category-nm,category-no, id が前提
[ -n "$(cat $tmp-get | grep 'page=')" ] && \
QRY_PAGE=$(cat $tmp-get | awk '{split($0,ary,"&"); print ary[2]}' | sed 's/page\=//') || \
QRY_PAGE=1
[ -n "$(cat $tmp-get | grep 'search=')" ] && \
SEARCH=$(cat $tmp-get | awk '{split($0,ary,"&"); print ary[3]}') || \
SEARCH='search=0'
CATEGORY_NM=$(cat $tmp-get | awk '{split($0,ary,"&"); print ary[4]}' | sed 's/category-nm\=//')
CATEGORY_NO=$(cat $tmp-get | awk '{split($0,ary,"&"); print ary[5]}' | sed 's/category-no\=//')
NUM=$(cat $tmp-get | awk '{split($0,ary,"&"); print ary[6]}' | sed 's/id\=//')

########################################
#詳細リストを取得
cat ${SYSD}/DATA/PARTS_LIST/LISTS/LV3/parts_* |
awk -v no=${NUM} '$1==no {print}' > $tmp-parts
cat $tmp-parts | awk '{print $3}' > $tmp-category-nm
cat $tmp-parts | awk '{print $4}' > $tmp-parts-nm
cat $tmp-parts | awk '{print $5}' > $tmp-price

########################################
#詳細を取得
cat ${DATAD}/LV3/${NUM}_details_* > $tmp-records
mojihame -lRECORDS ${SYSD}/APPLI/${CATEGORY}/LISTS/HTML/RECORDS.HTML $tmp-records > $tmp-table

########################################
# 改行文字を「\\n」という3文字の文字列に置換
TABLE_RECORDS=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-table`

########################################
#tableにrecordsを嵌め込む
cat ${SYSD}/APPLI/${CATEGORY}/LISTS/HTML/TABLE.HTML |
sed -e "s|###TABLE_RECORDS###|${TABLE_RECORDS}|g"     > $tmp-table-html

########################################
# 改行文字を「\\n」という3文字の文字列に置換
TABLE=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-table-html`   

########################################
#tableをはめ込む
cat ${SYSD}/APPLI/${CATEGORY}/LISTS/HTML/SHOW.HTML            |
sed -e "s|###PARTS_NO###|${NUM}|g"                            |
sed -e "s|###PARTS_CATEGORY_NM###|$(cat $tmp-category-nm)|g"  |
sed -e "s|###PARTS_NM###|$(cat $tmp-parts-nm)|g"              |
sed -e "s|###PARTS_PRICE###|$(cat $tmp-price)|g"              |
sed -e "s|###CATEGORY_NM###|${CATEGORY_NM}|g"                 |
sed -e "s|###CATEGORY_NO###|${CATEGORY_NO}|g"                 |
sed -e "s|###PAGE###|${QRY_PAGE}|g"                           |
sed -e "s|###SEARCH###|${SEARCH}|g"                           |
sed -e "s|###TABLE###|${TABLE}|g"                             |
sed -e "s|###INFO_MSG###||g"                                  > $tmp-html

########################################
#page name
echo "Parts detail" > $tmp-pagename

########################################
echo "OK"
exit 0
