#!/bin/bash -vx
#

########################################
#	ASSESSMENT NEW PARTS INPUT.CGI
#
#   Arg
#       $1:$$   necessary
#
#	Written by hiramatsu


########################################
#基本設定
SYSD=$(cd $(dirname $0) && pwd | awk '{print substr($0, 0, index($0, "sureshotsystem")+13)}')
#exec 2> $SYSD/LOG/LOG.$(basename $0).$(date +%Y%m%d).$(date +%H%M%S).$$
tmp=/tmp/tmp_$1
LANG=ja_JP.UTF-8
#PATH=/home/:/home/UTL:/home/TOOL/open-usp-tukubai-2014061402/COMMANDS:$PATH
CATEGORY=`cat $tmp-category`
FUNC=`cat $tmp-func`
ACTION=`cat $tmp-action`
SUBACTION=`cat $tmp-sub-action`

########################################
#Check error
ERROR_CHECK(){
	[ $(plus ${PIPESTATUS[@]}) -eq 0 ] && return
cat <<- FIN
	Context-type: text/html
	NG input
FIN
	cat $tmp-result
	exit 1
}

########################################
#第二引数を取得
#ASS=${2:-0}

#######################################
#フォーム入力値を取得
MM=$REQUEST_METHOD
TEMP_NO=$(cat $tmp-get | cut -d'&' -f1 | sed s/TEMP_NO=// )

########################################
#仮登録Dir :/TMP/{stuffid}/ASSESSMENT/
TEMPD=${SYSD}/TMP/$(cat ${SYSD}/SESSION/$(session_get 'sureshot_stuff_session_id'))/ASSESSMENT

########################################
#ディレクトリを作成する
if [ -e "${TEMPD}"  ]; then
    :
else
    mkdir ${TEMPD}
    chmod -R 770 ${TEMPD}
    ERROR_CHECK
fi

#######################################
#TEMP_NOが取得出来なかった場合、
# 1.TEMP_NOを設定
# 2./TMP/ASSESSMENT/配下にTEMP_NO/を作成
# 3.customer,parts,operationの空ファイルを作成
if [ -z ${TEMP_NO} ]; then
    TEMP_NO=$(date +%Y%m%d)_$(date +%H%M%S)_$RANDOM
    mkdir ${TEMPD}/${TEMP_NO}
    touch ${TEMPD}/${TEMP_NO}/customer
    touch ${TEMPD}/${TEMP_NO}/parts
    touch ${TEMPD}/${TEMP_NO}/operation
    chmod 770 ${TEMPD}/${TEMP_NO}
fi

#######################################
#顧客情報を取得
CUSTOMER_NM=$(cat ${TEMPD}/${TEMP_NO}/customer | cut -d' ' -f 2)

#######################################
#パーツカテゴリを取得
cat ${SYSD}/DATA/PARTS_CATEGORY/LISTS/LV3/*[^_d]    |
LANG=C sort -nk1,1                                  > $tmp-category

########################################
#入力済みパーツリストのパーツカテゴリ
# 1;カテゴリ番号 2;カテゴリ名
mojihame -lRECORDS ${SYSD}/APPLI/${CATEGORY}/${FUNC}/HTML/${ACTION}/CATEGORY_LIST.HTML $tmp-category > $tmp-parts-category-list

########################################
#新規登録パーツ用のパーツカテゴリ
# 1;カテゴリ番号 2;カテゴリ名
mojihame -lRECORDS ${SYSD}/APPLI/${CATEGORY}/${FUNC}/HTML/${ACTION}/CATEGORY_NEW.HTML $tmp-category > $tmp-parts-category-new

########################################
# 改行文字を「\\n」という3文字の文字列に置換
CATEGORY_LIST=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-parts-category-list`
CATEGORY_NEW=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-parts-category-new`

#######################################
#仮登録部品情報を取得
cat ${TEMPD}/${TEMP_NO}/parts   |
juni                            > $tmp-juni
mojihame -lRECORDS ${SYSD}/APPLI/${CATEGORY}/${FUNC}/HTML/${ACTION}/RECORDS.HTML $tmp-juni  > $tmp-records

########################################
# 改行文字を「\\n」という3文字の文字列に置換
TABLE_RECORDS=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-records`

########################################
#tableにrecordsを嵌め込む
cat ${SYSD}/APPLI/${CATEGORY}/${FUNC}/HTML/${ACTION}/TABLE.HTML         |
sed -e "s|###TABLE_RECORDS###|${TABLE_RECORDS}|g"                       |
sed -e "s|###CATEGORY###|${CATEGORY_NEW}|g"                             > $tmp-table-html

########################################
# 改行文字を「\\n」という3文字の文字列に置換
TABLE=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-table-html`

########################################
#Making viweing body HTML filw path
cat ${SYSD}/APPLI/${CATEGORY}/${FUNC}/HTML/${ACTION}/${SUBACTION}.HTML  |
sed -e "s|###INFO_MSG###|部品を選択してください。|"                     |
sed -e "s|###ASSESSMENT_NO###|${TEMP_NO}|"                               |
sed -e "s|###TEMP_NO###|${TEMP_NO}|"                                     |
sed -e "s|###CUSTOMER_NM###|${CUSTOMER_NM}|"                            |
sed -e "s|###PARTS_CATEGORY###|${PARTS_CATEGORY}|"                      |
sed -e "s|###TABLE###|${TABLE}|g"                                       > $tmp-html|

########################################
##ending
echo "OK"
exit 0

