#!/bin/bash -vx
#

########################################
# SET_LIST/NEW/CONFIRM INPUT.CGI
#
#   $1:必須 $$
#
#	Written by hiramatsu


########################################
#基本設定
export LANG=ja_JP.utf8
echo $LANG
SYSD=$(cd $(dirname $0) && pwd | awk '{print substr($0, 0, index($0, "sureshotsystem")+13)}')
#exec 2> $SYSD/LOG/LOG.$(basename $0).$(date +%Y%m%d).$(date +%H%M%S).$$
tmp=/tmp/tmp_$1
LANG=ja_JP.UTF-8
#PATH=/home/:/home/UTL:/home/TOOL/open-usp-tukubai-2014061402/COMMANDS:$PATH
CATEGORY=`cat $tmp-category`
FUNC=`cat $tmp-func`
DATAD=${SYSD}/DATA/${CATEGORY}/LISTS

#######################################
#Check error
ERROR_CHECK(){
	[ $(plus ${PIPESTATUS[@]}) -eq 0 ] && return
cat <<- FIN
	Context-type: text/html
	NG input
FIN
	cat $tmp-result
	exit 1
}

########################################
#セットのバリデーション。NGならばセットに戻す。
#RESULT=`${SYSD}/APPLI/${CATEGORY}/${FUNC}/CGI/SET/CONFIRM $1`
#if [ "${RESULT}" != 'OK' ]; then
#    echo "NG"
#    exit 0
#fi

########################################
#仮登録を削除
#SESSION=$(session_get 'sureshot_stuff_session_id') 
#STUFF_ID=$(cat ${SYSD}/SESSION/${SESSION}
#TEMPD=${SYSD}/TMP/${STUFF_ID}
TEMPD=${SYSD}/TMP/$(cat ${SYSD}/SESSION/$(session_get 'sureshot_stuff_session_id'))/SET_LIST

########################################
#仮登録を取得
#SET_ARRY=(`cat ${TEMPD}/set_list`)
SET_CATEGORY_NO=$(cat ${TEMPD}/set_list | cut -d' ' -f1)
SET_CATEGORY_NM=$(cat ${TEMPD}/set_list | cut -d' ' -f2)
SET_NM=$(cat ${TEMPD}/set_list | cut -d' ' -f3)
SET_PRICE=$(cat ${TEMPD}/set_list | cut -d' ' -f4)
SET_REMARKS=$(cat ${TEMPD}/set_list | cut -d' ' -f5)

########################################
#Get records
cat ${TEMPD}/set_list_operation     |
juni                                |
LANG=C sort -nk1,1                  > $tmp-records
mojihame -lRECORDS_OPERATION ${SYSD}/APPLI/${CATEGORY}/${FUNC}/HTML/CONFIRM/OPERATION_RECORDS.HTML $tmp-records > $tmp-table-records-operaion

########################################
# 改行文字を「\\n」という3文字の文字列に置換
TABLE_RECORDS_OPERATION=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-table-records-operaion`

########################################
#Get records
cat ${TEMPD}/set_list_parts         |
juni                                |
LANG=C sort -nk1,1                  > $tmp-records
mojihame -lRECORDS_PARTS ${SYSD}/APPLI/${CATEGORY}/${FUNC}/HTML/CONFIRM/PARTS_RECORDS.HTML $tmp-records > $tmp-table-records-parts

########################################
# 改行文字を「\\n」という3文字の文字列に置換
TABLE_RECORDS_PARTS=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-table-records-parts`

########################################
#tableにrecordsを嵌め込む
cat ${SYSD}/APPLI/${CATEGORY}/${FUNC}/HTML/CONFIRM/TABLE.HTML         |
sed -e "s|###SET_CATEGORY_NM###|${SET_CATEGORY_NM}|g"                 |
sed -e "s|###SET_CATEGORY_NO###|${SET_CATEGORY_N0}|g"                 |
sed -e "s|###SET_NM###|${SET_NM}|g"                                   |
sed -e "s|###SET_PRICE###|${SET_PRICE}|g"                             |
sed -e "s|###SET_REMARKS###|${SET_REMARKS}|g"                         |
sed -e "s|###TABLE_RECORDS_OPERATION###|${TABLE_RECORDS_OPERATION}|g" |
sed -e "s|###TABLE_RECORDS_PARTS###|${TABLE_RECORDS_PARTS}|g"         > $tmp-table-html

########################################
# 改行文字を「\\n」という3文字の文字列に置換
TABLE=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-table-html`

########################################
#tableをはめ込む、ページャーを差し込む
cat ${SYSD}/APPLI/${CATEGORY}/NEW/HTML/PARTS/INPUT.HTML                 |
sed -e "s|###INFO_MSG###|"セットに登録する内容を確認してください。"|g"  |
sed -e "s|###TABLE###|${TABLE}|g"                                       > $tmp-html

########################################
#page name
echo "Set Confirm" > $tmp-pagename

########################################
echo "OK"
exit 0
