#!/bin/bash -evx
#

########################################
#	CUSTOMER NEW COMPLETE.CGI
#
#   引数
#       $1:プロセスID
#
#	Written by hiramatsu


########################################
#基本設定
SYSD=/home/sureshotsystem
#exec 2> ${SYSD}/LOG/LOG.$(basename $0).$(date +%Y%m%d).$(date +%H%M%S).$$
tmp=/tmp/tmp_$1
LANG=ja_JP.UTF-8
PATH=/home/:/home/UTL:/home/TOOL/open-usp-tukubai-2014061402/COMMANDS:$PATH
CATEGORY=`cat $tmp-category`
FUNC=`cat $tmp-func`
DATAD=${SYSD}/DATA/${CATEGORY}/LISTS

########################################
#Check error
ERROR_CHECK(){
	[ $(plus ${PIPESTATUS[@]}) -eq 0 ] && return
cat <<- FIN
	Context-type: text/html
	NG input
FIN
	cat $tmp-result
	exit 1
}

########################################
#顧客番号の次のロットを追加する
LATEST_NUM=$(ls ${SYSD}/DATA/NUMBERS/${CATEGORY}/ORIGIN | sort -nr | head -n 1)
START=$((LATEST_NUM + 1))
END=$((START + 1))
SEQ_STATUS=`${SYSD}/CGI/NUMBER_SEQ $1 ${CATEGORY} ${START} ${END} `
[[ ${SEQ_STATUS} != 'SUCCESS' ]] && exit 0

########################################
#新規顧客番号を確定する
NEW_NUM=`${SYSD}/CGI/NUMBERS $1 ${CATEGORY} `
[ ${NEW_NUM} = 'ERROR' ] && exit 0 || :

#######################################
#フォーム入力値を取得
VALUE1=$(nameread FIRST_NAME $tmp-post)
VALUE2=$(nameread GIVEN_NAME $tmp-post)
VALUE3=$(nameread EMAIL $tmp-post)
VALUE4=$(nameread PASSWORD $tmp-post)
#VALUE5=$(nameread ADMIN_FLAG $tmp-post)
VALUE5=0
VALUE6=$(nameread PHONE $tmp-post)

########################################
#日付を設定
CREATE_DATE=$(date +%Y%m%d%H%M%S)
UPDATE_DATE=$CREATE_DATE

########################################
#入力値を一時ファイル
# 顧客番号 姓 名 4.EMAIL 5.電話番号 6.作成日時 7.更新日時 8.ADMINフラグ 9.削除フラグ
echo ${NEW_NUM}" "${VALUE1}" "${VALUE2}" "${VALUE3}" "${VALUE6}" "${CREATE_DATE}" "${UPDATE_DATE}" "${VALUE5}" "0 > $tmp-customer

########################################
#データ格納
#LV1
$(mv $tmp-customer ${DATAD}/LV1/${NEW_NUM}_customer_${CREATE_DATE})
#LV2
cat ${DATAD}/LV1/${NEW_NUM}_customer_${CREATE_DATE} > ${DATAD}/LV2/${NEW_NUM}_customer_${CREATE_DATE}
#LV3
cat ${DATAD}/LV2/${NEW_NUM}_customer_${CREATE_DATE} |
awk '{print sprintf("%d %s %s %s %s %s %s %d %d /APP/STUFF/USERS/SHOW/?id=%d /APP/CUSTOMER/EDIT/INPUT/?id=%d /APP/CUSTOMER/DELETE/CONFIRM/?id=%d",$1,$2,$3,$4,$5,$6,$7,$8,$9,$1,$1,$1)}'  >   ${DATAD}/LV3/${NEW_NUM}_customer_${CREATE_DATE}

########################################
#HTMLの設定
ACTION=`cat $tmp-action`
cat ${SYSD}/APPLI/${CATEGORY}/${FUNC}/HTML/${ACTION}.HTML   |
sed -e "s/###FIRST_NAME_LABEL###/${VALUE1}/"                |
sed -e "s/###GIVEN_NAME_LABEL###/${VALUE2}/"                |
sed -e "s/###PHONE_LABEL###/${VALUE6}/"                     |
sed -e "s/###EMAIL_LABEL###/${VALUE3}/"                     > $tmp-html

#########################################
#page name
echo "Customer entry" > $tmp-pagename

###############################################################################
#ending
echo "OK"
#echo $COOK_SET
exit 0
