#!/bin/bash -evx
#

########################################
#	CUSTOMER SEARCH INPUT.CGI
#
#   引数
#
#	Written by hiramatsu


########################################
#基本設定
SYSD=/home/sureshotsystem
#exec 2> ${SYSD}/LOG/LOG.$(basename $0).$(date +%Y%m%d).$(date +%H%M%S).$$
tmp=/tmp/tmp_$1
LANG=ja_JP.UTF-8
PATH=/home/:/home/UTL:/home/TOOL/open-usp-tukubai-2014061402/COMMANDS:$PATH
CATEGORY=`cat $tmp-category`
FUNC=`cat $tmp-func`
DATAD=${SYSD}/DATA/CUSTOMER/LISTS

########################################
#Check error
ERROR_CHECK(){
	[ $(plus ${PIPESTATUS[@]}) -eq 0 ] && return
cat <<- FIN
	Context-type: text/html
	NG input
FIN
	cat $tmp-result
	exit 1
}

#######################################
#フォーム入力値を取得
#
sed -e 's/　/_/g' $tmp-post         > $tmp-search
nameread SEARCH_NAME $tmp-search    > $tmp-value1
cat $tmp-value1 | cut -d'_' -f1> $tmp-fname
cat $tmp-value1 | cut -d'_' -f2 > $tmp-gname

#######################################
#フォーム入力値を取得
nameread SEARCH_NAME $tmp-post    > $tmp-search-words

#######################################
#顧客名を曖昧検索
cat $tmp-search-words | sed "s/　/\\_/i" > $tmp-search-words2
WORDS=(` cat $tmp-search-words2 | tr '_' ' '`)
cat ${DATAD}/LV3/*[^_d] | LANG=C sort -nk1,1 | awk '{print}' > $tmp-base
for item in ${WORDS[@]}; do
    cat $tmp-base | awk '$2$3 ~ /'$item'/ {print}'  > $tmp-base2
    cat $tmp-base2 > $tmp-base
done
cat $tmp-base > $tmp-result

#######################################
#検索結果をリストボックス(HTML)に置く
mojihame -lRECORDS ${SYSD}/APPLI/${CATEGORY}/${FUNC}/HTML/DROPDOWN_LIST.HTML $tmp-result > $tmp-ajax-html

###############################################################################
#ending
echo "OK"
exit 0
