#!/bin/bash -evx
#

########################################
#	CUSTOMER SEARCH INPUT.CGI
#
#   引数
#
#	Written by hiramatsu


########################################
#基本設定
SYSD=/home/sureshotsystem
#exec 2> ${SYSD}/LOG/LOG.$(basename $0).$(date +%Y%m%d).$(date +%H%M%S).$$
tmp=/tmp/tmp_$1
LANG=ja_JP.UTF-8
PATH=/home/:/home/UTL:/home/TOOL/open-usp-tukubai-2014061402/COMMANDS:$PATH
CATEGORY=`cat $tmp-category`
FUNC=`cat $tmp-func`
DATAD=${SYSD}/DATA/CUSTOMER/LISTS

########################################
#Check error
ERROR_CHECK(){
	[ $(plus ${PIPESTATUS[@]}) -eq 0 ] && return
cat <<- FIN
	Context-type: text/html
	NG input
FIN
	cat $tmp-result
	exit 1
}

#######################################
#フォーム入力値を取得
#
sed -e 's/　/_/g' $tmp-post         > $tmp-search
nameread SEARCH_NAME $tmp-search    > $tmp-value1
cat $tmp-value1 | cut -d'_' -f1> $tmp-fname
cat $tmp-value1 | cut -d'_' -f2 > $tmp-gname

#######################################
#顧客名を曖昧検索
cat ${DATAD}/LV3/*[^_d]     |
awk '{print $1, $2, $3}'    |
LANG=C sort -nk1,1          |
awk -v f=$(cat $tmp-fname) -v g=$(cat $tmp-gname) '$1==f||$2==g'> $tmp-result

#######################################
#検索結果をリストボックス(HTML)に置く
mojihame -lRECORDS ${SYSD}/APPLI/${CATEGORY}/${FUNC}/HTML/LISTBOX.HTML $tmp-result > $tmp-ajax-html
exit 0

#########################################
#page name
echo "Customer entry" > $tmp-pagename

###############################################################################
#ending
echo "OK"
#echo $COOK_SET
exit 0
