#!/bin/bash -evx
#

########################################
#	STUFF NEW COMPLETE.CGI
#
#   引数
#       $1:プロセスID
#
#	Written by hiramatsu


########################################
#基本設定
SYSD=$(cd $(dirname $0) && pwd | awk '{print substr($0, 0, index($0, "sureshotsystem")+13)}')
#exec 2> ${SYSD}/LOG/LOG.$(basename $0).$(date +%Y%m%d).$(date +%H%M%S).$$
tmp=/tmp/tmp_$1
LANG=ja_JP.UTF-8
#PATH=/home/:/home/UTL:/home/TOOL/open-usp-tukubai-2014061402/COMMANDS:$PATH
CATEGORY=`cat $tmp-category`
FUNC=`cat $tmp-func`
STUFFD=${SYSD}/DATA/${CATEGORY}
LOGIND=${STUFFD}/LOGIN
USERSD=${STUFFD}/USERS
STUFF_SESS_ID='sureshot_stuff_session_id'

########################################
#Check error
ERROR_CHECK(){
	[ $(plus ${PIPESTATUS[@]}) -eq 0 ] && return
cat <<- FIN
	Context-type: text/html
	NG input
FIN
	cat $tmp-result
	exit 1
}

########################################
#フォーム値の設定
nameread FAMILY_NAME $tmp-post              | awk '{gsub(/^\_$/,"",$1);print}' > $tmp-value1
nameread GIVEN_NAME $tmp-post               | awk '{gsub(/^\_$/,"",$1);print}' > $tmp-value2
nameread EMAIL $tmp-post                    | awk '{gsub(/^\_$/,"",$1);print}' > $tmp-value3
nameread PASSWORD $tmp-post                 | awk '{gsub(/^\_$/,"",$1);print}' > $tmp-value4
nameread TEL1 $tmp-post                     | awk '{gsub(/^\_$/,"",$1);print}' > $tmp-value6
nameread TEL2 $tmp-post                     | awk '{gsub(/^\_$/,"",$1);print}' > $tmp-value7
nameread ADMIN $tmp-post                    | awk '{gsub(/^\_$/,"",$1);print}' > $tmp-value8

########################################
#バリデーションを設定

#FAMILY NAME
cat $tmp-value1 | awk '{print sprintf("FAMILY_NAME|ISNULL|%s",$1)}'       >> $tmp-validation  #必須入力
cat $tmp-value1 | awk '{print sprintf("FAMILY_NAME|LENGTH|%s,2,20",$1)}'  >> $tmp-validation  #length <=2 =>20

#GIVEN NAME
cat $tmp-value2 | awk '{print sprintf("GIVEN_NAME|ISNULL|%s",$1)}'        >> $tmp-validation  #必須入力
cat $tmp-value2 | awk '{print sprintf("GIVEN_NAME|LENGTH|%s,2,20",$1)}'   >> $tmp-validation  #length <=2 =>20

#EMAIL
cat $tmp-value3 | awk '{print sprintf("EMAIL|ISNULL|%s",$1)}'                   >> $tmp-validation  #必須入力
cat $tmp-value3 | awk '{print sprintf("EMAIL|DUPLICATE|STUFF,USERS,4,%s",$1)}'  >> $tmp-validation  #重複確認

#PASSWORD length <=8 
cat $tmp-value4 | awk '{print sprintf("PASSWORD|ISNULL|%s",$1)}'          >> $tmp-validation  #必須入力
cat $tmp-value4 | awk '{print sprintf("PASSWORD|LENGTH|%s,8,0",$1)}'      >> $tmp-validation  #length <=8 

#PASSWORD CONFIRMATION
#PASSWORDと同じ値を設定して必ず合格にする
cat $tmp-value4 | awk '{print sprintf("PW_CONFIRM|ISNULL|%s",$1)}'                            >> $tmp-validation  #必須入力
paste $tmp-value4 $tmp-value4 | awk '{print sprintf("PW_CONFIRM|COMPARE|SAME,%s,%s",$1,$2)}'  >> $tmp-validation  #=PASSWORD 

#TEL1
cat $tmp-value6 | awk '{print sprintf("TEL1|ISNULL|%s",$1)}'              >> $tmp-validation  #必須入力
cat $tmp-value6 | awk '{print sprintf("TEL1|MATCH|%s,-,1",$1)}'           >> $tmp-validation  #ハイフン必須
cat $tmp-value6 | awk '{print sprintf("TEL1|NUMERIC|%s,-",$1)}'           >> $tmp-validation  #ハイフン覗いたら数字のみ

#TEL2
cat $tmp-value7 | awk '{print sprintf("TEL2|MATCH|%s,-,1",$1)}'           >> $tmp-validation  #ハイフン必
cat $tmp-value7 | awk '{print sprintf("TEL2|NUMERIC|%s,-",$1)}'           >> $tmp-validation  #ハイフン覗いたら数字のみ

########################################
#バリデーションを実行
result=`${SYSD}/CGI/VALID/VALIDATION $1`

########################################
#管理者権限を取得
if [ "$(cat $tmp-value8)" = "1" ] ; then
  ADMIN_CHK="checked"
  ADMIN="管理者権限あり"
  ADMIN_VAL=1
else
  ADMIN_CHK=''
  ADMIN='管理者権限なし'
  ADMIN_VAL=0
fi

########################################
#パスワードの暗号化
echo $(sha1 $(cat $tmp-value4)) > $tmp-sha1

########################################
#HTMLの設定
if [ -n "$(grep "|NG" $tmp-valid-report)" ] ; then

    #Validation NG

    #########################################
    #入力画面HTMLを取得
    cat ${SYSD}/APPLI/${CATEGORY}/${FUNC}/HTML/INPUT.HTML > $tmp-html-tmp
    
    #########################################
    #バリデーション結果を元にメッセージとラベルカラーを設定
    result=`${SYSD}/CGI/VALID/ALERT_SETTING $1 - -`

    #########################################
    #上記処理からのHTMLを受け、入力値を設定し、HTMLを完成させる
    #CONFIRMからのバリデーションエラーのため、PWは削除
    cat $tmp-html-alert                                                 |
    sed -e "s/###FAMILY_NAME###/$(cat $tmp-value1)/"                    |
    sed -e "s/###GIVEN_NAME###/$(cat $tmp-value2)/"                     |
    sed -e "s/###EMAIL###/$(cat $tmp-value3)/"                          |
    sed -e "s/###TEL1###/$(cat $tmp-value6)/"                           |
    sed -e "s/###TEL2###/$(cat $tmp-value7)/"                           |
    sed -e "s/###PASSWORD###//"                                         |
    sed -e "s/###PW_CONFIRM###//"                                       |
    sed -e "s/###ADMIN_CHK###/${ADMIN_CHK}/"                            | 
    sed -e "s/###ADMIN_VAL###/${ADMIN_VAL}/"                            > $tmp-html

    #########################################
    #pege name
    echo "New stuff input" > $tmp-pagename
    
    exit 0
fi


########################################
#社員番号の次のロットを追加する
LATEST_NUM=$(ls ${SYSD}/DATA/NUMBERS/${CATEGORY}/ORIGIN | sort -nr | head -n 1)
START=$((LATEST_NUM + 1))
END=$((START + 3))
SEQ_STATUS=`${SYSD}/CGI/NUMBER_SEQ $1 ${CATEGORY} ${START} ${END} `
[[ ${SEQ_STATUS} != 'SUCCESS' ]] && exit 0

########################################
#新規の社員番号を確定する
STUFF_NUM=`${SYSD}/CGI/NUMBERS $1 'STUFF' `
[ ${STUFF_NUM} = 'ERROR' ] && exit 0 || :

#######################################
#Get Form Data
FAMILY_NAME=$(cat $tmp-value1)
GIVEN_NAME=$(cat $tmp-value2)
EMAIL=$(cat $tmp-value3)
PASSWORD=$(cat $tmp-value4)
TEL1=$(cat $tmp-value6)
TEL2=$(cat $tmp-value7)
[ -n "${TEL2}" ] && : || TEL2=${TEL1}
ADMIN_FLG=$(cat $tmp-value8)
[ "${ADMIN_FLG}" = "1" ] && ADMIN="管理者権限あり" || ADMIN='管理者権限なし'
DEL_FLG=0

########################################
#Set DATE
CREATE_DATE=$(date +%Y%m%d%H%M%S)
UPDATE_DATE=$CREATE_DATE

########################################
#更新者の取得
CREATE_USER=$(cat ${SYSD}/SESSION/$(session_get 'sureshot_stuff_session_id'))
UPDATE_USER=${CREATE_USER}

########################################
#       ログインデータ　
########################################

########################################
#ログインDirを作成
result=`${SYSD}/CGI/DATA/DFS_NEW $$ ${LOGIND} ${LOGIND}`

########################################
#一時ファイルに書き込み
echo ${STUFF_NUM} ${EMAIL} ${PASSWORD} ${CREATE_DATE} ${UPDATE_DATE} ${CREATE_USER} ${UPDATE_USER} 0 > $tmp-login

########################################
#データ配置
#LV1
mv $tmp-login ${LOGIND}/LV1/${STUFF_NUM}_login_${CREATE_DATE}
#LV2
cat ${LOGIND}/LV1/${STUFF_NUM}_login_${CREATE_DATE} | awk '{$NF=""; print $0}' > ${LOGIND}/LV2/${STUFF_NUM}_login_${CREATE_DATE}
#LV3(LV2と同じ)
cp -p ${LOGIND}/LV2/${STUFF_NUM}_login_${CREATE_DATE} ${LOGIND}/LV3/${STUFF_NUM}_login_${CREATE_DATE}


########################################
#       スタッフデータ　
########################################

########################################
#スタッフDirを作成
result=`${SYSD}/CGI/DATA/DFS_NEW $$ ${USERSD} ${USERSD}`

########################################
#一時ファイルに書き込み
#stuff_id	family_name	given_name	account_id	tel1	tel2	create_date	update_date	create_user	update_user	admin_flg	del_flg
echo ${STUFF_NUM} ${FAMILY_NAME} ${GIVEN_NAME} ${EMAIL} ${TEL1} ${TEL2} ${CREATE_DATE} ${UPDATE_DATE} ${CREATE_USER} ${UPDATE_USER} ${ADMIN_FLG} ${DEL_FLG} > $tmp-stuff

########################################
#データ配置
#LV1
#stuff_id	family_name	given_name	account_id	tel1	tel2	create_date	update_date	create_user	update_user	admin_flg	del_flg
mv $tmp-stuff ${USERSD}/LV1/${STUFF_NUM}_stuff_${CREATE_DATE}
#LV2
#stuff_id	family_name	given_name	account_id	tel1	tel2	create_date	update_date	create_user	update_user	admin_flg
#削除フラグはもたない-->dファイルにする
cat ${USERSD}/LV1/${STUFF_NUM}_stuff_${CREATE_DATE} | awk '{$NF=""; print $0}' > ${USERSD}/LV2/${STUFF_NUM}_stuff_${CREATE_DATE}
#LV3
#stuff_id	family_name	given_name	account_id	tel1	tel2	create_date	update_date	create_user	update_user	admin_flg	show_each_url	edit_each_url	delete_each_url
cat ${USERSD}/LV2/${STUFF_NUM}_stuff_${CREATE_DATE} |
awk '{print sprintf("%s\
/APP/STUFF/USERS?action=SHOW&id=%d \
/APP/STUFF/EDIT?action=INPUT&id=%d \
/APP/STUFF/DELETE?action=CONFIRM&id=%d"\
,$0,$1,$1,$1)}'  >   ${USERSD}/LV3/${STUFF_NUM}_stuff_${CREATE_DATE}

########################################
#HTMLの設定
ACTION=`cat $tmp-action`
cat ${SYSD}/APPLI/${CATEGORY}/${FUNC}/HTML/${ACTION}.HTML   |
sed -e "s/###FAMILY_NAME_LABEL###/${FAMILY_NAME}/"          |
sed -e "s/###GIVEN_NAME_LABEL###/${GIVEN_NAME}/"            |
sed -e "s/###EMAIL_LABEL###/${EMAIL}/"                      |
sed -e "s/###TEL1_LABEL###/${TEL1}/"                        |
sed -e "s/###TEL2_LABEL###/${TEL2}/"                        |
sed -e "s/###ADMIN_LABEL###/${ADMIN}/"                      > $tmp-html

#########################################
#pege name
echo "New stuff complete" > $tmp-pagename

###############################################################################
#ending
echo "OK"
exit 0
