#!/bin/bash -vx
#

########################################
#	STUFF NEW INPUT.CGI
#
#   Arg
#       $1:$$
#
#	Written by hiramatsu


########################################
#基本設定
SYSD=$(cd $(dirname $0) && pwd | awk '{print substr($0, 0, index($0, "sureshotsystem")+13)}')
#exec 2> $SYSD/LOG/LOG.$(basename $0).$(date +%Y%m%d).$(date +%H%M%S).$$
tmp=/tmp/tmp_$1
LANG=ja_JP.UTF-8
#PATH=/home/:/home/UTL:/home/TOOL/open-usp-tukubai-2014061402/COMMANDS:$PATH
CATEGORY=`cat $tmp-category`
FUNC=`cat $tmp-func`

########################################
#Check error
ERROR_CHECK(){
	[ $(plus ${PIPESTATUS[@]}) -eq 0 ] && return
cat <<- FIN
	Context-type: text/html
	NG input
FIN
	cat $tmp-result
	exit 1
}

########################################
#Making viweing body HTML filw path
ACTION=`cat $tmp-action`
cat ${SYSD}/APPLI/${CATEGORY}/${FUNC}/HTML/${ACTION}.HTML |
sed -e "s/###FAMILY_NAME_ERR###/hidden/"                  |
sed -e "s/###GIVEN_NAME_ERR###/hidden/"                   |
sed -e "s/###EMAIL_ERR###/hidden/"                        |
sed -e "s/###EMAIL_DUPLECATED###/hidden/"                 |
sed -e "s/###TEL1_ERR###/hidden/"                         |
sed -e "s/###TEL2_ERR###/hidden/"                         |
sed -e "s/###PASSWORD_ERR###/hidden/"                     |
sed -e "s/###PW_CONFIRM_ERR###/hidden/"                   |
sed -e "s/###ADMIN_ERR###/hidden/"                        |
sed -e "s/###FAMILY_NAME###//g"                           |
sed -e "s/###GIVEN_NAME###//g"                            |
sed -e "s/###EMAIL###//g"                                 |
sed -e "s/###TEL1###//g"                                  |
sed -e "s/###TEL2###//g"                                  |
sed -e "s/###PASSWORD###//g"                              |
sed -e "s/###PW_CONFIRM###//g"                            |
sed -e "s/###ADMIN_CHK###//"                              |
sed -e "s/###ADMIN_VAL###/0/"                             > $tmp-html

#########################################
#pege name
echo "New stuff input" > $tmp-pagename

#########################################
##ending
echo "OK"
exit 0

