#!/bin/bash -vx
#

########################################
#	AUTH.CGI
#
#   引数
#       $1:プロセスID
#
#	Written by hiramatsu


########################################
#基本設定
SYSD=/home/sureshotsystem
#exec 2> ${SYSD}/LOG/LOG.$(basename $0).$(date +%Y%m%d).$(date +%H%M%S).$$
tmp=/tmp/tmp_$1
LANG=ja_JP.UTF-8
PATH=/home/:/home/UTL:/usr/local/bin:/home/TOOL/open-usp-tukubai-2014061402/COMMANDS:$PATH
CATEGORY=`cat $tmp-category`
FUNC=`cat $tmp-func`
LOGIND=${SYSD}/DATA/STUFF/LOGIN

########################################
#Check error
ERROR_CHECK(){
	[ $(plus ${PIPESTATUS[@]}) -eq 0 ] && return
cat <<- FIN
	Context-type: text/html
	NG input
FIN
	cat $tmp-result
	exit 1
}

######################################
#Get Form Data
VALUE_ID=$(nameread ID $tmp-post)
VALUE_PW=$(nameread PASSWORD $tmp-post)

#######################################
#アカウントIDの暗号化
echo $(sha1 $VALUE_ID) > $tmp-sha1-id
ID=$(cat $tmp-sha1-id)

#######################################
#IDを保存(ローテート必要)
echo $VALUE_ID > ${SYSD}/SYS/STUFF/LOGIN/${ID}

#######################################
#パスワードの暗号化
echo $(sha1 $VALUE_PW) > $tmp-sha1-pw
PW=$(cat $tmp-sha1-pw)

#######################################
#AUTH
cat ${LOGIND}/LV3/*   | awk -v id=$VALUE_ID -v pw=$PW '$2==id&&$3==pw&&$6==0{print}' > $tmp-auth

########################################
#SET LOGIN SESSION
if [ -n "$(cat $tmp-auth)" ] ; then
    #ログインセッション用クッキー設定文字列
    STUFF_SESS_ID='sureshot_stuff_session_id'
    COOK=`${SYSD}/CGI/SESSION/SESSION_SET ${STUFF_SESS_ID} `
    echo $COOK > $tmp-cook-login

    #ログインアカウント用クッキー設定文字列
    STUFF_SESS_AC='sureshot_stuff_session_ac'
    COOK=`${SYSD}/CGI/SESSION/SESSION_SET ${STUFF_SESS_AC} 15 ${VALUE_ID}`
    echo $COOK > $tmp-cook-account
    
fi

#######################################
#HTMLの設定
if [ -z "$(cat $tmp-auth)" ] ; then
    ACTION=INPUT
    cat ${SYSD}/APPLI/${CATEGORY}/${FUNC}/HTML/${ACTION}.HTML           |
    sed -e "s/###INFO_LV###/danger/"                                    |
    sed -e "s/###AUTH_MSG###/Account ID or Password was incomplete./"   |
    sed -e "s/###ID_VALUE###/${VALUE_ID}/"                              |
    sed -e "s/###PASSWORD_VALUE###//"                                   > $tmp-html
else
    if [ -z  $( cat $tmp-return-url ) ] ; then
        cat ${SYSD}/HTML/INDEX.HTML > $tmp-html
    else
        echo ${SYSD}/$( cat $tmp-return-url ) > $tmp-html
    fi
fi

###############################################################################
#ending
echo "OK"
exit 0



