#!/bin/bash -evx
#

########################################
#	OUT.CGI
#
#       ログアウトを組み込んだ際には、必ず、アカウントのセッションも削除するように
#       引数を使って自由にセッションを削除できるように実装すること
#
#       $1:$$
#       $2:セッションID　デフォルト：sureshot_stuff_session_id
#
#	Written by hiramatsu


########################################
#基本設定
SYSD=$(cd $(dirname $0) && pwd | awk '{print substr($0, 0, index($0, "sureshotsystem")+13)}')
#exec 2> ${SYSD}/LOG/LOG.$(basename $0).$(date +%Y%m%d).$(date +%H%M%S).$$
tmp=/tmp/tmp_$1
LANG=ja_JP.UTF-8
#PATH=/home/:/home/UTL:/usr/local/bin:/home/TOOL/open-usp-tukubai-2014061402/COMMANDS:$PATH
SESSION_FILED=${SYSD}/SESSION
STUFF_SESS_ID=${2:-sureshot_stuff_session_id}

########################################
#Check error
ERROR_CHECK(){
	[ $(plus ${PIPESTATUS[@]}) -eq 0 ] && return
cat <<- FIN
	Context-type: text/html
	NG input
FIN
	cat $tmp-result
	exit 1
}

########################################
#Make cookie words for session
COOK=`${SYSD}/CGI/SESSION/SESSION_SET ${STUFF_SESS_ID} -2000`
echo $COOK > $tmp-cook
ERROR_CHECK

#######################################
#Get session
SESS=$(session_get ${STUFF_SESS_ID})
ERROR_CHECK

########################################
#Delete session file
if [ -z "${SESS}" ]; then
  :
else
  rm -f "${SESSION_FILED}/${SESS}"
  ERROR_CHECK
fi

#######################################
#HTMLの設定
cat ${SYSD}/HTML/INDEX.HTML > $tmp-html 

#########################################
#ページ名
echo "Top" > $tmp-pagename

#######################################
#ending
echo "OK"
exit 0



