#!/bin/bash -vx
#

########################################
# PARTS_LIST/LISTS PAGER.CGI
#
#   $1:必須 $$
#   $2:必須 QRY_PAGE(num)
#   $3:必須 SEARCH(char:search=0 or search=1)
#   $4:任意 PAGE_CATEGORY_NM(char:カテゴリ名)
#   $5:任意 PAGE_CATEGORY_NO(num:カテゴリNo)
#
#	Written by hiramatsu


########################################
#基本設定
export LANG=ja_JP.utf8
echo $LANG
SYSD=$(cd $(dirname $0) && pwd | awk '{print substr($0, 0, index($0, "sureshotsystem")+13)}')
#exec 2> $SYSD/LOG/LOG.$(basename $0).$(date +%Y%m%d).$(date +%H%M%S).$$
tmp=/tmp/tmp_$1
LANG=ja_JP.UTF-8
#PATH=/home/:/home/UTL:/home/TOOL/open-usp-tukubai-2014061402/COMMANDS:$PATH
CATEGORY=`cat $tmp-category`
FUNC='LISTS'
DATAD=${SYSD}/DATA/${CATEGORY}/LISTS

#######################################
#Check error
ERROR_CHECK(){
	[ $(plus ${PIPESTATUS[@]}) -eq 0 ] && return
cat <<- FIN
	Context-type: text/html
	NG input
FIN
	cat $tmp-result
	exit 1
}

#######################################
#引数取得
QRY_PAGE=$2
SEARCH=$3
PAGE_CATEGORY_NM=${4:-'ALL'}
PAGE_CATEGORY_NO=${5:-0}

#######################################
#最大表示レコード数設定ファイルの確認
if [ -e ${SYSD}/SYS/VIEW/${CATEGORY}/${FUNC}/VIEW_MAX_RECORDS ]; then
    :
else    
    mkdir ${SYSD}/SYS/VIEW/${CATEGORY}    
    mkdir ${SYSD}/SYS/VIEW/${CATEGORY}/${FUNC}
    cp ${SYSD}/SYS/VIEW/ORG_VIEW_MAX/VIEW_MAX_RECORDS ${SYSD}/SYS/VIEW/${CATEGORY}/${FUNC}/
    cp ${SYSD}/SYS/VIEW/ORG_VIEW_MAX/VIEW_MAX_PAGES ${SYSD}/SYS/VIEW/${CATEGORY}/${FUNC}/
fi

#######################################
#最大表示レコード数
VIEW_MAX_RECORDS=$(cat ${SYSD}/SYS/VIEW/${CATEGORY}/${FUNC}/VIEW_MAX_RECORDS | awk '{print $2}')

########################################
#最大表示ページ数
VIEW_MAX_PAGES=$(cat ${SYSD}/SYS/VIEW/${CATEGORY}/${FUNC}/VIEW_MAX_PAGES | awk '{print $2}')

########################################
#Set record start & end
if [ -z $(echo ${QRY_PAGE}) ] || [ "${QRY_PAGE}" = 1 ]; then
    SHOW_PAGE=1
    START=1
    END=${VIEW_MAX_RECORDS}
else
    SHOW_PAGE=${QRY_PAGE}
    END=$(expr ${QRY_PAGE} \* ${VIEW_MAX_RECORDS} )
    START=$(expr ${END} - ${VIEW_MAX_RECORDS} + 1 )
fi

########################################
#呼び出し元に開始と終了を返す
echo ${START} > $tmp-rec-start
echo ${END} > $tmp-rec-end

########################################
#レコード件数を取得
if [ "${PAGE_CATEGORY_NO}" -gt 0 ] ; then
    RECORDS=$(cat ${DATAD}/${PAGE_CATEGORY_NO}/LV3/*[^_d] | wc -l)
else
    RECORDS=$( ls ${DATAD}/*/LV3/*[^_d] | wc -l )
fi

########################################
#ページャーを設定
RESULT=`${SYSD}/CGI/PAGINATION/PAGER \
                          $1 \
                          "/APP/${CATEGORY}/${FUNC}" \
                          ${SHOW_PAGE} \
                          ${RECORDS} \
                          ${VIEW_MAX_RECORDS} \
                          ${VIEW_MAX_PAGES} \
                          "SHOW" \
                          "&${SEARCH}" \
                          "&category-nm=${PAGE_CATEGORY_NM}" \
                          "&category-no=${PAGE_CATEGORY_NO}"`

########################################
echo 'ok'
exit 0
