#!/bin/bash -vx
#

########################################
#	PAGER_AJAX.CGI
#
#   $1:必須 $$
#   $4:必須 LINK_URL
#   $5:任意 pageクエリパラメータ

#	Written by hiramatsu


########################################
#基本設定
SYSD=/home/sureshotsystem
#exec 2> $SYSD/LOG/LOG.$(basename $0).$(date +%Y%m%d).$(date +%H%M%S).$$
tmp=/tmp/tmp_$1
LANG=ja_JP.UTF-8
PATH=/home/:/home/UTL:/home/TOOL/open-usp-tukubai-2014061402/COMMANDS:$PATH
CATEGORY=`cat $tmp-category`
FUNC=`cat $tmp-func`
DATAD=${SYSD}/DATA/${CATEGORY}/LISTS


#######################################
#Check error
ERROR_CHECK(){
	[ $(plus ${PIPESTATUS[@]}) -eq 0 ] && return
cat <<- FIN
	Context-type: text/html
	NG input
FIN
	cat $tmp-result
	exit 1
}

#######################################
#フォームの入力値を取得
PARTS_CATEGORY=$(nameread PAGER_FILTER $tmp-post)
PAGER_LINK_URL=$(nameread PAGER_LINK_URL $tmp-post)

########################################
#最大表示レコード数
cat ${SYSD}/SYS/${CATEGORY}/${FUNC}/VIEW_MAX_RECORDS | 
awk '{print $2}' > $tmp-max-records
VIEW_MAX_RECORDS=$( cat $tmp-max-records )

########################################
#最大表示ページ数
cat ${SYSD}/SYS/${CATEGORY}/${FUNC}/VIEW_MAX_PAGES | 
awk '{print $2}' > $tmp-max-pages
VIEW_MAX_PAGES=$( cat $tmp-max-pages )

########################################
#Get querystring
QRY_PAGE=$( echo $5 | sed -e 's/^.*\(page\=[0-9]*\).*$/\1/' | sed -e 's/page\=//')

########################################
#Set record start & end
if [ -z $(echo ${QRY_PAGE}) ]; then
    SHOW_PAGE=1
    START=1
    END=${VIEW_MAX_RECORDS}
else
    SHOW_PAGE=${QRY_PAGE}
    END=$(expr ${QRY_PAGE} \* ${VIEW_MAX_RECORDS} )
    START=$(expr ${END} - ${VIEW_MAX_RECORDS} + 1 )
fi

########################################
#表示レコード数を取得
cat ${SYSD}/DATA/${CATEGORY}/LISTS/LV3/*[^_d]   |
awk -v c=${PARTS_CATEGORY} '$2==c{print}'       |
juni                                            |
tail -n 1                                       |
awk '{print $1}'                                > $tmp-record-count
RECORDS=$( cat $tmp-record-count)

########################################
#ページャーの必要有無を確認(レコード総数が最大表示数以下→ページャー不必要)
if [ ${RECORDS} -le ${PAGE_MAX_VIEW_RECORDS} ]; then
    echo ''> $tmp-ajax-html
    exit 0
fi

########################################
#ページャーを設定
RESULT=`${SYSD}/CGI/PAGER $1 ${PAGER_LINK_URL} ${SHOW_PAGE} ${RECORDS} ${VIEW_MAX_RECORDS} ${VIEW_MAX_PAGES} "&category=${PARTS_CATEGORY}" "&ff=22" `

########################################
#AJAX用HTMLを出力
cat $tmp-pager-html |
sed -e 's|\\n||g'   > $tmp-ajax-html


########################################
echo "OK"
exit 0
