#!/bin/bash -vx
#

########################################
#	SHOW.CGI
#
#   $1:必須 $$
#
#	Written by hiramatsu


########################################
#基本設定
SYSD=/home/sureshotsystem
#exec 2> $SYSD/LOG/LOG.$(basename $0).$(date +%Y%m%d).$(date +%H%M%S).$$
tmp=/tmp/tmp_$1
LANG=ja_JP.UTF-8
PATH=/home/:/home/UTL:/home/TOOL/open-usp-tukubai-2014061402/COMMANDS:$PATH
CATEGORY=`cat $tmp-category`
FUNC=`cat $tmp-func`
DATAD=${SYSD}/DATA/${CATEGORY}/LISTS

#######################################
#Check error
ERROR_CHECK(){
	[ $(plus ${PIPESTATUS[@]}) -eq 0 ] && return
cat <<- FIN
	Context-type: text/html
	NG input
FIN
	cat $tmp-result
	exit 1
}

########################################
#最大表示レコード数
cat ${SYSD}/SYS/${CATEGORY}/${FUNC}/VIEW_MAX_RECORDS | 
awk '{print $2}' > $tmp-max-records
VIEW_MAX_RECORDS=$( cat $tmp-max-records )

########################################
#最大表示ページ数
cat ${SYSD}/SYS/${CATEGORY}/${FUNC}/VIEW_MAX_PAGES | 
awk '{print $2}' > $tmp-max-pages
VIEW_MAX_PAGES=$( cat $tmp-max-pages )

########################################
#Get querystring
QRY_PAGE=$( cat $tmp-get | sed -e 's/^.*\(page\=[0-9]*\).*$/\1/' | sed -e 's/page\=//')
QRY_DISP=$( cat $tmp-get | sed -e 's/^.*\(disp\=[0-9]*\).*$/\1/' | sed -e 's/disp\=//')

########################################
#Set record start & end
if [ -z $(echo ${QRY_PAGE}) ]; then
    SHOW_PAGE=1
    START=1
    END=${VIEW_MAX_RECORDS}
else
    SHOW_PAGE=${QRY_PAGE}
    END=$(expr ${QRY_PAGE} \* ${VIEW_MAX_RECORDS} )
    START=$(expr ${END} - ${VIEW_MAX_RECORDS} + 1 )
fi

########################################
#ページャーを設定
RECORDS=$( ls ${SYSD}/DATA/${CATEGORY}/LISTS/LV3/*[^_d] | wc -l )
RESULT=`${SYSD}/CGI/PAGER $1 "/APP/PARTS_LIST/LISTS/SHOW" ${SHOW_PAGE} ${RECORDS} ${VIEW_MAX_RECORDS} ${VIEW_MAX_PAGES}`

#######################################
#フォームの入力値を取得
cat $tmp-post
PAGE_FILTER=$(nameread PARTS_CATEGORY_NAME_HIDDEN_PAGE $tmp-post)

########################################
#パーツカテゴリを取得
cat ${SYSD}/DATA/PARTS_CATEGORY/LISTS/LV3/*[^_d]    |
LANG=C sort -nk1,1                                  > $tmp-category

########################################
#Page絞り込み用のパーツカテゴリ
# 1;カテゴリ番号 2;カテゴリ名
mojihame -lRECORDS ${SYSD}/APPLI/${CATEGORY}/LISTS/HTML/CATEGORY_PAGE.HTML $tmp-category > $tmp-parts-category-page

########################################
#登録済パーツ用のパーツカテゴリ
# 1;カテゴリ番号 2;カテゴリ名
mojihame -lRECORDS ${SYSD}/APPLI/${CATEGORY}/LISTS/HTML/CATEGORY_LIST.HTML $tmp-category > $tmp-parts-category-list

########################################
#新規登録パーツ用のパーツカテゴリ
# 1;カテゴリ番号 2;カテゴリ名
mojihame -lRECORDS ${SYSD}/APPLI/${CATEGORY}/LISTS/HTML/CATEGORY_NEW.HTML $tmp-category > $tmp-parts-category-new

########################################
# 改行文字を「\\n」という3文字の文字列に置換
PARTS_CATEGORY_PAGE=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-parts-category-page`
PARTS_CATEGORY_LIST=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-parts-category-list`
PARTS_CATEGORY_NEW=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-parts-category-new`

########################################
#パーツリストを取得
if [ -n "${PAGE_FILTER}" -a "${PAGE_FILTER}" != 'ALL' ] ; then
    cat ${DATAD}/LV3/*[^_d]                             |
    LANG=C sort -nk1,1                                  |
    awk -v c=${PAGE_FILTER} '$2==c{print}'              |
    awk -v s=${START} -v e=${END} 'NR>=s&&NR<=e&&$9!=1' |
    juni                                                > $tmp-records
else
    cat ${DATAD}/LV3/*[^_d]                             |
    LANG=C sort -nk1,1                                  |
    awk -v s=${START} -v e=${END} 'NR>=s&&NR<=e&&$9!=1' |
    juni                                                > $tmp-records
fi
# 1;カテゴリ番号 2;カテゴリ名
mojihame -lRECORDS ${SYSD}/APPLI/${CATEGORY}/${FUNC}/HTML/RECORDS.HTML $tmp-records > $tmp-table-records
cat $tmp-table-records              |
sed -e "s|###PARTS_CATEGORY###|${PARTS_CATEGORY_LIST}|g"                            > $tmp-table-records2

########################################
# 改行文字を「\\n」という3文字の文字列に置換
TABLE_RECORDS=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-table-records2`

########################################
#絞込の場合
#tableにrecordsを嵌め込み、ここで終了
if [ -n "${PAGE_FILTER}" ] ; then
    cat ${SYSD}/APPLI/${CATEGORY}/LISTS/HTML/TABLE.HTML             |
    sed -e "s|###TABLE_RECORDS###|${TABLE_RECORDS}|g"               |
    sed -e "s|###PARTS_CATEGORY###|${PARTS_CATEGORY_NEW}|g"         > $tmp-ajax-html
    echo "OK"
    exit 0
fi

########################################
#tableにrecordsを嵌め込む
cat ${SYSD}/APPLI/${CATEGORY}/LISTS/HTML/TABLE.HTML             |
sed -e "s|###TABLE_RECORDS###|${TABLE_RECORDS}|g"               |
sed -e "s|###PARTS_CATEGORY###|${PARTS_CATEGORY_NEW}|g"         > $tmp-table-html

########################################
# 改行文字を「\\n」という3文字の文字列に置換
TABLE=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-table-html`

########################################
#tableをはめ込む、ページャーを差し込む
cat ${SYSD}/APPLI/${CATEGORY}/LISTS/HTML/SHOW.HTML              |
sed -e "s|###PARTS_CATEGORY###|${PARTS_CATEGORY_PAGE}|g"        |
sed -e "s|###TABLE###|${TABLE}|g"                               |
sed -e "s|###INFO_MSG###||g"                                    |
sed -e "s|###PAGER###|$(cat $tmp-pager-html)|g"                 > $tmp-html

########################################
echo "OK"
exit 0
