#!/bin/bash -evx
#

########################################
#   APPRAISAL/NEW/OPERATION/COMPLETE.CGI
#
#   引数
#       $1:プロセスID
#
#	Written by hiramatsu


########################################
#基本設定
SYSD=$(cd $(dirname $0) && pwd | awk '{print substr($0, 0, index($0, "sureshotsystem")+13)}')
#exec 2> ${SYSD}/LOG/LOG.$(basename $0).$(date +%Y%m%d).$(date +%H%M%S).$$
tmp=/tmp/tmp_$1
LANG=ja_JP.UTF-8
#PATH=/home/:/home/UTL:/home/TOOL/open-usp-tukubai-2014061402/COMMANDS:$PATH
CATEGORY=`cat $tmp-category`
FUNC=`cat $tmp-func`

########################################
#Check error
ERROR_CHECK(){
	[ $(plus ${PIPESTATUS[@]}) -eq 0 ] && return
cat <<- FIN
	Context-type: text/html
	NG input
FIN
	cat $tmp-result
	exit 1
}

########################################
#作業カテゴリ更新中は、処理をさせない
#ls ${SYSD}/LOCK/OPERATION_CATEGORY/* > $tmp-checker 2> /dev/null
#if [ -n cat $tmp-checker ] ; then
#    echo "333" > $tmp-ajax-html
#    exit 0
#fi

#######################################
#フォーム入力値を取得
ACTION=$(nameread ACTION $tmp-post)
ROW=$(nameread ROW $tmp-post)
TEMP_NO=$(nameread TEMP_NO $tmp-post)
CATE_NM=$(nameread CATEGORY_NM $tmp-post)   #作業カテゴリ名
CATE_NO=$(nameread CATEGORY_NO $tmp-post)   #作業カテゴリ番号
OPERATION_NM=$(nameread OPERATION_NM $tmp-post)     #作業名
OPERATION_NO=$(nameread OPERATION_NO $tmp-post)     #作業番号
PRICE=$(nameread OPERATION_PRICE $tmp-post)     #プライス
QTY=$(nameread OPERATION_QTY $tmp-post)         #数量

########################################
#仮登録Dir :/TMP/{stuffid}/APPRAISAL/
TEMPD=${SYSD}/TMP/$(cat ${SYSD}/SESSION/$(session_get 'sureshot_stuff_session_id'))/APPRAISAL/${TEMP_NO}

########################################
#ACTIONで振り分け
case ${ACTION} in
ADD)    #追加
  #1:カテゴリ番号、2:カテゴリ名、3:作業番号、4:作業名、5:価格、6:数量
  echo ${CATE_NO}" "${CATE_NM}" "${OPERATION_NO}" "${OPERATION_NM}" "${PRICE}" "${QTY}  >> ${TEMPD}/operation
  #空行を削除
  cat ${TEMPD}/operation | awk /./ > $tmp-operation
  ;;
EDIT)   #変更
  cat ${TEMPD}/operation | 
  awk \
      -v row=${ROW} \
      -v cate_no=${CATE_NO} -v cate_nm=${CATE_NM} \
      -v operation_no=${OPERATION_NO} -v operation_nm=${OPERATION_NM} \
      -v price=${PRICE} \
      -v qty=${QTY} \
      'NR!=row{print} \
      NR==row{print(cate_no, cate_nm, operation_no, operation_nm, price, qty)}' \
      > $tmp-operation
  ;;
DELETE) #削除
  cat ${TEMPD}/operation | awk -v d=${ROW} 'NR!=d{print}' > $tmp-operation
  ;;
esac

########################################
#作業を仮登録
cat $tmp-operation > ${TEMPD}/operation

########################################
#作業カテゴリを取得
cat ${SYSD}/DATA/OPERATION_CATEGORY/LISTS/LV3/*[^_d]  |
LANG=C sort -nk1,1                                    > $tmp-category

########################################
#登録済作業用の作業カテゴリ
# 1;カテゴリ番号 2;カテゴリ名
mojihame -lRECORDS ${SYSD}/APPLI/APPRAISAL/NEW/HTML/OPERATION/CATEGORY_LIST.HTML $tmp-category > $tmp-operation-category-list

#######################################
# 改行文字を「\\n」という3文字の文字列に置換
CATEGORY_LIST=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-operation-category-list`

########################################
#作業リストを取得
cat ${TEMPD}/operation  |
juni                    > $tmp-records
#1:順位、2:カテゴリ番号、3:カテゴリ名、4:作業番号、5:作業名、6:価格、7:数量
mojihame -lRECORDS ${SYSD}/APPLI/APPRAISAL/NEW/HTML/OPERATION/RECORDS.HTML $tmp-records > $tmp-table-records

########################################
#作業リストに作業カテゴリリストを嵌め込む
cat $tmp-table-records                         |
sed -e "s|###CATEGORY###|${CATEGORY_LIST}|g"   > $tmp-table-records2

########################################
# 改行文字を「\\n」という3文字の文字列に置換
TABLE_RECORDS=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-table-records2`

echo ${TABLE_RECORDS} > /tmp/vvvvvv

########################################
#新規登録作業用の作業カテゴリ
# 1;カテゴリ番号 2;カテゴリ名
mojihame -lRECORDS ${SYSD}/APPLI/APPRAISAL/NEW/HTML/OPERATION/CATEGORY_NEW.HTML $tmp-category > $tmp-operation-category-new

########################################
# 改行文字を「\\n」という3文字の文字列に置換
CATEGORY_NEW=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-operation-category-new`

########################################
#tableにrecordsを嵌め込む
cat ${SYSD}/APPLI/APPRAISAL/NEW/HTML/OPERATION/TABLE.HTML  |
sed -e "s|###CATEGORY###|${CATEGORY_NEW}|g"                 |
sed -e "s|###TABLE_RECORDS###|${TABLE_RECORDS}|g"           > $tmp-ajax-html

########################################
#ending
echo "OK"
exit 0
