#!/bin/bash -vx
#

########################################
#	APPRAISAL EDIT OPERATION INPUT.CGI
#
#   Arg
#       $1:$$   necessary
#
#	Written by hiramatsu


########################################
#基本設定
SYSD=$(cd $(dirname $0) && pwd | awk '{print substr($0, 0, index($0, "sureshotsystem")+13)}')
#exec 2> $SYSD/LOG/LOG.$(basename $0).$(date +%Y%m%d).$(date +%H%M%S).$$
tmp=/tmp/tmp_$1
LANG=ja_JP.UTF-8
#PATH=/home/:/home/UTL:/home/TOOL/open-usp-tukubai-2014061402/COMMANDS:$PATH
CATEGORY=`cat $tmp-category`
FUNC=`cat $tmp-func`
ACTION=`cat $tmp-action`
SUB_ACTION=`cat $tmp-sub-action`
DATAD=${SYSD}/DATA/${CATEGORY}/LISTS

########################################
#Check error
ERROR_CHECK(){
	[ $(plus ${PIPESTATUS[@]}) -eq 0 ] && return
cat <<- FIN
	Context-type: text/html
	NG input
FIN
	cat $tmp-result
	exit 1
}

#######################################
#フォーム入力値を取得
APPRAISAL_NO=$(cat $tmp-get | cut -d'&' -f1 | sed s/APPRAISAL_NO=// )

########################################
#査定済のファイルの仮ファイル作成する
TEMP_NO=$(cat $(ls ${DATAD}/LV3/${APPRAISAL_NO}_appraisal_customer_*) | cut -d' ' -f2) 

########################################
#仮登録Dir :/TMP/{stuffid}/APPRAISAL/
TEMPD=${SYSD}/TMP/$(cat ${SYSD}/SESSION/$(session_get 'sureshot_stuff_session_id'))/APPRAISAL/${TEMP_NO}

#######################################
#顧客情報を取得
CUSTOMER_NO=$(cat ${TEMPD}/customer | cut -d' ' -f3)
CUSTOMER_NM=$(cat ${TEMPD}/customer | cut -d' ' -f4)

#######################################
#TEMP_NOが取得出来なかった場合-->異常
if [ -z ${APPRAISAL_NO} ]; then
  #CUSTOMER INPUTへ戻す
  REDIRECT_FORCE="/APP/APPRAISAL/LIST/SHOW"
else
  #ヘッダーインフォ設定
  INFO_MSG="見積番号 : ${APPRAISAL_NO}"
  APPRAISAL_INFO="査定番号 : "${TEMP_NO}  
  CUSTOMER_INFO="お客様 : "`echo ${CUSTOMER_NO}  ${CUSTOMER_NM}`
fi

#######################################
#作業カテゴリを取得
cat ${SYSD}/DATA/OPERATION_CATEGORY/LISTS/LV3/*[^_d]    |
LANG=C sort -nk1,1                                  > $tmp-category

########################################
#入力済み作業リストの作業カテゴリ
# 1;カテゴリ番号 2;カテゴリ名
mojihame -lRECORDS ${SYSD}/APPLI/${CATEGORY}/${FUNC}/HTML/${ACTION}/CATEGORY_LIST.HTML $tmp-category > $tmp-operation-category-list

########################################
#新規登録作業用の作業カテゴリ
# 1;カテゴリ番号 2;カテゴリ名
mojihame -lRECORDS ${SYSD}/APPLI/${CATEGORY}/${FUNC}/HTML/${ACTION}/CATEGORY_NEW.HTML $tmp-category > $tmp-operation-category-new

########################################
# 改行文字を「\\n」という3文字の文字列に置換
CATEGORY_LIST=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-operation-category-list`
CATEGORY_NEW=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-operation-category-new`

#######################################
#登録作業情報を取得
#1 20170701_172259_3387 1 オイル交換 2 oil1 3000 1 20170701173352 20170701173352
if [ -n "$(cat ${TEMPD}/operation)" ]; then
  cat ${TEMPD}/operation  |
  juni                    > $tmp-juni
  mojihame -lRECORDS ${SYSD}/APPLI/${CATEGORY}/${FUNC}/HTML/${ACTION}/RECORDS.HTML $tmp-juni  > $tmp-records
fi

########################################
# 改行文字を「\\n」という3文字の文字列に置換
TABLE_RECORDS=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-records`

########################################
#tableにrecordsを嵌め込む
cat ${SYSD}/APPLI/${CATEGORY}/${FUNC}/HTML/${ACTION}/TABLE.HTML         |
sed -e "s|###TABLE_RECORDS###|${TABLE_RECORDS}|g"                       |
sed -e "s|###CATEGORY###|${CATEGORY_NEW}|g"                             > $tmp-table-html

########################################
# 改行文字を「\\n」という3文字の文字列に置換
TABLE=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-table-html`

########################################
#Making viweing body HTML filw path
cat ${SYSD}/APPLI/${CATEGORY}/${FUNC}/HTML/${ACTION}/${SUB_ACTION}.HTML |
sed -e "s|###REDIRECT_FORCE###|${REDIRECT_FORCE}|"                      |
sed -e "s/###INFO_MSG###/${INFO_MSG}/"                                  |
sed -e "s/###APPRAISAL_INFO###/${APPRAISAL_INFO}/"                      |
sed -e "s/###CUSTOMER_INFO###/${CUSTOMER_INFO}/"                        |
sed -e "s/###APPRAISAL_NO###/${APPRAISAL_NO}/"                          |
sed -e "s/###TEMP_NO###/${TEMP_NO}/"                                    |
sed -e "s|###CUSTOMER_NM###|${CUSTOMER_NM}|"                            |
sed -e "s|###OPERATION_CATEGORY###|${OPERATION_CATEGORY}|"              |
sed -e "s|###TABLE###|${TABLE}|g"                                       > $tmp-html|

#########################################
#page name
echo "Appraisal operation edit" > $tmp-pagename

########################################
##ending
echo "OK"
exit 0

