#!/bin/bash -evx
#

########################################
#	PARTS_CATEGORY NEW COMPLETE.CGI
#
#   引数
#       $1:プロセスID
#
#	Written by hiramatsu


########################################
#基本設定
SYSD=$(cd $(dirname $0) && pwd | awk '{print substr($0, 0, index($0, "sureshotsystem")+13)}')
#exec 2> ${SYSD}/LOG/LOG.$(basename $0).$(date +%Y%m%d).$(date +%H%M%S).$$
tmp=/tmp/tmp_$1
LANG=ja_JP.UTF-8
#PATH=/home/:/home/UTL:/home/TOOL/open-usp-tukubai-2014061402/COMMANDS:$PATH
CATEGORY=`cat $tmp-category`
FUNC=`cat $tmp-func`
DATAD=${SYSD}/DATA/${CATEGORY}/LISTS

########################################
#Check error
ERROR_CHECK(){
	[ $(plus ${PIPESTATUS[@]}) -eq 0 ] && return
cat <<- FIN
	Context-type: text/html
	NG input
FIN
	cat $tmp-result
	exit 1
}

########################################
#ディレクトリを作成する
if [ -e ${SYSD}/DATA/${CATEGORY}  ]; then
    :
else
    mkdir ${SYSD}/DATA/${CATEGORY}
    cp -rp ${SYSD}/DATA/ORG_LV1-3/ ${SYSD}/DATA/${CATEGORY}/LISTS
    chmod -R 775 ${SYSD}/DATA/${CATEGORY} #オーナーと権限を再帰的に設定
    #chown -R root:apache ${SYSD}/DATA/NUMBERS/${CATEGORY}
    ERROR_CHECK
fi
if [ -e ${SYSD}/DATA/PARTS_LIST  ]; then
    :
else
    mkdir ${SYSD}/DATA/PARTS_LIST
    mkdir ${SYSD}/DATA/PARTS_LIST/LISTS
    chmod -R 770 ${SYSD}/DATA/PARTS_LIST #オーナーと権限を再帰的に設定
    ERROR_CHECK
fi

########################################
#カテゴリ番号の次のロットを追加する
LATEST_NUM=$(ls ${SYSD}/DATA/NUMBERS/${CATEGORY}/ORIGIN | sort -nr | head -n 1)
START=$((LATEST_NUM + 1))
END=$((START + 3))
SEQ_STATUS=`${SYSD}/CGI/NUMBER_SEQ $1 ${CATEGORY} ${START} ${END} `
[[ ${SEQ_STATUS} != 'SUCCESS' ]] && exit 0

########################################
#新規カテゴリ番号を確定する
NEW_NUM=`${SYSD}/CGI/NUMBERS $1 'PARTS_CATEGORY' `
[ ${NEW_NUM} = 'ERROR' ] && exit 0 || :

#######################################
#フォームの入力値を取得
VALUE1=$(nameread NEW_PARTS_CATEGORY_NAME $tmp-post)

########################################
#重複確認
cat ${DATAD}/LV3/*[^_d] | awk -v nm=${VALUE1} '$2==nm{print $1}' > $tmp-valid1
if [ -n "$(cat $tmp-valid1)" ] ; then
    echo 2222 > $tmp-ajax-html
    exit 0
fi

########################################
#日付を設定
CREATE_DATE=$(date +%Y%m%d%H%M%S)
UPDATE_DATE=$CREATE_DATE

########################################
#更新者の取得
CREATE_USER=$(cat ${SYSD}/SESSION/$(session_get 'sureshot_stuff_session_id'))
UPDATE_USER=${CREATE_USER}

########################################
#入力値を一時ファイル化
#parts_category_id	parts_category_name	create_date	update_date	create_user	update_user	del_flg
echo ${NEW_NUM} ${VALUE1} ${CREATE_DATE} ${UPDATE_DATE} ${CREATE_USER} ${UPDATE_USER} 0 > $tmp-parts-category

########################################
#データ格納
#LV1
#LV1:原始データとして、ファイル追加のみを行う
mv $tmp-parts-category ${DATAD}/LV1/${NEW_NUM}_parts_category_${CREATE_DATE}

#LV2
#削除フラグは除外-->dファイルとして扱う
cat ${DATAD}/LV1/${NEW_NUM}_parts_category_${CREATE_DATE} | awk '{$NF=""; print $0}' > ${DATAD}/LV2/${NEW_NUM}_parts_category_${CREATE_DATE}

#LV3
#LV2のコピー
cp -p ${DATAD}/LV2/${NEW_NUM}_parts_category_${CREATE_DATE} ${DATAD}/LV3/${NEW_NUM}_parts_category_${CREATE_DATE}

########################################
#パーツ格納用カテゴリDirを作成
cp -irp ${SYSD}/DATA/ORG_LV1-3/ ${SYSD}/DATA/PARTS_LIST/LISTS/${NEW_NUM}

########################################
#Get records
cat ${SYSD}/DATA/${CATEGORY}/LISTS/LV3/*[^_d]       |
LANG=C sort -nk1,1                                  |
juni                                                > $tmp-records
# 1;カテゴリ番号 2;カテゴリ名
mojihame -lRECORDS ${SYSD}/APPLI/${CATEGORY}/LISTS/HTML/RECORDS.HTML $tmp-records > $tmp-table-records

########################################
# 改行文字を「\\n」という3文字の文字列に置換
TABLE_RECORDS=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-table-records`

########################################
#tableにrecordsを嵌め込む
cat ${SYSD}/APPLI/${CATEGORY}/LISTS/HTML/TABLE.HTML           > $tmp-table
sed -e "s|###TABLE_RECORDS###|${TABLE_RECORDS}|g" $tmp-table  > $tmp-ajax-html

########################################
#ending
echo "OK"
exit 0
