#!/bin/bash -evx
#

########################################
#	PARTS_LIST EDIT COMPLETE.CGI
#
#   引数
#       $1:プロセスID
#
#	Written by hiramatsu


########################################
#基本設定
SYSD=/home/sureshotsystem
#exec 2> ${SYSD}/LOG/LOG.$(basename $0).$(date +%Y%m%d).$(date +%H%M%S).$$
tmp=/tmp/tmp_$1
LANG=ja_JP.UTF-8
PATH=/home/:/home/UTL:/home/TOOL/open-usp-tukubai-2014061402/COMMANDS:$PATH
CATEGORY=`cat $tmp-category`
FUNC=`cat $tmp-func`
DATAD=${SYSD}/DATA/${CATEGORY}/LISTS

########################################
#Check error
ERROR_CHECK(){
	[ $(plus ${PIPESTATUS[@]}) -eq 0 ] && return
cat <<- FIN
	Context-type: text/html
	NG input
FIN
	cat $tmp-result
	exit 1
}

#######################################
#フォームの入力値を取得
PAGE_FILTER=$(nameread PARTS_CATEGORY_NAME_HIDDEN_PAGE $tmp-post)
NUM=$(nameread EDIT_PARTS_NO $tmp-post)
VALUE1=$(nameread EDIT_PARTS_CATEGORY_NAME $tmp-post)
VALUE2=$(nameread EDIT_PARTS_NAME $tmp-post)
VALUE3=$(nameread EDIT_PARTS_PRICE $tmp-post)

########################################
#重複確認
cat ${DATAD}/LV3/* | awk -v nm=${VALUE2} '$3==nm{print $1}' > $tmp-valid1
if [ -n "$(cat $tmp-valid1)" ] ; then
    echo 2222 > $tmp-ajax-html
    exit 0
fi

########################################
#既存データから作成日時取得、現在日時を更新日時とする
ls ${DATAD}/LV1/${NUM}_parts_* | cut -d'_' -f4 | sort -nk1,1 | head -n 1 > $tmp-create
CREATE_DATE=$(cat $tmp-create)
UPDATE_DATE=$(date +%Y%m%d%H%M%S)

########################################
#該当のデータ操作をロック
LOCK=`${SYSD}/CGI/LOCK/LOCK $1 'PARTS_LIST' ${NUM}`
LOCK_STATUS=$(echo $LOCK | cut -d'.' -f4)
[ ${LOCK_STATUS} != 'LOCKED' ] && exit 0 || :

########################################
#入力値を一時ファイル化
#1.パーツ番号 2.パーツカテゴリ名 3.パーツ名 4.価格 5.作成日時 6.更新日時 7.削除フラグ
echo ${NUM}" "${VALUE1}" "${VALUE2}" "${VALUE3}" "${CREATE_DATE}" "${UPDATE_DATE}" "0 > $tmp-parts

########################################
#データ格納
#LV1:原始データとして、ファイル追加のみを行う
$(mv $tmp-parts ${DATAD}/LV1/${NUM}_parts_${UPDATE_DATE})

#LV2:変更されたデータとファイルを入れ替える
cp -ip ${DATAD}/LV1/${NUM}_parts_${UPDATE_DATE} ${DATAD}/LV2/${NUM}_parts_${UPDATE_DATE}
ls ${DATAD}/LV2/${NUM}_* | sort -nk1 | head -n 1 > $tmp-delete
rm -f $(cat $tmp-delete)

#LV3:LV2のコピー
cp -ip ${DATAD}/LV2/${NUM}_parts_${UPDATE_DATE} ${DATAD}/LV3/${NUM}_parts_${UPDATE_DATE}
ls ${DATAD}/LV3/${NUM}_* | sort -nk1 | head -n 1 > $tmp-delete
rm -f $(cat $tmp-delete)

########################################
#データ操作ロックを解除
UNLOCK_STATUS=`${SYSD}/CGI/LOCK/UNLOCK $1 'PARTS_LIST' ${NUM}`
[ ${UNLOCK_STATUS} != 'UNLOCK'] && exit 0 || :

########################################
#パーツカテゴリを取得
cat ${SYSD}/DATA/PARTS_CATEGORY/LISTS/LV3/*[^_d]    |
LANG=C sort -nk1,1                                  > $tmp-category

########################################
#Page絞り込み用のパーツカテゴリ
# 1;カテゴリ番号 2;カテゴリ名
mojihame -lRECORDS ${SYSD}/APPLI/${CATEGORY}/LISTS/HTML/CATEGORY_PAGE.HTML $tmp-category > $tmp-parts-category-page

########################################
#登録済パーツ用のパーツカテゴリ
# 1;カテゴリ番号 2;カテゴリ名
mojihame -lRECORDS ${SYSD}/APPLI/${CATEGORY}/LISTS/HTML/CATEGORY_LIST.HTML $tmp-category > $tmp-parts-category-list

########################################
#新規登録パーツ用のパーツカテゴリ
# 1;カテゴリ番号 2;カテゴリ名
mojihame -lRECORDS ${SYSD}/APPLI/${CATEGORY}/LISTS/HTML/CATEGORY_NEW.HTML $tmp-category > $tmp-parts-category-new

########################################
# 改行文字を「\\n」という3文字の文字列に置換
PARTS_CATEGORY_PAGE=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-parts-category-page`
PARTS_CATEGORY_LIST=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-parts-category-list`
PARTS_CATEGORY_NEW=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-parts-category-new`

########################################
#パーツリストを取得
if [ -n "${PAGE_FILTER}" -a "${PAGE_FILTER}" != 'ALL' ] ; then
    cat ${DATAD}/LV3/*[^_d]                 |
    LANG=C sort -nk1,1                      |
    awk -v c=${PAGE_FILTER} '$2==c{print}'  |
    juni                                    > $tmp-records
else
    cat ${DATAD}/LV3/*[^_d]                 |
    LANG=C sort -nk1,1                      |
    juni                                    > $tmp-records
fi
# 1;カテゴリ番号 2;カテゴリ名
mojihame -lRECORDS ${SYSD}/APPLI/${CATEGORY}/LISTS/HTML/RECORDS.HTML $tmp-records > $tmp-table-records

########################################
#登録済レコードにパーツカテゴリリストを嵌め込む
cat $tmp-table-records                                      |
sed -re "s|###PARTS_CATEGORY###|${PARTS_CATEGORY_LIST}|g"   > $tmp-table

########################################
# 改行文字を「\\n」という3文字の文字列に置換
TABLE_RECORDS=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-table`

########################################
#tableにrecordsを嵌め込む
cat ${SYSD}/APPLI/${CATEGORY}/LISTS/HTML/TABLE.HTML     |
sed -e "s|###PARTS_CATEGORY###|${PARTS_CATEGORY_NEW}|g"     |
sed -e "s|###TABLE_RECORDS###|${TABLE_RECORDS}|g"       > $tmp-ajax-html

########################################
#ending
echo "OK"
exit 0
