#!/bin/bash -evx
#

########################################
#	PARTS_LIST SEARCH INPUT.CGI
#
#   引数
#       $1:プロセスID
#
#	Written by hiramatsu


########################################
#基本設定
SYSD=/home/sureshotsystem
#exec 2> ${SYSD}/LOG/LOG.$(basename $0).$(date +%Y%m%d).$(date +%H%M%S).$$
tmp=/tmp/tmp_$1
LANG=ja_JP.UTF-8
#PATH=/home/:/home/UTL:/home/TOOL/open-usp-tukubai-2014061402/COMMANDS:$PATH
CATEGORY=`cat $tmp-category`
FUNC=`cat $tmp-func`
DATAD=${SYSD}/DATA/${CATEGORY}/LISTS

########################################
#Check error
ERROR_CHECK(){
	[ $(plus ${PIPESTATUS[@]}) -eq 0 ] && return
cat <<- FIN
	Context-type: text/html
	NG input
FIN
	cat $tmp-result
	exit 1
}

#######################################
#フォームの入力値を取得
VALUE1=$(nameread PARTS_CATEGORY_NO $tmp-post)

########################################
#パーツカテゴリを取得
cat ${SYSD}/DATA/PARTS_LIST/LISTS/${VALUE1}/LV3/*[^_d]  |
LANG=C sort -nk1,1                                      > $tmp-parts

########################################
#Parts
# 部品番号、カテゴリ番号、カテゴリ名、部品名(EN)、部品名(JP)、単価、UD、CD
mojihame -lRECORDS ${SYSD}/APPLI/${CATEGORY}/${FUNC}/HTML/DROPDOWN_LIST.HTML $tmp-parts > $tmp-ajax-html

########################################
# 改行文字を「\\n」という3文字の文字に置換
#PARTS=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-parts-html`

########################################
#ending
echo "OK"
exit 0
