#!/bin/bash -evx
#

########################################
#	APPRAISAL/NEW COMPLETE.CGI
#
#   引数
#       $1:プロセスID
#
#	Written by hiramatsu


########################################
#基本設定
SYSD=$(cd $(dirname $0) && pwd | awk '{print substr($0, 0, index($0, "sureshotsystem")+13)}')
#exec 2> ${SYSD}/LOG/LOG.$(basename $0).$(date +%Y%m%d).$(date +%H%M%S).$$
tmp=/tmp/tmp_$1
LANG=ja_JP.UTF-8
#PATH=/home/:/home/UTL:/home/TOOL/open-usp-tukubai-2014061402/COMMANDS:$PATH
CATEGORY=`cat $tmp-category`
FUNC=`cat $tmp-func`
DATAD=${SYSD}/DATA/${CATEGORY}/LISTS

########################################
#Check error
ERROR_CHECK(){
	[ $(plus ${PIPESTATUS[@]}) -eq 0 ] && return
cat <<- FIN
	Context-type: text/html
	NG input
FIN
	cat $tmp-result
	exit 1
}

########################################
#パーツ番号の次のロットを追加する
LATEST_NUM=$(ls ${SYSD}/DATA/NUMBERS/${CATEGORY}/ORIGIN | sort -nr | head -n 1)
START=$((LATEST_NUM + 1))
END=$((START + 1))
SEQ_STATUS=`${SYSD}/CGI/NUMBER_SEQ $1 ${CATEGORY} ${START} ${END} `
[[ ${SEQ_STATUS} != 'SUCCESS' ]] && exit 0

########################################
#新規パーツ番号を確定する
NEW_NUM=`${SYSD}/CGI/NUMBERS $1 'APPRAISAL' `
[ ${NEW_NUM} = 'ERROR' ] && exit 0 || :

#######################################
#フォーム入力値を取得
TEMP_NO=$(nameread TEMP_NO $tmp-post)

########################################
#仮登録Dir
TEMPD=${SYSD}/TMP/$(cat ${SYSD}/SESSION/$(session_get 'sureshot_stuff_session_id'))/APPRAISAL/${TEMP_NO}

########################################
#ディレクトリを作成する
if [ -e "${SYSD}/DATA/${CATEGORY}"  ]; then
    :
else
    mkdir ${SYSD}/DATA/${CATEGORY}
    cp -rp ${SYSD}/DATA/ORG_LV1-3 ${SYSD}/DATA/${CATEGORY}/LISTS
    chmod -R 770 ${SYSD}/DATA/${CATEGORY}
    ERROR_CHECK
fi

########################################
#日付を設定
CREATE_DATE=$(date +%Y%m%d%H%M%S)
UPDATE_DATE=$CREATE_DATE

#######################################
#仮登録を取得
#顧客
cat ${TEMPD}/customer   | awk -v id=${NEW_NUM} -v tmp=${TEMP_NO} -v cdt=${CREATE_DATE} -v udt=${UPDATE_DATE} '{print id, tmp, $0, cdt, udt}' > $tmp-customer
#作業
cat ${TEMPD}/operation  | awk -v id=${NEW_NUM} -v tmp=${TEMP_NO} -v cdt=${CREATE_DATE} -v udt=${UPDATE_DATE} '{print id, tmp, $0, cdt, udt}' > $tmp-operation
#部品#
cat ${TEMPD}/parts      | awk -v id=${NEW_NUM} -v tmp=${TEMP_NO} -v cdt=${CREATE_DATE} -v udt=${UPDATE_DATE} '{print id, tmp, $0, cdt, udt}' > $tmp-parts

########################################
#データ格納
#LV1
mv $tmp-customer  ${DATAD}/LV1/${NEW_NUM}_appraisal_customer_${CREATE_DATE}
mv $tmp-operation ${DATAD}/LV1/${NEW_NUM}_appraisal_operation_${CREATE_DATE}
mv $tmp-parts     ${DATAD}/LV1/${NEW_NUM}_appraisal_parts_${CREATE_DATE}
#LV2
cat ${DATAD}/LV1/${NEW_NUM}_appraisal_customer_${CREATE_DATE} > ${DATAD}/LV2/${NEW_NUM}_appraisal_customer_${CREATE_DATE}
cat ${DATAD}/LV1/${NEW_NUM}_appraisal_operation_${CREATE_DATE} > ${DATAD}/LV2/${NEW_NUM}_appraisal_operation_${CREATE_DATE}
cat ${DATAD}/LV1/${NEW_NUM}_appraisal_parts_${CREATE_DATE} > ${DATAD}/LV2/${NEW_NUM}_appraisal_parts_${CREATE_DATE}
#LV3
cat ${DATAD}/LV2/${NEW_NUM}_appraisal_customer_${CREATE_DATE} > ${DATAD}/LV3/${NEW_NUM}_appraisal_customer_${CREATE_DATE}
cat ${DATAD}/LV2/${NEW_NUM}_appraisal_operation_${CREATE_DATE} > ${DATAD}/LV3/${NEW_NUM}_appraisal_operation_${CREATE_DATE}
cat ${DATAD}/LV2/${NEW_NUM}_appraisal_parts_${CREATE_DATE} > ${DATAD}/LV3/${NEW_NUM}_appraisal_parts_${CREATE_DATE}

#######################################
#仮登録セットリストを削除
rm -rf ${TEMPD}

########################################
#ending
echo "OK"
exit 0
