#!/bin/bash -evx
#

########################################
#	CUSTOMER EDIT COMPLETE.CGI
#
#   引数
#       $1:プロセスID
#
#	Written by hiramatsu


########################################
#基本設定
SYSD=$(cd $(dirname $0) && pwd | awk '{print substr($0, 0, index($0, "sureshotsystem")+13)}')
#exec 2> ${SYSD}/LOG/LOG.$(basename $0).$(date +%Y%m%d).$(date +%H%M%S).$$
tmp=/tmp/tmp_$1
LANG=ja_JP.UTF-8
#PATH=/home/:/home/UTL:/home/TOOL/open-usp-tukubai-2014061402/COMMANDS:$PATH
CATEGORY=`cat $tmp-category`
FUNC=`cat $tmp-func`
DATAD=${SYSD}/DATA/${CATEGORY}/LISTS

########################################
#Check error
ERROR_CHECK(){
	[ $(plus ${PIPESTATUS[@]}) -eq 0 ] && return
cat <<- FIN
	Context-type: text/html
	NG input
FIN
	cat $tmp-result
	exit 1
}

#######################################
#Get Form Data
ID=$(nameread CUSTOMER_ID $tmp-post)
VALUE1=$(nameread FIRST_NAME $tmp-post)
VALUE2=$(nameread GIVEN_NAME $tmp-post)
VALUE3=$(nameread EMAIL $tmp-post)
PW=$(nameread PASSWORD $tmp-post)
#VALUE5=$(nameread ADMIN_FLAG $tmp-post)
VALUE5=0
VALUE6=$(nameread PHONE $tmp-post)

######################################
#INPUT表示時点で作成した暗号化スタッフ番号を取得し、整合性の確認を行う
#暗号化の一時ファイルは削除
#顧客番号の整合性が取れない場合、CONFIRM画面に戻すが、実質更新は出来ない
CUSTOMER_NUM=$(cat ${SYSD}/TMP/CUSTOMER/${ID})
rm -f ${SYSD}/TMP/CUSTOMER/${ID}
if [ z ${CUSTOMER_NUM} ]; then
    cat ${SYSD}/APPLI/${CATEGORY}/${FUNC}/HTML/CONFIRM.HTML     |
    sed -e "s/###CUSTOMER_ID_NOT_MATCH###/データ不整合により更新出来ませんでした。/"   |
    sed -e "s/###FIRST_NAME_LABEL###/${VALUE1}/"                |
    sed -e "s/###GIVEN_NAME_LABEL###/${VALUE2}/"                |
    sed -e "s/###EMAIL_LABEL###/${VALUE3}/"                     |
    sed -e "s/###PHONE_LABEL###/${VALUE6}/"                     |
    sed -e "s/###PASSWORD_LABEL###/********/"                   > $tmp-html
    exit 0
fi

########################################
#該当のCUSTOMERのデータ操作をロック
LOCK=`${SYSD}/CGI/LOCK/LOCK $1 'CUSTOMER' ${CUSTOMER_NUM}`
LOCK_STATUS=$(echo $LOCK | cut -d'.' -f4)
[ ${LOCK_STATUS} != 'LOCKED' ] && exit 0 || :

########################################
#パスワードの値が"NOT_CHANGE"のままならば、変更が無いので、既存データを取得
#[[ "${PW}" = 'NOT_CHANGE' ]] && PW=$(cat ${DATAD}/LV3/* | awk -v id=$CUSTOMER_NUM '$1==id{print $4}')
[[ "${PW}" = 'NOT_CHANGE' ]] && PW=$(cat ${DATAD}/LV3/${CUSTOMER_NUM}_customer_* | awk '{print $4}')

########################################
#既存データから作成日時取得、現在日時を更新日時とする
ls ${DATAD}/LV1/${CUSTOMER_NUM}_customer_* | cut -d'_' -f3 | sort -nk1,1 | head -n 1 > $tmp-create
CREATE_DATE=$(cat $tmp-create)
UPDATE_DATE=$(date +%Y%m%d%H%M%S)

########################################
#ユーザーデータ用に一時ファイルに書き出し
#1.顧客番号 2.姓 3.名 4.EMAIL 5.Phone 6.作成日時 7.更新日時 8.ADMINフラグ 9.削除フラグ
echo ${CUSTOMER_NUM}" "${VALUE1}" "${VALUE2}" "${VALUE3}" "${VALUE6}" "${CREATE_DATE}" "${UPDATE_DATE}" "${VALUE5}" "0 > $tmp-customer

########################################
#データの格納
#LV1:原始データとして、ファイル追加のみを行う
$(mv $tmp-customer ${DATAD}/LV1/${CUSTOMER_NUM}_customer_${UPDATE_DATE})

#LV2:変更されたデータとファイルを入れ替える
cp -ip ${DATAD}/LV1/${CUSTOMER_NUM}_customer_${UPDATE_DATE} ${DATAD}/LV2/${CUSTOMER_NUM}_customer_${UPDATE_DATE}
ls ${USERSD}/LV2/${CUSTOMER_NUM}* | sort -nk1 | head -n 1 > $tmp-delete
rm -f $(cat $tmp-delete)

#LV3:リンク用のURLを追加,変更されたデータとファイルを入れ替える
cat ${DATAD}/LV1/${CUSTOMER_NUM}_customer_${UPDATE_DATE} |
awk '{print sprintf("%d %s %s %s %s %s %s %d %d /APP/CUSTOMER/LISTS/SHOW/?id=%d /APP/CUSTOMER/EDIT/INPUT/?id=%d /APP/CUSTOMER/DELETE/CONFIRM/?id=%d",$1,$2,$3,$4,$5,$6,$7,$8,$9,$1,$1,$1)}'  > ${DATAD}/LV3/${CUSTOMER_NUM}_customer_${UPDATE_DATE}
ls ${DATAD}/LV3/${CUSTOMER_NUM}* | sort -nk1 | head -n 1 > $tmp-delete
rm -f $(cat $tmp-delete)

########################################
#CUSTOMERのデータ操作ロックを解除
UNLOCK_STATUS=`${SYSD}/CGI/LOCK/UNLOCK $1 ${CATEGORY} ${CUSTOMER_NUM}`
[ ${UNLOCK_STATUS} != 'UNLOCK'] && exit 0 || :

########################################
#HTMLの設定
ACTION=`cat $tmp-action`
cat ${SYSD}/APPLI/${CATEGORY}/${FUNC}/HTML/${ACTION}.HTML   |
sed -e "s/###FIRST_NAME_LABEL###/${VALUE1}/"                |
sed -e "s/###GIVEN_NAME_LABEL###/${VALUE2}/"                |
sed -e "s/###PHONE_LABEL###/${VALUE6}/"                     |
sed -e "s/###EMAIL_LABEL###/${VALUE3}/"                     > $tmp-html

#########################################
#page name
echo "Customer edit" > $tmp-pagename

###############################################################################
#ending
echo "OK"
exit 0
