#!/bin/bash -evx
#

########################################
#   ASSESSMENT/NEW/PARTS/COMPLETE.CGI
#
#   引数
#       $1:プロセスID
#
#	Written by hiramatsu


########################################
#基本設定
SYSD=$(cd $(dirname $0) && pwd | awk '{print substr($0, 0, index($0, "sureshotsystem")+13)}')
#exec 2> ${SYSD}/LOG/LOG.$(basename $0).$(date +%Y%m%d).$(date +%H%M%S).$$
tmp=/tmp/tmp_$1
LANG=ja_JP.UTF-8
#PATH=/home/:/home/UTL:/home/TOOL/open-usp-tukubai-2014061402/COMMANDS:$PATH
CATEGORY=`cat $tmp-category`
FUNC=`cat $tmp-func`

########################################
#Check error
ERROR_CHECK(){
	[ $(plus ${PIPESTATUS[@]}) -eq 0 ] && return
cat <<- FIN
	Context-type: text/html
	NG input
FIN
	cat $tmp-result
	exit 1
}

########################################
#パーツカテゴリ更新中は、処理をさせない
#ls ${SYSD}/LOCK/PARTS_CATEGORY/* > $tmp-checker 2> /dev/null
#if [ -n cat $tmp-checker ] ; then
#    echo "333" > $tmp-ajax-html
#    exit 0
#fi

#######################################
#フォーム入力値を取得
ACTION=$(nameread ACTION $tmp-post)
ROW=$(nameread ROW $tmp-post)
TEMP_NO=$(nameread TEMP_NO $tmp-post)
CATE_NM=$(nameread CATEGORY_NM $tmp-post)   #パーツカテゴリ名
CATE_NO=$(nameread CATEGORY_NO $tmp-post)   #パーツカテゴリ番号
PARTS_NM=$(nameread PARTS_NM $tmp-post)     #パーツ名
PARTS_NO=$(nameread PARTS_NO $tmp-post)     #パーツ番号
PRICE=$(nameread PARTS_PRICE $tmp-post)     #プライス
QTY=$(nameread PARTS_QTY $tmp-post)         #数量

########################################
#仮番号ディレクトリ
TEMPD=${SYSD}/TMP/ASSESSMENT/${TEMP_NO}

########################################
#ACTIONで振り分け
case ${ACTION} in
ADD)    #追加
  #1:カテゴリ番号、2:カテゴリ名、3:部品番号、4:部品名、5:価格、6:数量
  echo ${CATE_NO}" "${CATE_NM}" "${PARTS_NO}" "${PARTS_NM}" "${PRICE}" "${QTY}  >> ${TEMPD}/parts
  #空行を削除
  cat ${TEMPD}/parts | awk /./ > $tmp-parts
  ;;
EDIT)   #変更
  cat ${TEMPD}/parts | 
  awk \
      -v row=${ROW} \
      -v cate_no=${CATE_NO} -v cate_nm=${CATE_NM} \
      -v parts_no=${PARTS_NO} -v parts_nm=${PARTS_NM} \
      -v price=${PRICE} \
      -v qty=${QTY} \
      'NR!=row{print} \
      NR==row{print(cate_no, cate_nm, parts_no, parts_nm, price, qty)}' \
      > $tmp-parts
  ;;
DELETE) #削除
  cat ${TEMPD}/parts | awk -v d=${ROW} 'NR!=d{print}' > $tmp-parts
  ;;
esac

########################################
cat $tmp-parts > ${TEMPD}/parts

########################################
#パーツカテゴリを取得
cat ${SYSD}/DATA/PARTS_CATEGORY/LISTS/LV3/*[^_d]    |
LANG=C sort -nk1,1                                  > $tmp-category

########################################
#登録済パーツ用のパーツカテゴリ
# 1;カテゴリ番号 2;カテゴリ名
mojihame -lRECORDS ${SYSD}/APPLI/ASSESSMENT/NEW/HTML/PARTS/CATEGORY_LIST.HTML $tmp-category > $tmp-parts-category-list

#######################################
# 改行文字を「\\n」という3文字の文字列に置換
CATEGORY_LIST=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-parts-category-list`

########################################
#パーツリストを取得
cat ${TEMPD}/parts |
juni               > $tmp-records
#1:順位、2:カテゴリ番号、3:カテゴリ名、4:部品番号、5:部品名、6:価格、7:数量
mojihame -lRECORDS ${SYSD}/APPLI/ASSESSMENT/NEW/HTML/PARTS/RECORDS.HTML $tmp-records > $tmp-table-records

########################################
#パーツリストにパーツカテゴリリストを嵌め込む
cat $tmp-table-records                         |
sed -e "s|###CATEGORY###|${CATEGORY_LIST}|g"   > $tmp-table-records2

########################################
# 改行文字を「\\n」という3文字の文字列に置換
TABLE_RECORDS=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-table-records2`

echo ${TABLE_RECORDS} > /tmp/vvvvvv

########################################
#新規登録パーツ用のパーツカテゴリ
# 1;カテゴリ番号 2;カテゴリ名
mojihame -lRECORDS ${SYSD}/APPLI/ASSESSMENT/NEW/HTML/PARTS/CATEGORY_NEW.HTML $tmp-category > $tmp-parts-category-new

########################################
# 改行文字を「\\n」という3文字の文字列に置換
CATEGORY_NEW=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-parts-category-new`

########################################
#tableにrecordsを嵌め込む
cat ${SYSD}/APPLI/ASSESSMENT/NEW/HTML/PARTS/TABLE.HTML    |
sed -e "s|###CATEGORY###|${CATEGORY_NEW}|g"               |
sed -e "s|###TABLE_RECORDS###|${TABLE_RECORDS}|g"         > $tmp-ajax-html

########################################
#ending
echo "OK"
exit 0
