#!/bin/bash -vx
#

########################################
#	CUSTOMER SHOW.CGI
#
#   $1:必須 $$
#
#	Written by hiramatsu


########################################
#基本設定
SYSD=/home/sureshotsystem
#exec 2> $SYSD/LOG/LOG.$(basename $0).$(date +%Y%m%d).$(date +%H%M%S).$$
tmp=/tmp/tmp_$1
LANG=ja_JP.UTF-8
PATH=/home/:/home/UTL:/home/TOOL/open-usp-tukubai-2014061402/COMMANDS:$PATH
CATEGORY=`cat $tmp-category`
FUNC=`cat $tmp-func`
ACTION=`cat $tmp-action`

#######################################
#Check error
ERROR_CHECK(){
	[ $(plus ${PIPESTATUS[@]}) -eq 0 ] && return
cat <<- FIN
	Context-type: text/html
	NG input
FIN
	cat $tmp-result
	exit 1
}

########################################
#最大表示レコード数
cat ${SYSD}/SYS/${CATEGORY}/${FUNC}/VIEW_MAX_RECORDS | 
awk '{print $2}' > $tmp-max-records
VIEW_MAX_RECORDS=$( cat $tmp-max-records )

########################################
#最大表示ページ数
cat ${SYSD}/SYS/${CATEGORY}/${FUNC}/VIEW_MAX_PAGES | 
awk '{print $2}' > $tmp-max-pages
VIEW_MAX_PAGES=$( cat $tmp-max-pages )

########################################
#Get querystring
QRY_PAGE=$( cat $tmp-get | sed -e 's/^.*\(page\=[0-9]*\).*$/\1/' | sed -e 's/page\=//')
QRY_DISP=$( cat $tmp-get | sed -e 's/^.*\(disp\=[0-9]*\).*$/\1/' | sed -e 's/disp\=//')

########################################
#Set record start & end
if [ -z $(echo ${QRY_PAGE}) ]; then
    SHOW_PAGE=1
    START=1
    END=${VIEW_MAX_RECORDS}
else
    SHOW_PAGE=${QRY_PAGE}
    END=$(expr ${QRY_PAGE} \* ${VIEW_MAX_RECORDS} )
    START=$(expr ${END} - ${VIEW_MAX_RECORDS} + 1 )
fi

########################################
#Get stuff records
cat ${SYSD}/DATA/${CATEGORY}/${FUNC}/LV3/*[^_d]     |
LANG=C sort -nk1,1                                  |
awk -v s=${START} -v e=${END} 'NR>=s&&NR<=e&&$9!=1' |
juni                                                > $tmp-records
# 1;顧客番号 2;姓 3:名 4:email, 5:Phone
mojihame -lRECORDS ${SYSD}/APPLI/${CATEGORY}/${FUNC}/HTML/${ACTION}.HTML $tmp-records > $tmp-template-html

########################################
#Set pager
RECORDS=$( ls ${SYSD}/DATA/${CATEGORY}/${FUNC}/LV3/*[^_d] | wc -l )
RESULT=`${SYSD}/CGI/PAGER $1 /APP/${CATEGORY}/${FUNC}/${ACTION} ${SHOW_PAGE} ${RECORDS} ${VIEW_MAX_RECORDS} ${VIEW_MAX_PAGES}`

########################################
#Making viweing body HTML filw path
sed -re "s|###PAGER###|$(cat $tmp-pager-html)|g" $tmp-template-html > $tmp-html

#########################################
#page name
echo "Customer lists" > $tmp-pagename

#########################################
##ending
echo "OK"
exit 0
