#!/bin/bash -vx
#

########################################
#	SHOW.CGI
#
#	Written by hiramatsu


########################################
#Set basic
SYSD=/home/sureshotsystem
#exec 2> $SYSD/LOG/LOG.$(basename $0).$(date +%Y%m%d).$(date +%H%M%S).$$
tmp=/tmp/tmp_$1
LANG=ja_JP.UTF-8
PATH=/home/:/home/UTL:/home/TOOL/open-usp-tukubai-2014061402/COMMANDS:$PATH
CATEGORY=`cat $tmp-category`
FUNC=`cat $tmp-func`
ACTION=`cat $tmp-action`

########################################
#Check error
ERROR_CHECK(){
	[ $(plus ${PIPESTATUS[@]}) -eq 0 ] && return
cat <<- FIN
	Context-type: text/html
	NG input
FIN
	cat $tmp-result
	exit 1
}

########################################
#Check Login Session
#session=`${SYSD}/CGI/LOGIN_SESSION`
#echo $session > $tmp-session


########################################
#Set start & end
if [ -z $(cat $tmp-get) ]; then
    start=1
    end=20
else
    if [ -n $(cat $tmp-get | grep "id\=") ]; then
        query_string=$(cat $tmp-get | sed -e "s/id\=//")
        arr=( `echo $query_string | tr -s '-' ' '`)
        start=${arr[0]}
        end=${arr[0]}
    fi
fi

########################################
#Get employee records
cat ${SYSD}/DATA/${CATEGORY}/USERS/LV3/EMPLOYEES     |
LANG=C sort -nk1,1                           |
awk -v s=$start -v e=$end 'NR>=s&&NR<=e' |
juni                                        > $tmp-records
# 1;社員番号 2;姓 3:名 4:email

mojihame -lRECORDS ${SYSD}/APPLI/${CATEGORY}/${FUNC}/HTML/${ACTION}.HTML $tmp-records > $tmp-html

########################################
#Making viweing body HTML filw path
cat $tmp-html

#########################################
##ending
echo "OK"
exit 0

