#!/bin/bash -vx
#

########################################
#	SHOW.CGI
#
#	Written by hiramatsu


########################################
#Set basic
SYSD=/home/sureshotsystem
#exec 2> $SYSD/LOG/LOG.$(basename $0).$(date +%Y%m%d).$(date +%H%M%S).$$
tmp=/tmp/tmp_$1
LANG=ja_JP.UTF-8
PATH=/home/:/home/UTL:/home/TOOL/open-usp-tukubai-2014061402/COMMANDS:$PATH
CATEGORY=`cat $tmp-category`
FUNC=`cat $tmp-func`
ACTION=`cat $tmp-action`
PAGER_VIEW_REC=20
PAGER_VIEW_PAGES=5

########################################
#Check error
ERROR_CHECK(){
	[ $(plus ${PIPESTATUS[@]}) -eq 0 ] && return
cat <<- FIN
	Context-type: text/html
	NG input
FIN
	cat $tmp-result
	exit 1
}

########################################
#Get querystring
QRY_PAGE=$( cat $tmp-get | sed -e 's/^.*\(page\=[0-9]*\).*$/\1/' | sed -e 's/page\=//')
QRY_DISP=$( cat $tmp-get | sed -e 's/^.*\(disp\=[0-9]*\).*$/\1/' | sed -e 's/disp\=//')

########################################
#Set record start & end
if [ -z $(echo ${QRY_PAGE}) ]; then
    SHOW_PAGE=1
    START=1
    END=20
else
    SHOW_PAGE=${QRY_PAGE}
    END=$(expr ${QRY_PAGE} \* ${PAGER_VIEW_REC} )
    START=$(expr ${END} - ${PAGER_VIEW_REC} + 1 )
fi

########################################
#Get employee records
cat ${SYSD}/DATA/${CATEGORY}/USERS/LV3/EMPLOYEES    |
LANG=C sort -nk1,1                                  |
awk -v s=${START} -v e=${END} 'NR>=s&&NR<=e'        |
juni                                                > $tmp-records
# 1;社員番号 2;姓 3:名 4:email
mojihame -lRECORDS ${SYSD}/APPLI/${CATEGORY}/${FUNC}/HTML/${ACTION}.HTML $tmp-records > $tmp-template-html

########################################
#Set pager
RECORDS=$( cat ${SYSD}/DATA/${CATEGORY}/USERS/LV3/EMPLOYEES | wc -l )
RESULT=`${SYSD}/CGI/PAGER $1 /APP/EMPLOYEE/USERS/SHOW ${SHOW_PAGE} ${RECORDS}`

########################################
#Making viweing body HTML filw path
cat $tmp-html

#########################################
##ending
echo "OK"
exit 0

