#!/bin/bash -vx
#

########################################
#	CUSTOMER NEW INPUT.CGI
#
#   Arg
#       $1:$$
#
#	Written by hiramatsu


########################################
#基本設定
SYSD=/home/sureshotsystem
#exec 2> $SYSD/LOG/LOG.$(basename $0).$(date +%Y%m%d).$(date +%H%M%S).$$
tmp=/tmp/tmp_$1
LANG=ja_JP.UTF-8
PATH=/home/:/home/UTL:/home/TOOL/open-usp-tukubai-2014061402/COMMANDS:$PATH
CATEGORY=`cat $tmp-category`
FUNC=`cat $tmp-func`

########################################
#Check error
ERROR_CHECK(){
	[ $(plus ${PIPESTATUS[@]}) -eq 0 ] && return
cat <<- FIN
	Context-type: text/html
	NG input
FIN
	cat $tmp-result
	exit 1
}

########################################
#Making viweing body HTML filw path
ACTION=`cat $tmp-action`
cat ${SYSD}/APPLI/${CATEGORY}/${FUNC}/HTML/${ACTION}.HTML   |
sed -e "s/###FAMILY_NAME_ERR###/hidden/"            |
sed -e "s/###GIVEN_NAME_ERR###/hidden/"             |
sed -e "s/###EMAIL_ERR###/hidden/"                  |
sed -e "s/###PASSWORD_ERR###/hidden/"               |
sed -e "s/###PASSWORD_CONFIRMATION_ERR###/hidden/"  |
sed -e "s/###EMAIL_DUPLECATED###/hidden/"           |
sed -e "s/###FAMILY_NAME_VALUE###//"                |
sed -e "s/###GIVEN_NAME_VALUE###//"                 |
sed -e "s/###EMAIL_VALUE###//"                      |
sed -e "s/###PASSWORD_VALUE###//"                   |
sed -e "s/###PASSWORD_CONFIRMATION_VALUE###//"      > $tmp-html

#########################################
#page name
echo "Assessment entry" > $tmp-pagename

#########################################
##ending
echo "OK"
exit 0

