#!/bin/bash -evx
#

########################################
#	SET_LIST/NEW/PARTS/COMPLETE.CGI
#
#   引数
#       $1:プロセスID
#
#	Written by hiramatsu


########################################
#基本設定
SYSD=$(cd $(dirname $0) && pwd | awk '{print substr($0, 0, index($0, "sureshotsystem")+13)}')
#exec 2> ${SYSD}/LOG/LOG.$(basename $0).$(date +%Y%m%d).$(date +%H%M%S).$$
tmp=/tmp/tmp_$1
LANG=ja_JP.UTF-8
#PATH=/home/:/home/UTL:/home/TOOL/open-usp-tukubai-2014061402/COMMANDS:$PATH
CATEGORY=`cat $tmp-category`
FUNC=`cat $tmp-func`

########################################
#Check error
ERROR_CHECK(){
	[ $(plus ${PIPESTATUS[@]}) -eq 0 ] && return
cat <<- FIN
	Context-type: text/html
	NG input
FIN
	cat $tmp-result
	exit 1
}

########################################
#パーツカテゴリ更新中は、処理をさせない
#ls ${SYSD}/LOCK/PARTS_CATEGORY/* > $tmp-checker 2> /dev/null
#if [ -n cat $tmp-checker ] ; then
#    echo "333" > $tmp-ajax-html
#    exit 0
#fi

########################################
#仮登録ディレクトリ
SESSION=$(session_get 'sureshot_stuff_session_id') 
STUFF_ID=$(cat ${SYSD}/SESSION/${SESSION})
TEMPD=${SYSD}/TMP/${STUFF_ID}/SET_LIST

#######################################
#フォームの入力値を取得
cat $tmp-post
ACTION=$(nameread ACTION $tmp-post)
ROW=$(nameread ROW $tmp-post)
PARTS_CATEGORY_NO=$(nameread PARTS_CATEGORY_NO $tmp-post)
PARTS_CATEGORY_NM=$(nameread PARTS_CATEGORY_NM $tmp-post)
PARTS_NO=$(nameread PARTS_NO $tmp-post)
PARTS_NM=$(nameread PARTS_NM $tmp-post)
PARTS_PRICE=$(nameread PARTS_PRICE $tmp-post)
PARTS_QTY=$(nameread PARTS_QTY $tmp-post)

######################################t#
#ACTIONで振り分け
case ${ACTION} in
ADD)    #追加
  #重複確認
  cat ${TEMPD}/setlist_parts | awk -v pid=${PARTS_NO} '$3==pid {print}' > $tmp-valid1
  if [ -n "$(cat $tmp-valid1)" ] ; then
      echo 2222 > $tmp-ajax-html
      exit 0
  fi
  #1:カテゴリ番号、2:カテゴリ名、3:部品番号、4:部品名、5:価格、6:数量
  echo ${PARTS_CATEGORY_NO} ${PARTS_CATEGORY_NM} ${PARTS_NO} ${PARTS_NM} ${PARTS_PRICE} ${PARTS_QTY} >> ${TEMPD}/setlist_parts
  #空行を削除
  cat ${TEMPD}/setlist_parts | awk /./ > $tmp-set-list-parts
  ;;
EDIT)   #変更
  cat ${TEMPD}/setlist_parts | 
  awk \
      -v row=${ROW} \
      -v category_no=${PARTS_CATEGORY_NO} \
      -v category_nm=${PARTS_CATEGORY_NM} \
      -v parts_no=${PARTS_NO} \
      -v parts_nm=${PARTS_NM} \
      -v price=${PARTS_PRICE} \
      -v qty=${PARTS_QTY} \
      'NR!=row{print} \
      NR==row{print(category_no, category_nm, parts_no, parts_nm, price, qty)}' \
      > $tmp-set-list-parts
  ;;
DELETE) #削除
  cat ${TEMPD}/setlist_parts | awk -v d=${ROW} 'NR!=d{print}' > $tmp-set-list-parts
  ;;
esac

#######################################
#入力値を仮登録
#部品カテゴリ番号、部品カテゴリ名、部品番号、部品名、部品価格、部品数量
cat $tmp-set-list-parts > ${TEMPD}/setlist_parts

########################################
#部品カテゴリを取得
cat ${SYSD}/DATA/PARTS_CATEGORY/LISTS/LV3/*[^_d]    |
LANG=C sort -nk1,1                                  > $tmp-parts-category

########################################
#部品新規登録用の部品カテゴリ
# 1;カテゴリ番号 2;カテゴリ名
mojihame -lRECORDS ${SYSD}/APPLI/${CATEGORY}/${FUNC}/HTML/PARTS/PARTS_CATEGORY_NEW.HTML $tmp-parts-category > $tmp-parts-category-new

########################################
#カテゴリの改行文字を「\\n」という3文字の文字列に置換
CATEGORY_NEW=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-parts-category-new`

########################################
#部品レコード用の部品カテゴリ
# 1;カテゴリ番号 2;カテゴリ名
mojihame -lRECORDS ${SYSD}/APPLI/${CATEGORY}/${FUNC}/HTML/PARTS/PARTS_CATEGORY_LIST.HTML $tmp-parts-category > $tmp-parts-category-list

########################################
#部品カテゴリの改行文字を「\\n」という3文字の文字列に置換
CATEGORY_LIST=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-parts-category-list`

########################################
#仮登録の部品リストを取得
cat ${TEMPD}/setlist_parts          |
juni                                |                
LANG=C sort -nk1,1                  > $tmp-records
mojihame -lRECORDS ${SYSD}/APPLI/${CATEGORY}/NEW/HTML/PARTS/RECORDS.HTML $tmp-records > $tmp-table-records

########################################
#登録済レコードに部品カテゴリリストを嵌め込む
cat $tmp-table-records                         |
sed -e "s|###CATEGORY###|${CATEGORY_LIST}|g"   > $tmp-table

########################################
# 改行文字を「\\n」という3文字の文字列に置換
TABLE_RECORDS=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-table`

########################################
#tableにrecordsを嵌め込む
cat ${SYSD}/APPLI/${CATEGORY}/NEW/HTML/PARTS/TABLE.HTML     |
sed -e "s|###CATEGORY###|${CATEGORY_NEW}|g"                 |
sed -e "s|###TABLE_RECORDS###|${TABLE_RECORDS}|g"           > $tmp-ajax-html

########################################
#ending
echo "OK"
exit 0
