#!/bin/bash -vx
#

########################################
#	STUFF EDIT CONFIRM.CGI
#
#   引数
#       $1:必須 $$
#
#	Written by hiramatsu


########################################
#基本設定
SYSD=$(cd $(dirname $0) && pwd | awk '{print substr($0, 0, index($0, "sureshotsystem")+13)}')
#exec 2> $SYSD/LOG/LOG.$(basename $0).$(date +%Y%m%d).$(date +%H%M%S).$$
tmp=/tmp/tmp_$1
LANG=ja_JP.UTF-8
#PATH=/home/:/home/UTL:/usr/local/bin:/home/TOOL/open-usp-tukubai-2014061402/COMMANDS:$PATH
CATEGORY=`cat $tmp-category`
FUNC=`cat $tmp-func`

########################################
#Check error
ERROR_CHECK(){
	[ $(plus ${PIPESTATUS[@]}) -eq 0 ] && return
cat <<- FIN
	Context-type: text/html
	NG input
FIN
	cat $tmp-result
	exit 1
}

########################################
#暗号化された社員IDを取得(暗号化されフォームに埋め込まれた社員ID)
ENC_ID=$(nameread STUFF_ID $tmp-post | awk '{gsub(/^\_$/,"",$1);print}')

########################################
#フォーム値の設定
nameread FAMILY_NAME $tmp-post              | awk '{gsub(/^\_$/,"",$1);print}' > $tmp-value1
nameread GIVEN_NAME $tmp-post               | awk '{gsub(/^\_$/,"",$1);print}' > $tmp-value2
nameread EMAIL $tmp-post                    | awk '{gsub(/^\_$/,"",$1);print}' > $tmp-value3
nameread PASSWORD $tmp-post                 | awk '{gsub(/^\_$/,"",$1);print}' > $tmp-value4
nameread PASSWORD_CONFIRMATION $tmp-post    | awk '{gsub(/^\_$/,"",$1);print}' > $tmp-value5

########################################
#社員番号を復元
ID=$(cat ${SYSD}/TMP/$(cat ${SYSD}/SESSION/$(session_get 'sureshot_stuff_session_id'))/${CATEGORY}/${ENC_ID})

########################################
#バリデーション(必須入力確認)
#入力ありの場合、空ファイルが出力され、なしの場合、そのフィールド名が記載される
cat $tmp-post | awk '$2=="_" && $1=="FAMILY_NAME"{print $1}' > $tmp-need-VALID1
cat $tmp-post | awk '$2=="_" && $1=="GIVEN_NAME"{print $1}' > $tmp-need-VALID2
cat $tmp-post | awk '$2=="_" && $1=="EMAIL"{print $1}' > $tmp-need-VALID3
cat $tmp-post | awk '$2=="_" && $1=="PASSWORD"{print $1}' > $tmp-need-VALID4
cat $tmp-post | awk '$2=="_" && $1=="PASSWORD_CONFIRMATION"{print $1}' > $tmp-need-VALID5

########################################
#バリデーション(データ属性)
#FAMILY NAME length <=2 =>20
VALID1=$(cat $tmp-value1)
if [ "${VALID1}" -lt 2 ] || [ "${VALID1}" -gt 20 ] ; then
    echo "legth NG" > $tmp-attr-VALID1
fi
#GIVEN NAME length <=2 =>20
VALID2=$(cat $tmp-value2)
if [ "${VALID2}" -lt 2 ] || [ "${VALID2}" -gt 20 ] ; then
    echo "legth NG" > $tmp-attr-VALID2
fi
#EMAIL is
VALID3=$(cat $tmp-value3)
if [ -z "${VALID3}" ] ; then
    echo "NULL NG" > $tmp-attr-VALID3
fi
#PASSWORD length <=8 
VALID4=$(cat $tmp-value4)
if [ "${VALID4}" -lt 8 ] ; then
    echo "legth NG" > $tmp-attr-VALID4
fi
#PASSWORD CONFIRMATION =PASSWORD 
VALID5=$(cat $tmp-value5)
if [ "${VALID5}" != "${VALID4}" ] ; then
    echo "CONFIRMATION NG" > $tmp-attr-VALID5
fi

########################################
#バリデーション(EMAIL重複確認)
#1.社員番号 2.姓 3.名 4.EMAIL 5.TEL 6.作成日時 7.更新日時 8.削除フラグ
if [ -n "$(cat ${SYSD}/DATA/STUFF/USERS/LV3/* | awk -v i=${ENC_ID} -v e=${VALID3} '$1!=i&&$4==e{print $4}')" ] ; then
    echo "${VALID3} is duplicate" > $tmp-attr-VALID3
fi

########################################
#バリデーションエラー項目の確定
#FAMILY_NAME
if [ -n "$(cat $tmp-need-VALID1)$(cat $tmp-attr-VALID1)" ] ; then 
    VALID1_disp='show'
else
    VALID1_disp='hidden'
fi
#GIVEN_NAME
if [ -n "$(cat $tmp-need-VALID2)$(cat $tmp-attr-VALID2)" ] ; then
    VALID2_disp='show'
else
    VALID2_disp='hidden'
fi
#EMAIL
if [ -n "$(cat $tmp-need-VALID3)" ] ; then
    VALID31_disp='show'
else
    VALID31_disp='hidden'
fi
#EMAIL Duplicate
if [ -n "$(cat $tmp-attr-VALID6)" ] ; then
    VALID32_disp='show'
else
    VALID32_disp='hidden'
fi
#PASSWORD
if [ -n "$(cat $tmp-need-VALID4)$(cat $tmp-attr-VALID4)" ] ; then
    VALID4_disp='show'
else
    VALID4_disp='hidden'
fi
#PASSWORD CONFIRMATION
if [ -n "$(cat $tmp-need-VALID5)$(cat $tmp-attr-VALID5)" ] ; then
    VALID5_disp='show'
else
    VALID5_disp='hidden'
fi

########################################
#パスワードの暗号化
if [ "${VALID4}" = 'NOT_CHANGE' ]; then
    echo 'NOT_CHANGE' > $tmp-sha1
else
    echo $(sha1 $(cat $tmp-value4)) > $tmp-sha1
fi

########################################
#アクションの設定
#バリデーションエラー文言が1文字でもあればNG-->ActionをINPUTに設定
echo ${VALID1_disp}${VALID2_disp}${VALID31_disp}${VALID32_disp}${VALID4_disp}${VALID5_disp} | awk '{gsub(/hidden/,"",$1);print}' | awk '{print length($1)}' > $tmp-VALID-result
num=$(cat $tmp-VALID-result)
if [ $num -gt 0 ]; then
    ACTION=INPUT
else
    ACTION=CONFIRM
fi

########################################
#HTMLの設定
if [ $ACTION = 'INPUT' ] ; then
    #Validation NG
    cat ${SYSD}/APPLI/${CATEGORY}/${FUNC}/HTML/${ACTION}.HTML           |
    sed -e "s/###STUFF_ID###/${ENC_ID}/"                                |
    sed -e "s/###FAMILY_NAME_ERR###/${VALID1_disp}/"                    |
    sed -e "s/###GIVEN_NAME_ERR###/${VALID2_disp}/"                     |
    sed -e "s/###EMAIL_ERR###/${VALID31_disp}/"                         |
    sed -e "s/###EMAIL_DUPLECATED###/${VALID32_disp}/"                  |
    sed -e "s/###PASSWORD_ERR###/${VALID4_disp}/"                       |
    sed -e "s/###PASSWORD_CONFIRMATION_ERR###/${VALID4_disp}/"          |
    sed -e "s/###FAMILY_NAME_VALUE###/$(cat $tmp-value1)/"              |
    sed -e "s/###GIVEN_NAME_VALUE###/$(cat $tmp-value2)/"               |
    sed -e "s/###EMAIL_VALUE###/$(cat $tmp-value3)/"                    |
    sed -e "s/###PASSWORD_VALUE###/NOT_CHANGE/"                         |
    sed -e "s/###PASSWORD_CONFIRMATION_VALUE###/NOT_CHANGE/"            > $tmp-html
else
    #Validation OK
    cat ${SYSD}/APPLI/${CATEGORY}/${FUNC}/HTML/${ACTION}.HTML           |
    sed -e "s/###STUFF_ID###/${ENC_ID}/"                                |
    sed -e "s/###ID###/${ID}/"                                          |
    sed -e "s/###FAMILY_NAME_LABEL###/$(cat $tmp-value1)/"              |
    sed -e "s/###GIVEN_NAME_LABEL###/$(cat $tmp-value2)/"               |
    sed -e "s/###EMAIL_LABEL###/$(cat $tmp-value3)/"                    |
    sed -e "s/###PASSWORD_LABEL###/********/"                           |
    sed -e "s/###FAMILY_NAME_VALUE###/$(cat $tmp-value1)/"              |
    sed -e "s/###GIVEN_NAME_VALUE###/$(cat $tmp-value2)/"               |
    sed -e "s/###EMAIL_VALUE###/$(cat $tmp-value3)/"                    |
    sed -e "s/###PASSWORD_VALUE###/$(cat $tmp-sha1)/"                   > $tmp-html
fi

#########################################
#page name
if [ $ACTION = 'INPUT' ] ; then
    echo "Stuff edit input" > $tmp-pagename
else
    echo "Stuff edit confirm" > $tmp-pagename
fi

###############################################################################
#ending
echo "OK"
exit 0
