#!/bin/bash -vx
#

########################################
#	STUFF EDIT INPUT.CGI
#
#   引数
#       $1:必須 $$
#
#	Written by hiramatsu


########################################
#基本設定
SYSD=$(cd $(dirname $0) && pwd | awk '{print substr($0, 0, index($0, "sureshotsystem")+13)}')
#exec 2> $SYSD/LOG/LOG.$(basename $0).$(date +%Y%m%d).$(date +%H%M%S).$$
tmp=/tmp/tmp_$1
LANG=ja_JP.UTF-8
#PATH=/home/:/home/UTL:/home/TOOL/open-usp-tukubai-2014061402/COMMANDS:$PATH
CATEGORY=`cat $tmp-category`
FUNC=`cat $tmp-func`
USERSD=${SYSD}/DATA/${CATEGORY}/USERS

########################################
#Check error
ERROR_CHECK(){
	[ $(plus ${PIPESTATUS[@]}) -eq 0 ] && return
cat <<- FIN
	Context-type: text/html
	NG input
FIN
	cat $tmp-result
	exit 1
}

########################################
#更新するスタッフIDを取得 ※GETパラメータの順番は、action,idの順番が前提
EDIT_ID=$(cat $tmp-get | awk '{split($0,ary,"&"); print ary[2]}' | sed 's/id\=//')

########################################
#次ページ照合用にIDを暗号化
ENC_ID=$(sha1 $RANDOM$EDIT_ID)

########################################
#作業者IDを取得
USER=$(cat ${SYSD}/SESSION/$(session_get 'sureshot_stuff_session_id'))

########################################
#TMPディレクトリにある作業者ID内にSTUFFディレクトリを作成する
result=`${SYSD}/CGI/DATA/DFS_NEW $1 ${SYSD}/TMP/${USER}/STUFF`

########################################
#暗号化したスタッフIDを認証用としてTMP/*/STUFFに配置
echo $EDIT_ID > ${SYSD}/TMP/${USER}/STUFF/${ENC_ID}

########################################
#スタッフの最新データを取得
cat `ls -v ${USERSD}/LV2/${EDIT_ID}*` > $tmp-lv2

########################################
#Emailを復号化
cat ${SYSD}/DATA/STUFF/ACCOUNTS/$(cat $tmp-lv2 | sed -n 4p) | openssl enc -aes-128-cbc -d -base64 -pass pass:$(cat ${SYSD}/CGI/BIN/key) > $tmp-email-decode

########################################
#管理者権限を取得
[ "$(cat $tmp-lv2 | sed -n 8p)" = "1" ] && ADMIN_CHK="checked" || ADMIN_CHK=''

########################################
#Making viweing body HTML filw path
ACTION=`cat $tmp-action`
cat ${SYSD}/APPLI/${CATEGORY}/${FUNC}/HTML/${ACTION}.HTML   |
sed -e "s/###STUFF_ID###/$(cat $tmp-lv2 | sed -n 1p)/g"     |
sed -e "s/###FAMILY_NAME###/$(cat $tmp-lv2 | sed -n 2p)/"   |
sed -e "s/###GIVEN_NAME###/$(cat $tmp-lv2 | sed -n 3p)/"    |
sed -e "s/###EMAIL###/$(cat $tmp-email-decode)/"            |
sed -e "s/###TEL1###/$(cat $tmp-lv2 | sed -n 6p)/"          |
sed -e "s/###TEL2###/$(cat $tmp-lv2 | sed -n 7p)/"          |
sed -e "s/###PASSWORD###/NOT_CHANGE/"                       |
sed -e "s/###ENC_ID###/${ENC_ID}/"                          |
sed -e "s/###PW_CONFIRM###/NOT_CHANGE/"                     | 
sed -e "s/###ADMIN_CHK###/${ADMIN_CHK}/"                    |
sed -e "s/###ADMIN_VAL###/$(cat $tmp-lv2 | sed -n 8p)/"     > $tmp-html

#########################################
#page name
echo "Update stuff input" > $tmp-pagename

#########################################
##ending
echo "OK"
exit 0

