#!/bin/bash -vx
#

########################################
#	STUFF EDIT INPUT.CGI
#
#   引数
#       $1:必須 $$
#
#	Written by hiramatsu


########################################
#基本設定
SYSD=$(cd $(dirname $0) && pwd | awk '{print substr($0, 0, index($0, "sureshotsystem")+13)}')
#exec 2> $SYSD/LOG/LOG.$(basename $0).$(date +%Y%m%d).$(date +%H%M%S).$$
tmp=/tmp/tmp_$1
LANG=ja_JP.UTF-8
#PATH=/home/:/home/UTL:/home/TOOL/open-usp-tukubai-2014061402/COMMANDS:$PATH
CATEGORY=`cat $tmp-category`
FUNC=`cat $tmp-func`

########################################
#Check error
ERROR_CHECK(){
	[ $(plus ${PIPESTATUS[@]}) -eq 0 ] && return
cat <<- FIN
	Context-type: text/html
	NG input
FIN
	cat $tmp-result
	exit 1
}

########################################
#同一社員番号確認用にIDを暗号化し、ファイル保存
#また、この暗号化したIDをフォームのhiddenタグに適用
#GETパラメータの順番は、action,idの順番が前提
cat $tmp-get | awk '{split($0,ary,"&"); print ary[2]}' | sed 's/id\=//' > $tmp-id
ID=$(cat $tmp-id)
ENC_ID=$(sha1 $RANDOM$ID)
#修正するスタッフIDをスタッフIDを暗号化したフィル名に書き込み、
#サインインしたスタッフIDのTMPディレクトリに配置する
echo $ID > ${SYSD}/TMP/$(cat ${SYSD}/SESSION/$(session_get 'sureshot_stuff_session_id'))/${ENC_ID}

########################################
#Get Own users data
ARR=( `cat ${SYSD}/DATA/${CATEGORY}/USERS/LV3/${ID}_stuff_* |
        awk -v id=$ID '$1==id{print}'                       |
        tr -s ' ' ' '`)
ID=${ARR[0]}
FAMILY_NAME=${ARR[1]}
GIVEN_NAME=${ARR[2]}
EMAIL=${ARR[3]}
TEL=${ARR[4]}
CREATE_DATE=${ARR[5]}
UPDATE_DATE=${ARR[6]}
ADMIN_FLAG=${ARR[7]}
DEL_FLAG=${ARR[8]}

########################################
#Making viweing body HTML filw path
ACTION=`cat $tmp-action`
cat ${SYSD}/APPLI/${CATEGORY}/${FUNC}/HTML/${ACTION}.HTML   |
sed -e "s/###FAMILY_NAME_ERR###/hidden/"                    |
sed -e "s/###GIVEN_NAME_ERR###/hidden/"                     |
sed -e "s/###EMAIL_ERR###/hidden/"                          |
sed -e "s/###PASSWORD_ERR###/hidden/"                       |
sed -e "s/###PASSWORD_CONFIRMATION_ERR###/hidden/"          |
sed -e "s/###EMAIL_DUPLECATED###/hidden/"                   |
sed -e "s/###FAMILY_NAME_VALUE###/${FAMILY_NAME}/"          |
sed -e "s/###GIVEN_NAME_VALUE###/${GIVEN_NAME}/"            |
sed -e "s/###EMAIL_VALUE###/${EMAIL}/"                      |
sed -e "s/###PASSWORD_VALUE###/NOT_CHANGE/"                 |
sed -e "s/###STUFF_ID###/${ENC_ID}/"                        |
sed -e "s/###PASSWORD_CONFIRMATION_VALUE###/NOT_CHANGE/"    > $tmp-html

#########################################
#page name
echo "Stuff info update" > $tmp-pagename

#########################################
##ending
echo "OK"
exit 0

