#!/bin/bash -vx
#

########################################
#	STUFF EDIT INPUT.CGI
#
#   引数
#       $1:必須 $$
#
#	Written by hiramatsu


########################################
#基本設定
SYSD=$(cd $(dirname $0) && pwd | awk '{print substr($0, 0, index($0, "sureshotsystem")+13)}')
#exec 2> $SYSD/LOG/LOG.$(basename $0).$(date +%Y%m%d).$(date +%H%M%S).$$
tmp=/tmp/tmp_$1
LANG=ja_JP.UTF-8
#PATH=/home/:/home/UTL:/home/TOOL/open-usp-tukubai-2014061402/COMMANDS:$PATH
CATEGORY=`cat $tmp-category`
FUNC=`cat $tmp-func`

########################################
#Check error
ERROR_CHECK(){
	[ $(plus ${PIPESTATUS[@]}) -eq 0 ] && return
cat <<- FIN
	Context-type: text/html
	NG input
FIN
	cat $tmp-result
	exit 1
}

########################################
#同一社員番号確認用にIDを暗号化し、ファイル保存
#また、この暗号化したIDをフォームのhiddenタグに適用
#GETパラメータの順番は、action,idの順番が前提
cat $tmp-get | awk '{split($0,ary,"&"); print ary[2]}' | sed 's/id\=//' > $tmp-id
STUFF_ID=$(cat $tmp-id)
ENC_ID=$(sha1 $RANDOM$STUFF_ID)
#修正するスタッフIDをスタッフIDを暗号化したフィル名に書き込み、
#サインインしたスタッフIDのTMPディレクトリに配置する
echo $STUFF_ID > ${SYSD}/TMP/$(cat ${SYSD}/SESSION/$(session_get 'sureshot_stuff_session_id'))/${ENC_ID}

########################################
#Get Own users data
#stuff_id	family_name	given_name	account_id	tel1	tel2	create_date	update_date	create_user	update_user	admin_flg	show_each_url	edit_each_url	delete_each_url
#配列ARRの添字は0始まり
ARR=( `cat ${SYSD}/DATA/${CATEGORY}/USERS/LV3/${STUFF_ID}_stuff_* |
        awk -v id=$STUFF_ID '$1==id{print}'                       |
        tr -s ' ' ' '`)
FAMILY_NAME=${ARR[1]}
GIVEN_NAME=${ARR[2]}
EMAIL=${ARR[3]}
TEL1=${ARR[4]}
TEL2=${ARR[5]}
ADMIN_FLG=${ARR[10]}

########################################
#管理者権限を取得
[ "${ADMIN_FLG}" = "1" ] && ADMIN_CHK="checked" || ADMIN_CHK=''

########################################
#Making viweing body HTML filw path
ACTION=`cat $tmp-action`
cat ${SYSD}/APPLI/${CATEGORY}/${FUNC}/HTML/${ACTION}.HTML   |
sed -e "s/###FAMILY_NAME_ISNULL###/hidden/"                    |
sed -e "s/###FAMILY_NAME_LENGTH###/hidden/"                    |
sed -e "s/###GIVEN_NAME_ISNULL###/hidden/"                     |
sed -e "s/###GIVEN_NAME_LENGTH###/hidden/"                     |
sed -e "s/###EMAIL_ISNULLK###/hidden/"                          |
sed -e "s/###EMAIL_DUPLECATE###/hidden/"                   |
sed -e "s/###TEL1_ISNULL###/hidden/"                           |
sed -e "s/###TEL1_MATCH###/hidden/"                           |
sed -e "s/###TEL1_NUMERIC###/hidden/"                           |
sed -e "s/###TEL2_MATCH###/hidden/"                           |
sed -e "s/###TEL2_NUMERIC###/hidden/"                           |
sed -e "s/###PASSWORD_ISNULL###/hidden/"                       |
sed -e "s/###PASSWORD_LENGTH###/hidden/"                       |
sed -e "s/###PW_CONFIRM_ISNULL###/hidden/"                     |
sed -e "s/###PW_CONFIRM_COMPARE###/hidden/"                     |
sed -e "s/###ADMIN_ERR###/hidden/"                          |
sed -e "s/###FAMILY_NAME###/${FAMILY_NAME}/"                |
sed -e "s/###GIVEN_NAME###/${GIVEN_NAME}/"                  |
sed -e "s/###EMAIL###/${EMAIL}/"                            |
sed -e "s/###TEL1###/${TEL1}/"                              |
sed -e "s/###TEL2###/${TEL2}/"                              |
sed -e "s/###PASSWORD###/NOT_CHANGE/"                       |
sed -e "s/###ENC_ID###/${ENC_ID}/"                          |
sed -e "s/###PW_CONFIRM###/NOT_CHANGE/"                     | 
sed -e "s/###ADMIN_CHK###/${ADMIN_CHK}/"                    |
sed -e "s/###ADMIN_VAL###/${ADMIN_FLG}/"                    > $tmp-html

#########################################
#page name
echo "Update stuff input" > $tmp-pagename

#########################################
##ending
echo "OK"
exit 0

