#!/bin/bash -evx
#

########################################
#	SET_LIST/EDIT/SET/COMPLETE.CGI
#
#   引数
#       $1:プロセスID
#
#	Written by hiramatsu


########################################
#基本設定
SYSD=$(cd $(dirname $0) && pwd | awk '{print substr($0, 0, index($0, "sureshotsystem")+13)}')
#exec 2> ${SYSD}/LOG/LOG.$(basename $0).$(date +%Y%m%d).$(date +%H%M%S).$$
tmp=/tmp/tmp_$1
LANG=ja_JP.UTF-8
#PATH=/home/:/home/UTL:/home/TOOL/open-usp-tukubai-2014061402/COMMANDS:$PATH
CATEGORY=`cat $tmp-category`
FUNC=`cat $tmp-func`

########################################
#Check error
ERROR_CHECK(){
	[ $(plus ${PIPESTATUS[@]}) -eq 0 ] && return
cat <<- FIN
	Context-type: text/html
	NG input
FIN
	cat $tmp-result
	exit 1
}

########################################
#セットカテゴリ更新中は、処理をさせない
#ls ${SYSD}/LOCK/SET_CATEGORY/* > $tmp-checker 2> /dev/null
#if [ -n cat $tmp-checker ] ; then
#    echo "333" > $tmp-ajax-html
#    exit 0
#fi

#######################################
#フォームの入力値を取得
SET_CATEGORY_NO=$(nameread SET_CATEGORY_NO $tmp-post)
SET_CATEGORY_NX=$(nameread SET_CATEGORY_NX $tmp-post)
SET_CATEGORY_NM=$(nameread SET_CATEGORY_NM $tmp-post)
SET_NO=$(nameread SET_NO $tmp-post)
SET_NM=$(nameread SET_NM $tmp-post)
SET_PRICE=$(nameread SET_PRICE $tmp-post)
SET_REMARKS=$(nameread SET_REMARKS $tmp-post)

########################################
#DATAディレクトリ
DATAD_OLD=${SYSD}/DATA/${CATEGORY}/LISTS/${SET_CATEGORY_NX}
DATAD_NEW=${SYSD}/DATA/${CATEGORY}/LISTS/${SET_CATEGORY_NO}

########################################
#重複確認
cat ${DATAD_OLD}/LV3/* | awk -v nm=${SET_NM} '$4==nm{print $1}' > $tmp-valid1
if [ -n "$(cat $tmp-valid1)" ] ; then
    echo 2222 > $tmp-ajax-html
    exit 0
fi

########################################
#既存データから作成日時取得、現在日時を更新日時とする
ls ${DATAD_OLD}/LV1/${SET_NO}_setlist_base_* | cut -d'_' -f4 | sort -nk1,1 | head -n 1 > $tmp-create
CREATE_DATE=$(cat $tmp-create)
UPDATE_DATE=$(date +%Y%m%d%H%M%S)

#######################################
#ディレクトリを作成する
if [ -e "${DATAD_NEW}"  ]; then
    :
else
    mkdir ${DATAD_NEW} 
    cp -rp ${SYSD}/DATA/ORG_LV1-3 ${DATAD_NEW}/
    chmod -R 770 ${DATAD_NEW} #オーナーと権限を再帰的に設定
    ERROR_CHECK
fi

#######################################
#セットカテゴリが同一かどうかをチェック
if [ "${DATAD_OLD}" = "${DATAD_NEW}" ]; then
    CATEG
else

fi

#######################################
#データ格納
#セット番号、セットカテゴリ番号、セットカテゴリ名、セット名、セット価格、備考、作成日、更新日
cat ${SET_NO} ${SET_CATEGORY_NO} ${SET_CATEGORY_NM} ${SET_NM} ${SET_PRICE} ${SET_REMARKS} ${CREATE_DATE} ${UPDATE_DATE} > $tmp-set-list
#LV1
mv $tmp-set-list ${DATAD}/LV1/${NEW_NUM}_setlist_base_${CREATE_DATE}
mv $tmp-set-list_operation ${DATAD}/LV1/${NEW_NUM}_setlist_operation_${CREATE_DATE}
mv $tmp-set-list_parts ${DATAD}/LV1/${NEW_NUM}_setlist_parts_${CREATE_DATE}
#LV2
cat ${DATAD}/LV1/${NEW_NUM}_setlist_base_${CREATE_DATE} > ${DATAD}/LV2/${NEW_NUM}_setlist_base_${CREATE_DATE}
cat ${DATAD}/LV1/${NEW_NUM}_setlist_operation_${CREATE_DATE} > ${DATAD}/LV2/${NEW_NUM}_setlist_operation_${CREATE_DATE}
cat ${DATAD}/LV1/${NEW_NUM}_setlist_parts_${CREATE_DATE} > ${DATAD}/LV2/${NEW_NUM}_setlist_parts_${CREATE_DATE}
#LV3
cat ${DATAD}/LV2/${NEW_NUM}_setlist_base_${CREATE_DATE} > ${DATAD}/LV3/${NEW_NUM}_setlist_base_${CREATE_DATE}
cat ${DATAD}/LV2/${NEW_NUM}_setlist_operation_${CREATE_DATE} > ${DATAD}/LV3/${NEW_NUM}_setlist_operation_${CREATE_DATE}
cat ${DATAD}/LV2/${NEW_NUM}_setlist_parts_${CREATE_DATE} > ${DATAD}/LV3/${NEW_NUM}_setlist_parts_${CREATE_DATE}

#######################################
#仮登録セットリストを削除
rm -rf ${TEMPD}

########################################
#ending
echo "OK"
exit 0
