#!/bin/bash -evx
#

########################################
#	SET_LIST/EDIT/SET/COMPLETE.CGI
#
#   引数
#       $1:プロセスID
#
#	Written by hiramatsu


########################################
#基本設定
SYSD=$(cd $(dirname $0) && pwd | awk '{print substr($0, 0, index($0, "sureshotsystem")+13)}')
#exec 2> ${SYSD}/LOG/LOG.$(basename $0).$(date +%Y%m%d).$(date +%H%M%S).$$
tmp=/tmp/tmp_$1
LANG=ja_JP.UTF-8
#PATH=/home/:/home/UTL:/home/TOOL/open-usp-tukubai-2014061402/COMMANDS:$PATH
CATEGORY=`cat $tmp-category`
FUNC=`cat $tmp-func`

########################################
#仮登録Dir
SESSION=$(session_get 'sureshot_stuff_session_id') 
STUFF_ID=$(cat ${SYSD}/SESSION/${SESSION})
TEMPD=${SYSD}/TMP/${STUFF_ID}/SET_LIST

########################################
#Check error
ERROR_CHECK(){
	[ $(plus ${PIPESTATUS[@]}) -eq 0 ] && return
cat <<- FIN
	Context-type: text/html
	NG input
FIN
	cat $tmp-result
	exit 1
}

#######################################
#フォームの入力値を取得
SET_CATEGORY_NO=$(nameread SET_CATEGORY_NO $tmp-post)
SET_CATEGORY_NX=$(nameread SET_CATEGORY_NX $tmp-post)
SET_CATEGORY_NM=$(nameread SET_CATEGORY_NM $tmp-post)
NUM=$(nameread SET_NO $tmp-post)
SET_NM=$(nameread SET_NM $tmp-post)
SET_NM_NX=$(nameread SET_NM_NX $tmp-post)
SET_PRICE=$(nameread SET_PRICE $tmp-post)
SET_REMARKS=$(nameread SET_REMARKS $tmp-post)

########################################
#重複確認
if [ "${SET_NM}" != "${SET_NM_NX}" ] ; then
  cat ${SYSD}/DATA/SET_LIST/LIST/${SET_CATEGORY_NX}/LV3/*_setlist_base_* |
  awk -v nm=${SET_NM} '$4==nm{print $1}' > $tmp-valid1
  if [ -n "$(cat $tmp-valid1)" ] ; then
    echo 2222 > $tmp-ajax-html
    exit 0
  fi
fi

########################################
#セットの仮登録
#セット番号、セットカテゴリ番号、セットカテゴリ名、セット名、セット価格、備考
rm -f ${TEMPD}/setlist_base
echo ${NUM} ${SET_CATEGORY_NO} ${SET_CATEGORY_NM} ${SET_NM} ${SET_PRICE} ${SET_REMARKS} > ${TEMPD}/setlist_base

########################################
#セットのカテゴリを変更した場合
if [ "${SET_CATEGORY_NO}" = "${SET_CATEGORY_NX}" ]; then
  :
else
  echo ${SET_CATEGORY_NX} > ${TEMPD}/setlist_category_nx
  echo ${SET_CATEGORY_NO} > ${TEMPD}/setlist_category_no
fi

#completeで以下を使用する
#
#
#
#########################################
##DATAディレクトリ
#DATAD_OLD=${SYSD}/DATA/${CATEGORY}/LISTS/${SET_CATEGORY_NX}
#DATAD_NEW=${SYSD}/DATA/${CATEGORY}/LISTS/${SET_CATEGORY_NO}
#
########################################
##ディレクトリを作成する
#if [ -e "${DATAD_NEW}"  ]; then
#    :
#else
#    mkdir ${DATAD_NEW} 
#    cp -rp ${SYSD}/DATA/ORG_LV1-3 ${DATAD_NEW}/
#    chmod -R 770 ${DATAD_NEW} #オーナーと権限を再帰的に設定
#    ERROR_CHECK
#fi
#
#########################################
##既存データから作成日時取得、現在日時を更新日時とする
#ls ${DATAD_OLD}/LV1/${NUM}_setlist_base_* | cut -d'_' -f4 | sort -nk1,1 | head -n 1 > $tmp-create
#CREATE_DATE=$(cat $tmp-create)
#UPDATE_DATE=$(date +%Y%m%d%H%M%S)
#
#########################################
##該当のデータ操作をロック
#LOCK=`${SYSD}/CGI/LOCK/LOCK $1 'SET_LIST' ${NUM}`
#LOCK_STATUS=$(echo $LOCK | cut -d'.' -f4)
#[ ${LOCK_STATUS} != 'LOCKED' ] && exit 0 || :
#
########################################
##一時ファイル化
##セット番号、セットカテゴリ番号、セットカテゴリ名、セット名、セット価格、備考、作成日、更新日
#echo ${NUM} ${SET_CATEGORY_NO} ${SET_CATEGORY_NM} ${SET_NM} ${SET_PRICE} ${SET_REMARKS} ${CREATE_DATE} ${UPDATE_DATE} > $tmp-set-list
#
########################################
##データ格納
##LV1:原始データとして、ファイル追加のみを行う
#mv $tmp-set-list ${DATAD_NEW}/LV1/${NUM}_setlist_base_${UPDATE_DATE}
#
##カテゴリを変更した場合
#if [ "${SET_CAYEGORY_NO}" != "${SET_CATEGORY_NX}" ]; then
#    #旧カテゴリにあるLV1のパーツを論理削除
#    ls ${DATAD_OLD}/LV1/${NUM}_setlist_base_* | sort -nk1 | tail -n 1 > $tmp-delete-lv1
#    cp $(cat $tmp-delete-lv1) ${DATAD_OLD}/LV1/${NUM}_setlist_base_${UPDATE_DATE}_d
#    #旧カテゴリにあるLV2、LV3のパーツを論理削除ファイルと入れ替える
#    rm -f ${DATAD_OLD}/LV2/${NUM}_setlist_base_*
#    cp ${DATAD_OLD}/LV1/${NUM}_setlist_base_${UPDATE_DATE}_d ${DATAD_OLD}/LV2/   
#    rm -f ${DATAD_OLD}/LV3/${NUM}_setlist_base_*
#    cp ${DATAD_OLD}/LV2/${NUM}_setlist_base_* ${DATAD_OLD}/LV3/   
#fi
#
##LV3:LV2を更新ファイルと入れ替え
#rm -f ${DATAD_NEW}/LV2/${NUM}_setlist_base_*
#cp -fp ${DATAD_NEW}/LV1/${NUM}_setlist_base_${UPDATE_DATE} ${DATAD_NEW}/LV2/
#rm -f ${DATAD_NEW}/LV3/${NUM}_setlist_base_*
#cp -fp ${DATAD_NEW}/LV2/${NUM}_setlist_base_${UPDATE_DATE} ${DATAD_NEW}/LV3/
#
#########################################
##データ操作ロックを解除
#UNLOCK_STATUS=`${SYSD}/CGI/LOCK/UNLOCK $1 'SET_LIST' ${NUM}`
#[ ${UNLOCK_STATUS} != 'UNLOCK' ] && exit 0 || :
#
########################################
#ending
echo "OK"
exit 0
