#!/bin/bash -vx
#

########################################
# SET_LIST/EDIT/SET INPUT.CGI
#
#   $1:必須 $$

#	Written by hiramatsu


########################################
#基本設定
export LANG=ja_JP.utf8
echo $LANG
SYSD=$(cd $(dirname $0) && pwd | awk '{print substr($0, 0, index($0, "sureshotsystem")+13)}')
#exec 2> $SYSD/LOG/LOG.$(basename $0).$(date +%Y%m%d).$(date +%H%M%S).$$
tmp=/tmp/tmp_$1
LANG=ja_JP.UTF-8
#PATH=/home/:/home/UTL:/home/TOOL/open-usp-tukubai-2014061402/COMMANDS:$PATH
CATEGORY=`cat $tmp-category`
FUNC=`cat $tmp-func`
DATAD=${SYSD}/DATA/${CATEGORY}/LISTS

#######################################
#Check error
ERROR_CHECK(){
	[ $(plus ${PIPESTATUS[@]}) -eq 0 ] && return
cat <<- FIN
	Context-type: text/html
	NG input
FIN
	cat $tmp-result
	exit 1
}

########################################
#GETパラメータを取得
SET_CATEGORY_NO=$( cat $tmp-get | cut -d'&' -f1 | sed -e 's/SET_CATEGORY_NO_HID_EDIT\=//' | ruby -r uri -ne 'print URI.unescape $_')
SET_NO=$( cat $tmp-get | cut -d'&' -f2 | sed -e 's/SET_NO_HID_EDIT\=//' | ruby -r uri -ne 'print URI.unescape $_')

#######################################
#セットを取得
cat ${DATAD}/${SET_CATEGORY_NO}/LV3/${SET_NO}_setlist_base_*[^_d]   |
LA1NG=C sort -nk1,1                                                 > $tmp-set-list

#######################################
#セット情報を取得
#52 1 オイル交換 Oil_Filter交換 12000 S1 20170531173834 20170531173834
SET_CATEGORY_NM=$(cat $tmp-set-list | cut -d' ' -f3)  
SET_NM=$(cat $tmp-set-list | cut -d' ' -f4)  
SET_PRICE=$(cat $tmp-set-list | cut -d' ' -f5)
SET_REMARKS=$(cat $tmp-set-list | cut -d' ' -f6)

#######################################
#セットカテゴリを取得
cat ${SYSD}/DATA/SET_CATEGORY/LISTS/LV3/*_set_category_*[^_d]  |
LA1NG=C sort -nk1,1                                                       > $tmp-set-category

########################################
#セットカテゴリ
# 1;カテゴリ番号 2;カテゴリ名
mojihame -lRECORDS ${SYSD}/APPLI/${CATEGORY}/NEW/HTML/SET/SET_CATEGORY_NEW.HTML $tmp-set-category > $tmp-set-category-new

########################################
# セットカテゴリの改行文字を「\\n」という3文字の文字列に置換
CATEGORY_NEW=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-set-category-new`

########################################
#tableにrecordsを嵌め込む
cat ${SYSD}/APPLI/${CATEGORY}/EDIT/HTML/SET/TABLE.HTML  |
sed -e "s|###SET_CATEGORY_NM###|${SET_CATEGORY_NM}|g"   |
sed -e "s|###SET_CATEGORY_NO###|${SET_CATEGORY_NO}|g"   |
sed -e "s|###SET_NO###|${SET_NO}|g"                     |
sed -e "s|###SET_NM###|${SET_NM}|g"                     |
sed -e "s|###SET_PRICE###|${SET_PRICE}|g"               |
sed -e "s|###SET_REMARKS###|${SET_REMARKS}|g"           |
sed -e "s|###CATEGORY###|${CATEGORY_NEW}|g"             > $tmp-table-html

########################################
# 改行文字を「\\n」という3文字の文字列に置換
TABLE=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-table-html`

#tableをはめ込む、ページャーを差し込む
cat ${SYSD}/APPLI/${CATEGORY}/NEW/HTML/SET/INPUT.HTML               |
sed -e "s|###INFO_MSG###|"登録するセット名を入力してください。"|g"  |
sed -e "s|###TABLE###|${TABLE}|g"                                   > $tmp-html

########################################
#page name
echo "Set Name input" > $tmp-pagename

########################################
echo "OK"
exit 0
