#!/bin/bash -evx
#

########################################
#	ROOT.CGI
#
#	Written by hiramatsu


########################################
#基本設定
SYSD=$(cd $(dirname $0) && pwd | awk '{print substr($0, 0, index($0, "sureshotsystem")+13)}')
exec 2> ${SYSD}/LOG/LOG.$(basename $0).$(date +%Y%m%d).$(date +%H%M%S).$$
tmp=/tmp/tmp_$$
LANG=ja_JP.UTF-8
PATH=/home/:/usr/local/bin:${SYSD}/SYS/open-usp-tukubai-2014061402/COMMANDS:$PATH
#SESS_LIFE_MIN=5

########################################
#Check error
ERROR_CHECK(){
	[ $(plus ${PIPESTATUS[@]}) -eq 0 ] && return
cat <<- FIN
	Context-type: text/html
	NG input
FIN
	cat $tmp-result
	exit 1
}

#######################################
#View
cat << FIN
Content-type: text/html

FIN

cat << FIN
<!DOCTYPE html>
<html lang="jp">
FIN

cat << FIN
<body>
FIN


echo ""
echo "HELLO"

cat << FIN
</body>
FIN

cat << FIN
</html>
FIN

#########################################
##ending
rm -f $tmp-*
exit 0
