#!/bin/bash -vx
#

########################################
#	NUMBERS.CGI
#
#   引数
#       $1:プロセスID
#       $2:カテゴリ名
#
#	Written by hiramatsu


########################################
#基本設定
SYSD=$(cd $(dirname $0) && pwd | awk '{print substr($0, 0, index($0, "sureshotsystem")+13)}')
#exec 2> ${SYSD}/LOG/LOG.$(basename $0).$(date +%Y%m%d).$(date +%H%M%S).$$
tmp=/tmp/tmp_$1
LANG=ja_JP.UTF-8
PATH=/home/:/home/UTL:/home/TOOL/open-usp-tukubai-2014061402/COMMANDS:$PATH
NUMBERSD=${SYSD}/DATA/NUMBERS/$2

########################################
#Check error
ERROR_CHECK(){
	[ $(plus ${PIPESTATUS[@]}) -eq 0 ] && return
    [ -z ${STATUS} ] && STATUS='LOCK_ERROR'
    cat ${SYSD}/HTML/ERROR/SYSTEM_ERROR.HTML                        |
    sed -e "s/###ERROR1_LABEL###/採番処理中にエラー/"               |
    sed -e "s/###ERROR2_LABEL###/${NUMBERSD}/"                      |
    sed -e "s|###ERROR3_LABEL###||"                                 |
    sed -e "s/###ERROR4_LABEL###//"                                 |
    sed -e "s/###ERROR5_LABEL###//"                                 > $tmp-html
    echo "ERROR"
    exit 0
}

########################################
#新規採番番号を確定
#指定されたカテゴリのNUMBERS/ORIGINの最小値ファイル名を/USEDへ移動
ls ${NUMBERSD}/ORIGIN/ | sort -n | head -n 1                    |
awk -v url=${NUMBERSD} '{print sprintf(url"/ORIGIN/%s",$1)}'    |
xargs -I{} mv -v {} ${NUMBERSD}/USED > $tmp-numbers
ERROR_CHECK

########################################
#確定(USEDに移された番号)した番号を取得
NUM=$( cat $tmp-numbers |
rev                     |
cut -d' ' -f1           |
cut -c 1 )
ERROR_CHECK

########################################
#戻り値
echo ${NUM}

########################################
#正常終了
exit 0
