#!/bin/bash -vx
#

########################################
#	NUMBER_SEQ.CGI
#
#   引数
#       $1:必須：プロセスID
#       $2:必須：カテゴリ名
#       $3:必須：開始番号
#       $4:必須：終了番号
#
#	Written by hiramatsu


########################################
#Set basic
SYSD=/home/sureshotsystem
exec 2> ${SYSD}/LOG/LOG.$(basename $0).$(date +%Y%m%d).$(date +%H%M%S).$$
tmp=/tmp/tmp_$1
LANG=ja_JP.UTF-8
PATH=/home/:/home/UTL:/home/TOOL/open-usp-tukubai-2014061402/COMMANDS:$PATH

########################################
#Check error
ERROR_CHECK(){
	[ $(plus ${PIPESTATUS[@]}) -eq 0 ] && return
    cat ${SYSD}/HTML/ERROR/SYSTEM_ERROR.HTML                        |
    sed -e "s/###ERROR1_LABEL###/先振り採番ロット処理中にエラー/"   |
    sed -e "s/###ERROR2_LABEL###/カテゴリ：${CATEGORY}/"            |
    sed -e "s/###ERROR3_LABEL###/開始番号:${START}/"                |
    sed -e "s/###ERROR4_LABEL###/終了番号:${END}/"                  |
    sed -e "s/###ERROR5_LABEL###//"                                 > $tmp-html
    echo "SEQ_ERROR"
    exit 0
}

########################################
#Arguments
CATEGORY=$2
START=$3
END=$4

########################################
#EMPOLYEEのデータ操作をロック
LOCK=`${SYSD}/CGI/LOCK/LOCK $1 'EMPLOYEE' `
LOCK_STATUS=$(echo $LOCK | cut -d'.' -f4)
[ ${LOCK_STATUS} != 'LOCKED' ] && exit 0 || :

########################################
#DATA/NUMBERS/配下に指定したカテゴリ名のディレクトリが存在しない場合、
#そのカテゴリ名のディレクトリとその配下にORIGIN/とUSED/ディレクトリを作成する
if [ -e ${SYSD}/DATA/NUMBERS/${CATEGORY}  ]; then
    :
else
    #ディレクトリ作成
    mkdir ${SYSD}/DATA/NUMBERS/${CATEGORY}
    mkdir ${SYSD}/DATA/NUMBERS/${CATEGORY}/ORIGIN
    mkdir ${SYSD}/DATA/NUMBERS/${CATEGORY}/USED
    #オーナーと権限を再帰的に設定
    chmod -R 775 ${SYSD}/DATA/NUMBERS/${CATEGORY}
    chown -R root:apache ${SYSD}/DATA/NUMBERS/${CATEGORY}
    ERROR_CHECK
fi

########################################
#採番ファイルを作成
for i in `seq $START $END`
do
    touch ${SYSD}/DATA/NUMBERS/${CATEGORY}/ORIGIN/$i
    chmod 775 ${SYSD}/DATA/NUMBERS/${CATEGORY}/ORIGIN/$i
    ERROR_CHECK
done

########################################
#EMPOLYEEのデータ操作ロックを解除
UNLOCK_STATUS=`${SYSD}/CGI/LOCK/UNLOCK $1 'EMPLOYEE'`
[ ${UNLOCK_STATUS} != 'UNLOCK'] && exit 0 || :

########################################
#正常終了
echo "SUCCESS"
exit 0
