#!/bin/bash -evx
#

########################################
#	ROOT.CGI
#
#	Written by hiramatsu


########################################
#基本設定
SYSD=/home/sureshotsystem
exec 2> ${SYSD}/LOG/LOG.$(basename $0).$(date +%Y%m%d).$(date +%H%M%S).$$
tmp=/tmp/tmp_$$
LANG=ja_JP.UTF-8
PATH=/home/:/home/UTL:/usr/local/bin:/home/TOOL/open-usp-tukubai-2014061402/COMMANDS:$PATH
#SESS_LIFE_MIN=5

########################################
#Check error
ERROR_CHECK(){
	[ $(plus ${PIPESTATUS[@]}) -eq 0 ] && return
cat <<- FIN
	Context-type: text/html
	NG input
FIN
	cat $tmp-result
	exit 1
}

########################################
#Get Parameters
#1.Requst Methodの取得
METHOD=$REQUEST_METHOD
echo $METHOD > $tmp-method

#2.Request URL
URI=$REQUEST_URI
echo $URI > $tmp-uri

#3 Get method parameter.
case $METHOD in
GET)
    if [ ! -z $QUERY_STRING ]; then
        echo $QUERY_STRING > $tmp-get
    else
        touch $tmp-get
    fi
    ;;
POST)
    if [ ! -z $CONTENT_LENGTH ]; then
	    dd bs=$CONTENT_LENGTH |
	    cgi-name -d_ -i_	> $tmp-post
    else
	    touch $tmp-post
    fi
    ;;
#PUT)
#    #update 残念ながらSHELLでは、GET扱いらしい、、、 →POSTで対応するしか,AJAX
#    ;;
#DELETE)
#    #destroy 残念ながらSHELLでは、GET扱いらしい、、、→POSTで対応するしか,AJAX
#    ;;
esac


#######################################
#Set rooting
#URLを分解し、カテゴリと処理とアクションを取得する
ARR=( `echo $URI | tr -s '/' ' '`)
APP=${ARR[0]}
CATEGORY=${ARR[1]}
FUNC=${ARR[2]}
ACTION=${ARR[3]}
ARR_COUNT=${#ARR[*]}
echo $APP > $tmp-uri_ap
echo $CATEGORY > $tmp-category
echo $FUNC > $tmp-func
echo $ACTION > $tmp-action

########################################
#ログインセッションの確認と設定
STUFF_SESS_ID='sureshot_stuff_session_id'    #社員用ログインセッションID

#社員登録とログイン画面以外の場合、有効なログインセッションを要求
case ${CATEGORY}/${FUNC} in
#"STUFF/NEW" | "STUFF/SIGNIN" | "/")
"STUFF/NEW" | "STUFF/SIGNIN")
    ;;
*)
    #ログインセッションを確認
    SESS_STATUS=`${SYSD}/CGI/SESSION/SESSION_CHECK ${STUFF_SESS_ID} `
    case $SESS_STATUS in
    live)
        #ログインセッションが有効の場合、時間を延長
        SESS=$(session_get ${STUFF_SESS_ID})
        COOK=`${SYSD}/CGI/SESSION/SESSION_SET ${STUFF_SESS_ID} `
        echo $COOK > $tmp-cook-login
        ;;
    *)      
        #ログインセッションが無効の場合、ログイン画面へ
        #GETの場合、リターンURLを設定
        #POSTの場合、更新処理の途中にセッション切れを起こしている為、
        #これを無効とするのでTOP画面に戻す→リターンURL設定なし
        [ $METHOD = 'GET' ] && 
        RETURN_URL=${CATEGORY}/${FUNC}/${ACTION}/$( cat $tmp-get ) || RETURN_URL=''
        CATEGORY='STUFF'
        FUNC='SIGNIN'
        ACTION='INPUT'
        echo ${RETURN_URL} > $tmp-return-url
        echo ${CATEGORY} > $tmp-category
        echo $FUNC > $tmp-func
        echo $ACTION > $tmp-action
        ;;
    esac
    ;;
esac

#######################################
#Do the business logic & return HTML Body
if [ -n "${FUNC}${ACTION}" ] ; then
    result=`../APPLI/${CATEGORY}/${FUNC}/CGI/${ACTION} $$`
    echo $result > $tmp-result
else
    cat ${SYSD}/HTML/INDEX.HTML > $tmp-html
fi

########################################
#セットするCookie文字列を取得する
[ -e $tmp-cook-login ] && COOK_SET_LOGIN=`cat $tmp-cook-login` || :
[ -e $tmp-cook-account ] && COOK_SET_ACCOUNT=`cat $tmp-cook-account` || :


########################################
#View
cat << FIN
Content-type: text/html
${COOK_SET_LOGIN}
${COOK_SET_ACCOUNT}

FIN

echo ""
cat $tmp-html

#########################################
##ending
rm -f $tmp-*
exit 0
