#!/bin/bash -evx
#

########################################
#	EMPLOYEE EDIT COMPLETE.CGI
#
#	Written by hiramatsu


########################################
#Set basic
SYSD=/home/sureshotsystem
#exec 2> ${SYSD}/LOG/LOG.$(basename $0).$(date +%Y%m%d).$(date +%H%M%S).$$
tmp=/tmp/tmp_$1
LANG=ja_JP.UTF-8
PATH=/home/:/home/UTL:/home/TOOL/open-usp-tukubai-2014061402/COMMANDS:$PATH
CATEGORY=`cat $tmp-category`
FUNC=`cat $tmp-func`
LOGIND=${SYSD}/DATA/${CATEGORY}/LOGIN
USERSD=${SYSD}/DATA/${CATEGORY}/USERS
EMP_SESS_ID='ss_employee_session_id'

########################################
#Check error
ERROR_CHECK(){
	[ $(plus ${PIPESTATUS[@]}) -eq 0 ] && return
cat <<- FIN
	Context-type: text/html
	NG input
FIN
	cat $tmp-result
	exit 1
}

#######################################
#Get Form Data
ID=$(nameread ID $tmp-post)
VALUE1=$(nameread FAMILY_NAME $tmp-post)
VALUE2=$(nameread GIVEN_NAME $tmp-post)
VALUE3=$(nameread EMAIL $tmp-post)
VALUE4=$(nameread PASSWORD $tmp-post)

########################################
#Set employee number
LATEST_NUM=$(ls ${USERSD}/LV1 | sort -n | awk 'END{print}' | awk '{gsub(/\_employee/,"",$1);print}')
EMPLOYEE_NUM=$((LATEST_NUM + 1))

########################################
#Write data to tempolary file
#1.社員番号 2.姓 3.名 4.EMAIL 5.TEL 6.作成日時 7.更新日時 8.削除フラグ
echo ${EMPLOYEE_NUM}" "${VALUE1}" "${VALUE2}" "${VALUE3}" - "$(date +%Y%m%d%H%M%S)" "$(date +%Y%m%d%H%M%S)" "0 > $tmp-employee

########################################
#Write login to tempolary file
#1.社員番号 3.EMAIL 2.PW 3.作成日時 4.更新日時 5.削除フラグ
echo ${EMPLOYEE_NUM}" "${VALUE3}" "${VALUE4}" "$(date +%Y%m%d%H%M%S)" "$(date +%Y%m%d%H%M%S)" "0 > $tmp-login

########################################
#Data Saving to LOGIN
$(mv $tmp-login ${LOGIND}/LV1/${EMPLOYEE_NUM}_loginpass)

########################################
#Data Saving to USERS
$(mv $tmp-employee ${USERSD}/LV1/${EMPLOYEE_NUM}_employee)

########################################
#Login Stage up to LV2-3
cat ${LOGIND}/LV1/${EMPLOYEE_NUM}_loginpass  |
LANG=C sort -k1,1                           >> ${LOGIND}/LV2/LOGINPASSES
cat ${LOGIND}/LV2/LOGINPASSES               |
LANG=C sort -k1,1                           > ${LOGIND}/LV3/LOGINPASSES

########################################
#UserData Stage up to LV2-3
cat ${USERSD}/LV1/${EMPLOYEE_NUM}_employee    |
LANG=C sort -nk1,1                           >> ${USERSD}/LV2/EMPLOYEES
cat ${USERSD}/LV2/EMPLOYEES                  |
LANG=C sort -nk1,1                           > ${USERSD}/LV3/EMPLOYEES
COOK=`${SYSD}/CGI/SESSION/SESSION_SET ${EMP_SESS_ID} `
echo $COOK > $tmp-cook

########################################
#UserData Stage up to LV4
cat ${USERSD}/LV1/${EMPLOYEE_NUM}_employee      |
LANG=C sort -nk1,1                              |
awk '{print sprintf("/APP/EMPLOYEE/USERS/SHOW/?id=%d %d %s %s %s %s %s %s %d /APP/EMPLOYEE/EDIT/INPUT/?id=%d",$1,$1,$2,$3,$4,$5,$6,$7,$8,$1)}' >>${USERSD}/LV4/EMPLOYEES

########################################
#SET SESSION
COOK=`${SYSD}/CGI/SESSION/SESSION_SET ${EMP_SESS_ID} `
echo $COOK > $tmp-cook

########################################
#HTMLの設定
action=`cat $tmp-action`
cat ${SYSD}/APPLI/${CATEGORY}/${FUNC}/HTML/${action}.HTML   |
sed -e "s/###FAMILY_NAME_LABEL###/${VALUE1}/"   |
sed -e "s/###GIVEN_NAME_LABEL###/${VALUE2}/"    |
sed -e "s/###EMAIL_LABEL###/${VALUE3}/"         > $tmp-html

###############################################################################
#ending
echo "employee new user OK"
#echo $COOK_SET
exit 0



