#!/bin/bash -vx
#

########################################
# SET_LIST/LIST SHOW.CGI
#
#   $1:必須 $$
#
#	Written by hiramatsu


########################################
#基本設定
export LANG=ja_JP.utf8
echo $LANG
SYSD=$(cd $(dirname $0) && pwd | awk '{print substr($0, 0, index($0, "sureshotsystem")+13)}')
#exec 2> $SYSD/LOG/LOG.$(basename $0).$(date +%Y%m%d).$(date +%H%M%S).$$
tmp=/tmp/tmp_$1
LANG=ja_JP.UTF-8
#PATH=/home/:/home/UTL:/home/TOOL/open-usp-tukubai-2014061402/COMMANDS:$PATH
CATEGORY=`cat $tmp-category`
FUNC=`cat $tmp-func`
DATAD=${SYSD}/DATA/${CATEGORY}/LISTS

#######################################
#Check error
ERROR_CHECK(){
	[ $(plus ${PIPESTATUS[@]}) -eq 0 ] && return
cat <<- FIN
	Context-type: text/html
	NG input
FIN
	cat $tmp-result
	exit 1
}

########################################
#仮登録を削除
SESSION=$(session_get 'sureshot_stuff_session_id') 
STUFF_ID=$(cat ${SYSD}/SESSION/${SESSION})
TEMPD=${SYSD}/TMP/${STUFF_ID}/SET_LIST

########################################
#仮登録を削除
rm -rf ${TEMPD}

########################################
#GETパラメーターを取得
#ページを取得(初期はなし、絞込の場合は、page=1
QRY_PAGE=$( cat $tmp-get | sed -e 's/^.*\(page\=[0-9]*\).*$/\1/' | sed -e 's/page\=//')

########################################
#SEARCHで来た場合
#課題：正規表現で狙った箇所の文字列を抜き出したいが出来ていない
#その為、フォーム側のパラメーターの順序に合わせなければならなくなっている(cut)
cat $tmp-get | grep 'SEARCH' > $tmp-search
if [ -n "$(cat $tmp-get | grep 'SEARCH=1')" ] ; then
    #絞込のカテゴリを取得(urldecode)
    SET_PAGE_CATEGORY=$( cat $tmp-get | cut -d'&' -f1 | sed -e 's/SET_CATEGORY_NM_HID_PAGE\=//' | ruby -r uri -ne 'print URI.unescape $_')
    SET_PAGE_CATEGORY_NO=$( cat $tmp-get | cut -d'&' -f2 | sed -e 's/SET_CATEGORY_NO_HID_PAGE\=//' | ruby -r uri -ne 'print URI.unescape $_')
else
    SET_PAGE_CATEGORY=$( cat $tmp-get | cut -d'&' -f2 | sed -e 's/set-category\=//' | ruby -r uri -ne 'print URI.unescape $_')
    SET_PAGE_CATEGORY_NO=$( cat $tmp-get | cut -d'&' -f3 | sed -e 's/set-category-no\=//' | ruby -r uri -ne 'print URI.unescape $_')
fi

#######################################
#最大表示レコード数設定ファイルの確認
if [ -e ${SYSD}/SYS/VIEW/${CATEGORY}/${FUNC}/VIEW_MAX_RECORDS ]; then
    :
else
    mkdir ${SYSD}/SYS/VIEW/${CATEGORY}
    mkdir ${SYSD}/SYS/VIEW/${CATEGORY}/${FUNC}
    cp ${SYSD}/SYS/VIEW/ORG_VIEW_MAX/VIEW_MAX_RECORDS ${SYSD}/SYS/VIEW/${CATEGORY}/${FUNC}/
    cp ${SYSD}/SYS/VIEW/ORG_VIEW_MAX/VIEW_MAX_PAGES ${SYSD}/SYS/VIEW/${CATEGORY}/${FUNC}/
fi

#######################################
#最大表示レコード数
cat ${SYSD}/SYS/VIEW/${CATEGORY}/${FUNC}/VIEW_MAX_RECORDS | 
awk '{print $2}' > $tmp-max-records
VIEW_MAX_RECORDS=$( cat $tmp-max-records )

########################################
#最大表示ページ数
cat ${SYSD}/SYS/VIEW/${CATEGORY}/${FUNC}/VIEW_MAX_PAGES | 
awk '{print $2}' > $tmp-max-pages
VIEW_MAX_PAGES=$( cat $tmp-max-pages )

#Set record start & end
if [ -z $(echo ${QRY_PAGE}) ] || [ "${QRY_PAGE}" = 1 ]; then
    SHOW_PAGE=1
    START=1
    END=${VIEW_MAX_RECORDS}
else
    SHOW_PAGE=${QRY_PAGE}
    END=$(expr ${QRY_PAGE} \* ${VIEW_MAX_RECORDS} )
    START=$(expr ${END} - ${VIEW_MAX_RECORDS} + 1 )
fi

########################################
#ページャーを設定
if [ "${PAGE_CATEGORY_NO}" -gt 0 ] ; then
    RECORDS=$(cat ${DATAD}/${PAGE_CATEGORY_NO}/LV3/*_setlist_base_*[^_d] | wc -l)
else
    RECORDS=$( ls ${DATAD}/*/LV3/*_setlist_base_*[^_d] | wc -l )
fi
RESULT=`${SYSD}/CGI/PAGER $1 "/APP/SET_LIST/LISTS/SHOW" ${SHOW_PAGE} ${RECORDS} ${VIEW_MAX_RECORDS} ${VIEW_MAX_PAGES} "&category=${PAGE_CATEGORY}" "&category-no=${PAGE_CATEGORY_NO}"`

########################################
#セットカテゴリを取得
cat ${SYSD}/DATA/SET_CATEGORY/LISTS/LV3/*[^_d]    |
LANG=C sort -nk1,1                                  > $tmp-set-category

########################################
#Page絞り込み用のセットカテゴリ
# 1;カテゴリ番号 2;カテゴリ名
mojihame -lRECORDS ${SYSD}/APPLI/${CATEGORY}/LISTS/HTML/SET_CATEGORY_PAGE.HTML $tmp-set-category > $tmp-set-category-page

########################################
# セットカテゴリの改行文字を「\\n」という3文字の文字列に置換
SET_CATEGORY_PAGE=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-set-category-page`

########################################
#セットリストを取得
if [ "${SET_PAGE_CATEGORY_NO}" -gt 0 ] ; then
    #ページフィルターにALL以外(空欄を除く)が選択された場合
    cat ${DATAD}/${SET_PAGE_CATEGORY_NO}*[^_d]/LV3/*_setlist_base_*[^_d]  |
    LANG=C sort -nk1,1                                                    |
    awk -v s=${START} -v e=${END} 'NR>=s&&NR<=e&&$9!=1'                   |
    juni                                                                  > $tmp-records
else
    cat ${DATAD}/*[^_d]/LV3/*_setlist_base_*[^_d]                         |
    LANG=C sort -nk1,1                                                    |
    awk -v s=${START} -v e=${END} 'NR>=s&&NR<=e&&$9!=1'                   |
    juni                                                                  > $tmp-records
fi

mojihame -lRECORDS ${SYSD}/APPLI/${CATEGORY}/${FUNC}/HTML/RECORDS.HTML $tmp-records     > $tmp-table-records

########################################
# 改行文字を「\\n」という3文字の文字列に置換
TABLE_RECORDS=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-table-records`

########################################
#tableにrecordsを嵌め込む
cat ${SYSD}/APPLI/${CATEGORY}/LISTS/HTML/TABLE.HTML         |
sed -e "s|###TABLE_RECORDS###|${TABLE_RECORDS}|g"           > $tmp-table-html

########################################
# 改行文字を「\\n」という3文字の文字列に置換
TABLE=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-table-html`

########################################
#tableをはめ込む、ページャーを差し込む
cat ${SYSD}/APPLI/${CATEGORY}/LISTS/HTML/SHOW.HTML              |
sed -e "s|###SET_CATEGORY_NM_PAGE###|${SET_PAGE_CATEGORY}|g"    |
sed -e "s|###SET_CATEGORY_NO_PAGE###|${SET_PAGE_CATEGORY_NO}|g" |
sed -e "s|###SET_CATEGORY###|${SET_CATEGORY_PAGE}|g"            |
sed -e "s|###TABLE###|${TABLE}|g"                               |
sed -e "s|###INFO_MSG###|"変更するセットのEDITボタンを押してください。"|g"  |
sed -e "s|###PAGER###|$(cat $tmp-pager-html)|g"                 > $tmp-html

########################################
#page name
echo "Set lists" > $tmp-pagename

########################################
echo "OK"
exit 0
