#!/bin/bash -vx
#

########################################
#	ASSESSMENT NEW CUSTOMER CONFIRM.CGI
#
#   Arg
#       $1:$$
#
#	Written by hiramatsu


########################################
#基本設定
SYSD=/home/sureshotsystem
#exec 2> $SYSD/LOG/LOG.$(basename $0).$(date +%Y%m%d).$(date +%H%M%S).$$
tmp=/tmp/tmp_$1
LANG=ja_JP.UTF-8
#PATH=/home/:/home/UTL:/usr/local/bin:/home/TOOL/open-usp-tukubai-2014061402/COMMANDS:$PATH
CATEGORY=`cat $tmp-category`
FUNC=`cat $tmp-func`
ACTION=`cat $tmp-action`

########################################
#Check error
ERROR_CHECK(){
	[ $(plus ${PIPESTATUS[@]}) -eq 0 ] && return
cat <<- FIN
	Context-type: text/html
	NG input
FIN
	cat $tmp-result
	exit 1
}

########################################
#フォーム値の設定
nameread CUSTOMER_NO $tmp-post  | awk '{gsub(/^\_$/,"",$1);print}' > $tmp-value1
nameread CUSTOMER_NM $tmp-post  | awk '{gsub(/^\_$/,"",$1);print}' > $tmp-value2
nameread CUSTOMER_PH $tmp-post  | awk '{gsub(/^\_$/,"",$1);print}' > $tmp-value3
nameread TEMP_NO $tmp-post      | awk '{gsub(/^\_$/,"",$1);print}' > $tmp-value4

########################################
#バリデーション(必須入力確認)
#入力ありの場合、空ファイルが出力され、なしの場合、そのフィールド名が記載される
cat $tmp-post | awk '$2=="_" && $1=="CSUTOMER_NO"{print $1}' > $tmp-need-VALID1
cat $tmp-post | awk '$2=="_" && $1=="CUSTOMER_NM"{print $1}' > $tmp-need-VALID2
cat $tmp-post | awk '$2=="_" && $1=="CUSTOMER_PH"{print $1}' > $tmp-need-VALID3
cat $tmp-post | awk '$2=="_" && $1=="TEMP_NO"{print $1}' > $tmp-need-VALID4

########################################
#バリデーションエラー項目の確定
if [ -n "$(cat $tmp-need-VALID1)$(cat $tmp-need-VALID2)$(cat $tmp-need-VALID3)$(cat $tmp-need-VALID4)" ] ; then 
    echo 222 > $tmp-ajax-html
else
    echo 111 > $tmp-ajax-html
fi

########################################
#顧客情報の仮登録
if [ "$(cat $tmp-ajax-html)" = 111 ]; then
    VALUE1=$(cat $tmp-value1)
    VALUE2=$(cat $tmp-value2)
    VALUE3=$(cat $tmp-value3)
    TEMPD=${SYSD}/TMP/${CATEGORY}/$(cat $tmp-value4)
    echo ${VALUE1} ${VALUE2} ${VALUE3} > ${TEMPD}/customer
fi

###############################################################################
#ending
echo "OK"
exit 0
