#!/bin/bash -vx
#

########################################
#	APPRAISAL NEW CUSTOMER COMPLETE.CGI
#
#   Arg
#       $1:$$
#
#	Written by hiramatsu


########################################
#基本設定
SYSD=$(cd $(dirname $0) && pwd | awk '{print substr($0, 0, index($0, "sureshotsystem")+13)}')
#exec 2> $SYSD/LOG/LOG.$(basename $0).$(date +%Y%m%d).$(date +%H%M%S).$$
tmp=/tmp/tmp_$1
LANG=ja_JP.UTF-8
#PATH=/home/:/home/UTL:/usr/local/bin:/home/TOOL/open-usp-tukubai-2014061402/COMMANDS:$PATH
CATEGORY=`cat $tmp-category`
FUNC=`cat $tmp-func`
ACTION=`cat $tmp-action`

########################################
#Check error
ERROR_CHECK(){
	[ $(plus ${PIPESTATUS[@]}) -eq 0 ] && return
cat <<- FIN
	Context-type: text/html
	NG input
FIN
	cat $tmp-result
	exit 1
}

########################################
#仮登録Dir :/TMP/{stuffid}/APPRAISAL/
TEMPD=${SYSD}/TMP/$(cat ${SYSD}/SESSION/$(session_get 'sureshot_stuff_session_id'))/APPRAISAL

########################################
#フォーム値の設定
nameread CUSTOMER_NO $tmp-post  | awk '{gsub(/^\_$/,"",$1);print}' > $tmp-value1
nameread CUSTOMER_NM $tmp-post  | awk '{gsub(/^\_$/,"",$1);print}' > $tmp-value2
nameread CUSTOMER_PH $tmp-post  | awk '{gsub(/^\_$/,"",$1);print}' > $tmp-value3
TEMP_NO=$(nameread TEMP_NO $tmp-post      | awk '{gsub(/^\_$/,"",$1);print}')

########################################
#ディレクトリを作成する
if [ -e "${TEMPD}"  ]; then
    :
else
    mkdir ${TEMPD}
    chmod -R 770 ${TEMPD}
    ERROR_CHECK
fi

#######################################
#TEMP_NOが取得出来なかった場合、
# 1.TEMP_NOを設定
# 2./TMP/APPRAISAL/配下にTEMP_NO/を作成
# 3.customer,parts,operationの空ファイルを作成
# 4.info msg に初期MSGを登録
# 4.customer info は空を登録
if [ -z ${TEMP_NO} ]; then
    TEMP_NO=$(date +%Y%m%d)_$(date +%H%M%S)_$RANDOM
    mkdir ${TEMPD}/${TEMP_NO}
    touch ${TEMPD}/${TEMP_NO}/customer
    touch ${TEMPD}/${TEMP_NO}/parts
    touch ${TEMPD}/${TEMP_NO}/operation
    chmod 770 ${TEMPD}/${TEMP_NO}
fi
echo ${TEMP_NO}

########################################
#バリデーション(必須入力確認)
#入力ありの場合、空ファイルが出力され、なしの場合、そのフィールド名が記載される
cat $tmp-post | awk '$2=="_" && $1=="CSUTOMER_NO"{print $1}' > $tmp-need-VALID1
cat $tmp-post | awk '$2=="_" && $1=="CUSTOMER_NM"{print $1}' > $tmp-need-VALID2
cat $tmp-post | awk '$2=="_" && $1=="CUSTOMER_PH"{print $1}' > $tmp-need-VALID3

########################################
#バリデーション
if [ -n "$(cat $tmp-need-VALID1)$(cat $tmp-need-VALID2)$(cat $tmp-need-VALID3)" ] ; then 
    echo 222 > $tmp-ajax-html
else
    echo ${TEMP_NO} > $tmp-ajax-html
fi

########################################
#顧客情報の仮登録
if [ "$(cat $tmp-ajax-html)" != 222 ]; then
    #顧客番号、顧客名、電話
    echo $(cat $tmp-value1) $(cat $tmp-value2) $(cat $tmp-value3) > ${TEMPD}/${TEMP_NO}/customer
fi

###############################################################################
#ending
echo "OK"
exit 0
