#!/bin/bash -vx
#

########################################
#	APPRAISAL NEW CUSTOMER INPUT.CGI
#
#   Arg
#       $1:$$
#
#	Written by hiramatsu


########################################
#基本設定
SYSD=$(cd $(dirname $0) && pwd | awk '{print substr($0, 0, index($0, "sureshotsystem")+13)}')
#exec 2> $SYSD/LOG/LOG.$(basename $0).$(date +%Y%m%d).$(date +%H%M%S).$$
tmp=/tmp/tmp_$1
LANG=ja_JP.UTF-8
#PATH=/home/:/home/UTL:/home/TOOL/open-usp-tukubai-2014061402/COMMANDS:$PATH
CATEGORY=`cat $tmp-category`
FUNC=`cat $tmp-func`

########################################
#Check error
ERROR_CHECK(){
	[ $(plus ${PIPESTATUS[@]}) -eq 0 ] && return
cat <<- FIN
	Context-type: text/html
	NG input
FIN
	cat $tmp-result
	exit 1
}

#######################################
#フォーム入力値を取得
MM=$REQUEST_METHOD
TEMP_NO=$(cat $tmp-get | cut -d'&' -f1 | sed s/TEMP_NO=// )

########################################
#仮登録Dir :/TMP/{stuffid}/APPRAISAL/
TEMPD=${SYSD}/TMP/$(cat ${SYSD}/SESSION/$(session_get 'sureshot_stuff_session_id'))/APPRAISAL

########################################
#ディレクトリを作成する
if [ -e "${TEMPD}"  ]; then
    :
else
    mkdir ${TEMPD}
    chmod -R 770 ${TEMPD}
    ERROR_CHECK
fi

#######################################
#TEMP_NOが取得出来なかった場合、
# 1.TEMP_NOを設定
# 2./TMP/APPRAISAL/配下にTEMP_NO/を作成
# 3.customer,parts,operationの空ファイルを作成
if [ -z ${TEMP_NO} ]; then
    TEMP_NO=$(date +%Y%m%d)_$(date +%H%M%S)_$RANDOM
    mkdir ${TEMPD}/${TEMP_NO}
    touch ${TEMPD}/${TEMP_NO}/customer
    touch ${TEMPD}/${TEMP_NO}/parts
    touch ${TEMPD}/${TEMP_NO}/operation
    chmod 770 ${TEMPD}/${TEMP_NO}
fi

########################################
#顧客情報取得
CUSTOMER_NO=$(cat ${TEMPD}/${TEMP_NO}/customer | cut -d' ' -f1)
FAMILY_NAME=$(cat ${TEMPD}/${TEMP_NO}/customer | cut -d' ' -f2)
GIVEN_NAME=$(cat ${TEMPD}/${TEMP_NO}/customer | cut -d' ' -f3)
PHONE=$(cat ${TEMPD}/${TEMP_NO}/customer | cut -d' ' -f4)

########################################
#画面情報設定:SETボタン、削除ボタン
[ -z "${CUSTOMER_NO}" ] && DISABLED_SET="" || DISABLED_SET='disabled'
[ -z "${CUSTOMER_NO}" ] && DISABLED_DEL="" || DISABLED_DEL='disabled'

########################################
#Making viweing body HTML file path
ACTION=`cat $tmp-action`
SUB_ACTION=`cat $tmp-sub-action`
cat ${SYSD}/APPLI/${CATEGORY}/${FUNC}/HTML/${ACTION}/${SUB_ACTION}.HTML |
sed -e "s/###INFO_MSG###//"                                             |
sed -e "s/###DISABLED_SET###/${DISABLED_SET}/"                          |
sed -e "s/###DISABLED_DEL###/${DISABLED_DEL}/"                          |
sed -e "s/###CUSTOMER_NO###/${CUSTOMER_NO}/"                            |
sed -e "s/###CUSTOMER_NM###/${FAMILI_NAME} ${GIVEN_NAME}/"              |
sed -e "s/###CUSTOMER_PH###/${CUSTOMER_PH}/"                            |
sed -e "s/###TEMP_NO###/${TEMP_NO}/"                                     |
sed -e "s/###DUMMY###//"                                                > $tmp-html

#########################################
#page name
echo "Appraisal customer entry" > $tmp-pagename

#########################################
##ending
echo "OK"
exit 0

