#!/bin/bash -vx
#

########################################
# SET_LIST/EDIT/CONFIRM INPUT.CGI
#
#   $1:必須 $$
#
#	Written by hiramatsu


########################################
#基本設定
export LANG=ja_JP.utf8
echo $LANG
SYSD=$(cd $(dirname $0) && pwd | awk '{print substr($0, 0, index($0, "sureshotsystem")+13)}')
#exec 2> $SYSD/LOG/LOG.$(basename $0).$(date +%Y%m%d).$(date +%H%M%S).$$
tmp=/tmp/tmp_$1
LANG=ja_JP.UTF-8
#PATH=/home/:/home/UTL:/home/TOOL/open-usp-tukubai-2014061402/COMMANDS:$PATH
CATEGORY=`cat $tmp-category`
FUNC=`cat $tmp-func`
DATAD=${SYSD}/DATA/${CATEGORY}/LISTS

#######################################
#Check error
ERROR_CHECK(){
	[ $(plus ${PIPESTATUS[@]}) -eq 0 ] && return
cat <<- FIN
	Context-type: text/html
	NG input
FIN
	cat $tmp-result
	exit 1
}

########################################
#セットのバリデーション。NGならばセットに戻す。
#RESULT=`${SYSD}/APPLI/${CATEGORY}/${FUNC}/CGI/SET/CONFIRM $1`
#if [ "${RESULT}" != 'OK' ]; then
#    echo "NG"
#    exit 0
#fi

########################################
#仮登録を削除
TEMPD=${SYSD}/TMP/$(cat ${SYSD}/SESSION/$(session_get 'sureshot_stuff_session_id'))/SET_LIST

########################################
#GETパラメータを取得
SET_CATEGORY_NO_ORG=$( cat $tmp-get | cut -d'&' -f1 | sed -e 's/SET_CATEGORY_NO_HID\=//' | ruby -r uri -ne 'print URI.unescape $_')
SET_NO=$( cat $tmp-get | cut -d'&' -f2 | sed -e 's/SET_NO_HID\=//' | ruby -r uri -ne 'print URI.unescape $_')

########################################
#セットを取得
if [ -e "${TEMPD}/setlist_base" ] ; then
  SET_EDIT_INFO="変更あり"
  SET_LABEL="label-warning"
  cat ${TEMPD}/setlist_base > $tmp-setlist-base
else
  SET_EDIT_INFO="変更なし"
  SET_LABEL="label-default"
  cat ${DATAD}/${SET_CATEGORY_NO_ORG}/LV3/${SET_NO}_setlist_base_* > $tmp-setlist-base 
fi
SET_CATEGORY_NO=$(cat $tmp-setlist-base | cut -d' ' -f2)
SET_CATEGORY_NM=$(cat $tmp-setlist-base | cut -d' ' -f3)
SET_NM=$(cat $tmp-setlist-base | cut -d' ' -f4)
SET_PRICE=$(cat $tmp-setlist-base | cut -d' ' -f5)
SET_REMARKS=$(cat $tmp-setlist-base | cut -d' ' -f6)

########################################
#作業を取得
#82 1 1 オイル交換 2 oil1 3000 1 20170613193650 20170613193650
if [ -e "${TEMPD}/setlist_operation" ] ; then
  OPE_EDIT_INFO="変更あり"
  OPE_LABEL="label-warning"
  cat ${TEMPD}/setlist_operation | sort > $tmp-setlist-operation
else  
  OPE_EDIT_INFO="変更なし"
  OPE_LABEL="label-default"
  cat ${DATAD}/${SET_CATEGORY_NO_ORG}/LV3/${SET_NO}_setlist_operation_* > $tmp-setlist-operation 
fi
cat $tmp-setlist-operation          |
juni                                |
LANG=C sort -nk1,1                  > $tmp-records-operation
mojihame -lRECORDS_OPERATION ${SYSD}/APPLI/${CATEGORY}/${FUNC}/HTML/CONFIRM/OPERATION_RECORDS.HTML $tmp-records-operation > $tmp-table-records-operation

########################################
# 改行文字を「\\n」という3文字の文字列に置換
TABLE_RECORDS_OPERATION=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-table-records-operation`

########################################
#部品を取得
#82 1 5 オイル 5 oil1 4000 2 20170613193650 20170613193650
if [ -e "${TEMPD}/setlist_parts" ] ; then
  PARTS_EDIT_INFO="変更あり"
  PARTS_LABEL="label-warning"
  cat ${TEMPD}/setlist_parts | sort > $tmp-setlist-parts
else  
  PARTS_EDIT_INFO="変更なし"
  PARTS_LABEL="label-default"
  cat ${DATAD}/${SET_CATEGORY_NO_ORG}/LV3/${SET_NO}_setlist_parts_* > $tmp-setlist-parts
fi
cat $tmp-setlist-parts              |
juni                                |
LANG=C sort -nk1,1                  > $tmp-records-parts
mojihame -lRECORDS_PARTS ${SYSD}/APPLI/${CATEGORY}/${FUNC}/HTML/CONFIRM/PARTS_RECORDS.HTML $tmp-records-parts > $tmp-table-records-parts

########################################
# 改行文字を「\\n」という3文字の文字列に置換
TABLE_RECORDS_PARTS=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-table-records-parts`

########################################
#tableにrecordsを嵌め込む
cat ${SYSD}/APPLI/${CATEGORY}/${FUNC}/HTML/CONFIRM/TABLE.HTML         |
sed -e "s|###SET_EDIT_INFO###|${SET_EDIT_INFO}|g"                     |
sed -e "s|###OPE_EDIT_INFO###|${OPE_EDIT_INFO}|g"                     |
sed -e "s|###PARTS_EDIT_INFO###|${PARTS_EDIT_INFO}|g"                 |
sed -e "s|###LABEL_SET###|${SET_LABEL}|g"                             |
sed -e "s|###LABEL_OPE###|${OPE_LABEL}|g"                             |
sed -e "s|###LABEL_PARTS###|${PARTS_LABEL}|g"                         |
sed -e "s|###SET_CATEGORY_NM###|${SET_CATEGORY_NM}|g"                 |
sed -e "s|###SET_CATEGORY_NO###|${SET_CATEGORY_NO}|g"                 |
sed -e "s|###SET_NO###|${SET_NO}|g"                                   |
sed -e "s|###SET_NM###|${SET_NM}|g"                                   |
sed -e "s|###SET_PRICE###|${SET_PRICE}|g"                             |
sed -e "s|###SET_REMARKS###|${SET_REMARKS}|g"                         |
sed -e "s|###TABLE_RECORDS_OPERATION###|${TABLE_RECORDS_OPERATION}|g" |
sed -e "s|###TABLE_RECORDS_PARTS###|${TABLE_RECORDS_PARTS}|g"         > $tmp-table-html

########################################
# 改行文字を「\\n」という3文字の文字列に置換
TABLE=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-table-html`

########################################
#tableをはめ込む、ページャーを差し込む
cat ${SYSD}/APPLI/${CATEGORY}/${FUNC}/HTML/CONFIRM/INPUT.HTML           |
sed -e "s|###INFO_MSG###|"セットに登録する内容を確認してください。"|g"  |
sed -e "s|###SET_CATEGORY_NO_ORG###|${SET_CATEGORY_NO_ORG}|g"           |
sed -e "s|###SET_NO###|${SET_NO}|g"                                     |
sed -e "s|###TABLE###|${TABLE}|g"                                       > $tmp-html

########################################
#page name
echo "Set Confirm" > $tmp-pagename

########################################
echo "OK"
exit 0
