#!/bin/bash -evx
#

########################################
#	STUFF DELETE COMPLETE.CGI
#
#   引数
#       $1:プロセスID
#
#	Written by hiramatsu


########################################
#基本設定
SYSD=$(cd $(dirname $0) && pwd | awk '{print substr($0, 0, index($0, "sureshotsystem")+13)}')
#exec 2> ${SYSD}/LOG/LOG.$(basename $0).$(date +%Y%m%d).$(date +%H%M%S).$$
tmp=/tmp/tmp_$1
LANG=ja_JP.UTF-8
PATH=/home/:/home/UTL:/home/TOOL/open-usp-tukubai-2014061402/COMMANDS:$PATH
CATEGORY=`cat $tmp-category`
FUNC=`cat $tmp-func`
LOGIND=${SYSD}/DATA/${CATEGORY}/LOGIN
USERSD=${SYSD}/DATA/${CATEGORY}/USERS
STUFF_SESS_ID='sureshot_stuff_session_id'

########################################
#Check error
ERROR_CHECK(){
	[ $(plus ${PIPESTATUS[@]}) -eq 0 ] && return
cat <<- FIN
	Context-type: text/html
	NG input
FIN
	cat $tmp-result
	exit 1
}

#######################################
#Get Form Data
ID=$(nameread ID $tmp-post)
VALUE1=$(nameread FAMILY_NAME $tmp-post)
VALUE2=$(nameread GIVEN_NAME $tmp-post)
VALUE3=$(nameread EMAIL $tmp-post)
ENC_ID=$(nameread STUFF_ID $tmp-post)

######################################
#INPUT表示時点で作成した暗号化スタッフ番号を取得し、整合性の確認を行う
#暗号化の一時ファイルは削除
STUFF_NUM=$(cat ${SYSD}/TMP/$(cat ${SYSD}/SESSION/$(session_get 'sureshot_stuff_session_id'))/${CATEGORY}/${ENC_ID})
rm -f ${SYSD}/TMP/$(cat ${SYSD}/SESSION/$(session_get 'sureshot_stuff_session_id'))/${CATEGORY}/${ENC_ID}

######################################
#スタッフIDの整合性が取れない場合、CONFIRM画面に戻す
if [ "${ID}" -ne "${STUFF_NUM}" ]; then
    cat ${SYSD}/APPLI/${CATEGORY}/${FUNC}/HTML/CONFIRM.HTML         |
    sed -e "s/###MSG###/データ不整合により処理を中止しました。/"    |
    sed -e "s/###ERROR_MSG###//"                                    |
    sed -e "s/###ID_###/${ID}/"                                     |
    sed -e "s/###FAMILY_NAME_###/${VALUE1}/"                        |
    sed -e "s/###GIVEN_NAME_###/${VALUE2}/"                         |
    sed -e "s/###EMAIL_###/${VALUE3}/"                              |
    sed -e "s/###STUFF_ID###/${ENC_ID}/"                          > $tmp-html
    exit 0
fi

########################################
#該当のSTUFFのデータ操作をロック
LOCK=`${SYSD}/CGI/LOCK/LOCK $1 'STUFF' ${STUFF_NUM}`
LOCK_STATUS=$(echo $LOCK | cut -d'.' -f4)
[ ${LOCK_STATUS} != 'LOCKED' ] && exit 0 || :

########################################
#既存データから作成日時取得、現在日時を更新日時とする
ls ${SYSD}/DATA/STUFF/USERS/LV1/${STUFF_NUM}_stuff_* | cut -d'_' -f3 | 
sort -nk1,1 | head -n 1 > $tmp-create
CREATE_DATE=$(cat $tmp-create)
UPDATE_DATE=$(date +%Y%m%d%H%M%S)

########################################
#ログインデータ用に一時ファイルに書き出し
#1.社員番号 3.EMAIL 2.PW 3.作成日時 4.更新日時 5.ADMINフラグ 6.削除フラグ
cat ${SYSD}/DATA/STUFF/LOGIN/LV1/${STUFF_NUM}_login_${CREATE_DATE}  |
awk -v update=${UPDATE_DATE} '{print $1,$2,$3,update,$5,1}'         > $tmp-login

#######################################
#ログイン用データの格納
#LV1
#原始データとlして、ファイル追加のみを行う
#削除データなのでファイル名の末尾に_dを付ける
mv $tmp-login ${LOGIND}/LV1/${STUFF_NUM}_login_${UPDATE_DATE}_d

#LV2
#ファイル名の末尾に_dを付ける
mv $(ls ${LOGIND}/LV2/${STUFF_NUM}*) $(ls ${LOGIND}/LV2/${STUFF_NUM}*)_d

#LV3
#ファイル名の末尾に_dを付ける
mv $(ls ${LOGIND}/LV3/${STUFF_NUM}*) $(ls ${LOGIND}/LV3/${STUFF_NUM}*)_d

########################################
#ユーザーデータ用に一時ファイルに書き出し
#1.社員番号 2.姓 3.名 4.EMAIL 5.TEL 6.作成日時 7.更新日時 8.ADMINフラグ 9.削除フラグ
cat ${SYSD}/DATA/STUFF/USERS/LV1/${STUFF_NUM}_stuff_${CREATE_DATE} |
awk -v update=${UPDATE_DATE} '{print $1,$2,$3,$4,$5,$6,update,$8,1}' > $tmp-stuff

########################################
#スタッフ用データの格納
#LV1
#原始データとして、ファイル追加のみを行う
#削除データなのでファイル名の末尾に_dを付ける
mv $tmp-stuff ${USERSD}/LV1/${STUFF_NUM}_stuff_${UPDATE_DATE}_d

#LV2
#ファイル名の末尾に_dを付ける
mv $(ls ${USERSD}/LV2/${STUFF_NUM}*) $(ls ${USERSD}/LV2/${STUFF_NUM}*)_d

#LV3
#ファイル名の末尾に_dを付ける
mv $(ls ${USERSD}/LV3/${STUFF_NUM}*) $(ls ${USERSD}/LV3/${STUFF_NUM}*)_d

########################################
#STUFFのデータ操作ロックを解除
UNLOCK_STATUS=`${SYSD}/CGI/LOCK/UNLOCK $1 'STUFF' ${STUFF_NUM}`
[ ${UNLOCK_STATUS} != 'UNLOCK'] && exit 0 || :

########################################
#SET SESSION
COOK=`${SYSD}/CGI/SESSION/SESSION_SET ${STUFF_SESS_ID} `
echo $COOK > $tmp-cook

########################################
#HTMLの設定
ACTION=`cat $tmp-action`
cat ${SYSD}/APPLI/${CATEGORY}/${FUNC}/HTML/${ACTION}.HTML   |
sed -e "s/###ID_LABEL###/${ID}/"                            |
sed -e "s/###FAMILY_NAME_LABEL###/${VALUE1}/"               |
sed -e "s/###GIVEN_NAME_LABEL###/${VALUE2}/"                |
sed -e "s/###EMAIL_LABEL###/${VALUE3}/"                     > $tmp-html

#########################################
#page name
echo "Stuff delete complete" > $tmp-pagename

###############################################################################
#ending
echo "stuff edit OK"
exit 0
