#!/bin/bash -vx
#

########################################
#	STUFF DELETE CONFIRM.CGI
#
#   引数
#       $1:必須 $$
#
#	Written by hiramatsu


########################################
#基本設定
SYSD=/home/sureshotsystem
#exec 2> $SYSD/LOG/LOG.$(basename $0).$(date +%Y%m%d).$(date +%H%M%S).$$
tmp=/tmp/tmp_$1
LANG=ja_JP.UTF-8
PATH=/home/:/home/UTL:/usr/local/bin:/home/TOOL/open-usp-tukubai-2014061402/COMMANDS:$PATH
CATEGORY=`cat $tmp-category`
FUNC=`cat $tmp-func`

########################################
#Check error
ERROR_CHECK(){
	[ $(plus ${PIPESTATUS[@]}) -eq 0 ] && return
cat <<- FIN
	Context-type: text/html
	NG input
FIN
	cat $tmp-result
	exit 1
}

########################################
#Get STUFF ID
nameread STUFF_ID $tmp-post              | awk '{gsub(/^\_$/,"",$1);print}' > $tmp-stuff
STUFF_ID=$(cat $tmp-stuff)

########################################
#フォーム値の設定
nameread ID $tmp-post              | awk '{gsub(/^\_$/,"",$1);print}' > $tmp-value1
nameread FAMILY_NAME $tmp-post              | awk '{gsub(/^\_$/,"",$1);print}' > $tmp-value2
nameread GIVEN_NAME $tmp-post               | awk '{gsub(/^\_$/,"",$1);print}' > $tmp-value3
nameread EMAIL $tmp-post                    | awk '{gsub(/^\_$/,"",$1);print}' > $tmp-value4

########################################
#社員番号一致確認
ID=$( ${SYSD}/DATA/${CATEGORY}/TMP/${STUFF_ID} )
[ -z ${ID} ] && ACTION=INPUT || ACTION=COMPLETE

########################################
#HTMLの設定
if [ $ACTION = 'INPUT' ] ; then
    cat ${SYSD}/APPLI/${CATEGORY}/${FUNC}/HTML/${ACTION}.HTML   |
    sed -e "s/###DELETE_ERR###//"                               |
    sed -e "s/###STUFF_ID_VALUE###/$(cat $tmp-value1)/"      |
    sed -e "s/###FAMILY_NAME_VALUE###/$(cat $tmp-value2)/"      |
    sed -e "s/###GIVEN_NAME_VALUE###/$(cat $tmp-value3)/"       |
    sed -e "s/###EMAIL_VALUE###/$(cat $tmp-value4)/"            > $tmp-html
else
    RESULT=$( ${SYSD}/APPLI/${CATEGORY}/${FUNC}/CGI/${ACTION} $1)

    cat ${SYSD}/APPLI/${CATEGORY}/${FUNC}/HTML/${ACTION}.HTML   |
    sed -e "s/###STUFF_ID_VALUE###/$(cat $tmp-value1)/"      |
    sed -e "s/###FAMILY_NAME_VALUE###/$(cat $tmp-value2)/"      |
    sed -e "s/###GIVEN_NAME_VALUE###/$(cat $tmp-value3)/"       |
    sed -e "s/###EMAIL_###/$(cat $tmp-value4)/"                 > $tmp-html
fi

###############################################################################
#ending
echo "OK"
exit 0



