#!/bin/bash -evx
#

########################################
#	SET_LIST/EDIT COMPLETE.CGI
#
#   引数
#       $1:プロセスID
#
#	Written by hiramatsu


########################################
#基本設定
SYSD=$(cd $(dirname $0) && pwd | awk '{print substr($0, 0, index($0, "sureshotsystem")+13)}')
#exec 2> ${SYSD}/LOG/LOG.$(basename $0).$(date +%Y%m%d).$(date +%H%M%S).$$
tmp=/tmp/tmp_$1
LANG=ja_JP.UTF-8
#PATH=/home/:/home/UTL:/home/TOOL/open-usp-tukubai-2014061402/COMMANDS:$PATH
CATEGORY=`cat $tmp-category`
FUNC=`cat $tmp-func`

########################################
#Check error
ERROR_CHECK(){
	[ $(plus ${PIPESTATUS[@]}) -eq 0 ] && return
cat <<- FIN
	Context-type: text/html
	NG input
FIN
	cat $tmp-result
	exit 1
}

########################################
#セットカテゴリ更新中は、処理をさせない
#ls ${SYSD}/LOCK/SET_CATEGORY/* > $tmp-checker 2> /dev/null
#if [ -n cat $tmp-checker ] ; then
#    echo "333" > $tmp-ajax-html
#    exit 0
#fi

########################################
#仮登録を削除
TEMPD=${SYSD}/TMP/$(cat ${SYSD}/SESSION/$(session_get 'sureshot_stuff_session_id'))/SET_LIST

########################################
#変更確認
if [ -n "$(cat ${TEMPD}/setlist_*)" ]; then
  :
else
  echo 2222 > $tmp-ajax-html
  exit 0
fi

#######################################
#フォームの入力値を取得
ROW=$(nameread ROW $tmp-post)
NUM=$(nameread SET_NO $tmp-post)
SET_CATEGORY_NX=$(nameread SET_CATEGORY_NX $tmp-post)
SET_CATEGORY_NO=$(nameread SET_CATEGORY_NO $tmp-post)

########################################
#DATAディレクトリ
DATAD_OLD=${SYSD}/DATA/${CATEGORY}/LISTS/${SET_CATEGORY_NX}
DATAD_NEW=${SYSD}/DATA/${CATEGORY}/LISTS/${SET_CATEGORY_NO}
[ "${DATAD_OLD}" = "${DATAD_NEW}" ] && DATAD=${DATAD_OLD} || DATAD=${DATAD_NEW} 

#######################################
#セット変更内容を取得
if [ -e "${TEMPD}/setlist_base" ] ; then
  #82 2 タイヤ交換 Oil_Filter交換-TTT 30000 S123 
  SET_CATEGORY_NM=$( cat ${TEMPD}/setlist_base | cut -d' ' -f3)
  SET_NM=$( cat ${TEMPD}/setlist_base | cut -d' ' -f4)
  SET_PRICE=$( cat ${TEMPD}/setlist_base | cut -d' ' -f5)
  SET_REMARKS=$( cat ${TEMPD}/setlist_base | cut -d' ' -f6)
  echo ${NUM} ${SET_CATEGORY_NO} ${SET_CATEGORY_NM} ${SET_NM} ${SET_PRICE} ${SET_REMARKS} > $tmp-setlist-base
else
  #最新LV1データ
  cat `ls ${DATAD_OLD}/LV1/${NUM}_setlist_base_*[^_d] | sort -nr | head -n1` > $tmp-setlist-base
fi

#######################################
#作業変更内容を取得
if [ -e "${TEMPD}/setlist_operation" ] ; then
  cat ${TEMPD}/setlist_operation > $tmp-setlist-operation
else
  #既存最新LV1データ
  cat `ls ${DATAD_OLD}/LV1/${NUM}_setlist_operation_*[^_d] | sort -nr | head -n1` > $tmp-setlist-operation
fi

#######################################
#部品変更内容を取得
if [ -e "${TEMPD}/setlist_parts" ] ; then
  cat ${TEMPD}/setlist_parts > $tmp-setlist-parts
else
  #既存最新LV1データ
  cat `ls ${DATAD_OLD}/LV1/${NUM}_setlist_parts_*[^_d] | sort -nr | head -n1` > $tmp-setlist-parts
fi

########################################
#既存データから作成日時取得、現在日時を更新日時とする
ls ${DATAD_OLD}/LV1/${SET_NO}_setlist_base_* | cut -d'_' -f4 | sort -nk1,1 | head -n 1 > $tmp-create
CREATE_DATE=$(cat $tmp-create)
UPDATE_DATE=$(date +%Y%m%d%H%M%S)

########################################
#未使用のセットカテゴリが選択された場合、ディレクトリを作成する
if [ -e "${DATAD_NEW}"  ]; then
    :
else
    mkdir ${DATAD_NEW}
    cp -rp ${SYSD}/DATA/ORG_LV1-3/* ${DATAD_NEW}/
    chmod -R 770 ${DATAD_NEW} #オーナーと権限を再帰的に設定
    ERROR_CHECK
fi

#######################################
#データ格納
#LV1:原始データとして、ファイル追加のみを行う
mv $tmp-setlist-base      ${DATAD}/LV1/${NUM}_setlist_base_${UPDATE_DATE}
mv $tmp-setlist-operation ${DATAD}/LV1/${NUM}_setlist_operation_${UPDATE_DATE}
mv $tmp-setlist-parts     ${DATAD}/LV1/${NUM}_setlist_parts_${UPDATE_DATE}
#LV2:LV1更新ファイルと入れ替え
rm -f ${DATAD_OLD}/LV2/${NUM}_setlist_*
cp -fp ${DATAD}/LV1/${NUM}_setlist_*_${UPDATE_DATE} ${DATAD}/LV2/
#LV3:LV2更新ファイルと入れ替え
rm -f ${DATAD_OLD}/LV3/${NUM}_setlist_base_*
cp -fp ${DATAD}/LV2/${NUM}_setlist_*_${UPDATE_DATE} ${DATAD}/LV3/

#######################################
#仮登録セットリストを削除
rm -rf ${TEMPD}

########################################
#ending
echo "OK"
exit 0
