#!/bin/bash -vx
#

########################################
#	SHOW.CGI
#
#   $1:必須 $$
#
#	Written by hiramatsu


########################################
#基本設定
SYSD=$(cd $(dirname $0) && pwd | awk '{print substr($0, 0, index($0, "sureshotsystem")+13)}')
#exec 2> $SYSD/LOG/LOG.$(basename $0).$(date +%Y%m%d).$(date +%H%M%S).$$
tmp=/tmp/tmp_$1
LANG=ja_JP.UTF-8
#PATH=/home/:/home/UTL:/home/TOOL/open-usp-tukubai-2014061402/COMMANDS:$PATH
CATEGORY=`cat $tmp-category`
FUNC=`cat $tmp-func`
ACTION=`cat $tmp-action`

#######################################
#Check error
ERROR_CHECK(){
	[ $(plus ${PIPESTATUS[@]}) -eq 0 ] && return
cat <<- FIN
	Context-type: text/html
	NG input
FIN
	cat $tmp-result
	exit 1
}

#######################################
#最大表示レコード数設定ファイルの確認
if [ -e ${SYSD}/SYS/VIEW/${CATEGORY}/${FUNC}/VIEW_MAX_RECORDS ]; then
    :
else    
    result=`${SYSD}/CGI/DATA/DFS_NEW $$ ${SYSD}/SYS/VIEW/${CATEGORY}/${FUNC} `
    cp ${SYSD}/SYS/VIEW/ORG_VIEW_MAX/VIEW_MAX_RECORDS ${SYSD}/SYS/VIEW/${CATEGORY}/${FUNC}/
    cp ${SYSD}/SYS/VIEW/ORG_VIEW_MAX/VIEW_MAX_PAGES ${SYSD}/SYS/VIEW/${CATEGORY}/${FUNC}/
fi

########################################
#最大表示レコード数
cat ${SYSD}/SYS/VIEW/${CATEGORY}/${FUNC}/VIEW_MAX_RECORDS | 
awk '{print $2}' > $tmp-max-records
VIEW_MAX_RECORDS=$( cat $tmp-max-records )

########################################
#最大表示ページ数
cat ${SYSD}/SYS/VIEW/${CATEGORY}/${FUNC}/VIEW_MAX_PAGES | 
awk '{print $2}' > $tmp-max-pages
VIEW_MAX_PAGES=$( cat $tmp-max-pages )

########################################
#Get querystring
#GETパラメータの順番は、action,pageの順番が前提
QRY_PAGE=$(cat $tmp-get | awk '{split($0,ary,"&"); print ary[2]}' | sed 's/page\=//')

########################################
#Set record start & end
if [ -z $(echo ${QRY_PAGE}) ]; then
    SHOW_PAGE=1
    START=1
    END=${VIEW_MAX_RECORDS}
else
    SHOW_PAGE=${QRY_PAGE}
    END=$(expr ${QRY_PAGE} \* ${VIEW_MAX_RECORDS} )
    START=$(expr ${END} - ${VIEW_MAX_RECORDS} + 1 )
fi

########################################
#Get stuff records
#dレコードとSystemユーザーは非表示
cat ${SYSD}/DATA/${CATEGORY}/USERS/LV3/[^0]*[^_d]   |
LANG=C sort -nk1,1                                  |
awk -v s=${START} -v e=${END} 'NR>=s&&NR<=e&&$9!=1' |
juni                                                > $tmp-records-base

########################################
#EMAIL DEDODE
resutlt=`aes128-decode ${SYSD}/DATA/STUFF/ACCOUNTS $1 $tmp-email-decode`

########################################
#DecodeしたEmailをJOIN
cat $tmp-records-base | sort -k5 > $tmp-records-base-sort
cat $tmp-email-decode | sort -k1 > $tmp-email-decode-sort
join -1 5 -2 1 $tmp-records-base-sort $tmp-email-decode-sort | awk '{$1="";$6=$NF;$NF="";print}' | sort -nk1 > $tmp-records

# 1;社員番号 2;姓 3:名 4:email
mojihame -lRECORDS ${SYSD}/APPLI/${CATEGORY}/${FUNC}/HTML/${ACTION}.HTML $tmp-records > $tmp-template-html

########################################
#Set pager
RECORDS=$( ls ${SYSD}/DATA/${CATEGORY}/USERS/LV3/*[^_d] | wc -l )
RESULT=`${SYSD}/CGI/PAGINATION/PAGER $1 /APP/STUFF/USERS ${SHOW_PAGE} ${RECORDS} ${VIEW_MAX_RECORDS} ${VIEW_MAX_PAGES}`

########################################
#Making viweing body HTML filw path
cat $tmp-template-html                          |
sed -e "s/###INFO_MSG###//"                     |
sed -e "s|###PAGER###|$(cat $tmp-pager-html)|g" > $tmp-html

#########################################
#page name
echo "Stuff lists" > $tmp-pagename

#########################################
##ending
echo "OK"
exit 0

