#!/bin/bash -evx
#

########################################
#	SET_LIST/NEW/PARTS/COMPLETE.CGI
#
#   引数
#       $1:プロセスID
#
#	Written by hiramatsu


########################################
#基本設定
SYSD=$(cd $(dirname $0) && pwd | awk '{print substr($0, 0, index($0, "sureshotsystem")+13)}')
#exec 2> ${SYSD}/LOG/LOG.$(basename $0).$(date +%Y%m%d).$(date +%H%M%S).$$
tmp=/tmp/tmp_$1
LANG=ja_JP.UTF-8
#PATH=/home/:/home/UTL:/home/TOOL/open-usp-tukubai-2014061402/COMMANDS:$PATH
CATEGORY=`cat $tmp-category`
FUNC=`cat $tmp-func`

########################################
#Check error
ERROR_CHECK(){
	[ $(plus ${PIPESTATUS[@]}) -eq 0 ] && return
cat <<- FIN
	Context-type: text/html
	NG input
FIN
	cat $tmp-result
	exit 1
}

########################################
#パーツカテゴリ更新中は、処理をさせない
#ls ${SYSD}/LOCK/PARTS_CATEGORY/* > $tmp-checker 2> /dev/null
#if [ -n cat $tmp-checker ] ; then
#    echo "333" > $tmp-ajax-html
#    exit 0
#fi

########################################
#仮登録ディレクトリ
TEMPD=${SYSD}/TMP/$(cat ${SYSD}/SESSION/$(session_get 'sureshot_stuff_session_id'))/SET_LIST

#######################################
#フォームの入力値を取得
ACTION=$(nameread ACTION $tmp-post)
ROW=$(nameread ROW $tmp-post)
NUM=$(nameread SET_NO $tmp-post)
SET_CATEGORY_NO=$(nameread SET_CATEGORY_NO $tmp-post)
PARTS_CATEGORY_NO=$(nameread PARTS_CATEGORY_NO $tmp-post)
PARTS_CATEGORY_NM=$(nameread PARTS_CATEGORY_NM $tmp-post)
PARTS_NO=$(nameread PARTS_NO $tmp-post)
PARTS_NM=$(nameread PARTS_NM $tmp-post)
PARTS_NM_NX=$(nameread PARTS_NM_NX $tmp-post)
PARTS_PRICE=$(nameread PARTS_PRICE $tmp-post)
PARTS_QTY=$(nameread PARTS_QTY $tmp-post)

########################################
#DATAディレクトリ
DATAD=${SYSD}/DATA/${CATEGORY}/LISTS/${SET_CATEGORY_NO}

########################################
#部品を取得
#セット番号、セットカテゴリ番号、部品カテゴリ番号、部品カテゴリ名、部品番号、部品名、部品価格、作成日、更新日
if [ -e "${TEMPD}/setlist_parts" ]; then
  cat ${TEMPD}/setlist_parts > $tmp-set-parts-tmp
else
  cat ${DATAD}/LV3/${NUM}_setlist_parts_*  > $tmp-set-parts-tmp
fi

########################################
#重複確認
if [ "${PARTS_NM}" != "${PARTS_NM_NX}" ] ; then
  cat $tmp-set-parts-tmp                    | 
  awk -v nm=${PARTS_NM} '$6==nm{print $1}'  > $tmp-valid1
  if [ -n "$(cat $tmp-valid1)" ] ; then
    echo 2222 > $tmp-ajax-html
    exit 0
  fi
fi

########################################
#既存データから作成日時取得、現在日時を更新日時とする
ls ${DATAD}/LV1/${NUM}_setlist_parts_* | sort -nk1,1 | head -n 1 | cut -d'_' -f5 > $tmp-create
CREATE_DATE=$(cat $tmp-create)
UPDATE_DATE=$(date +%Y%m%d%H%M%S)

######################################t#
#ACTIONで振り分け
case ${ACTION} in
ADD)
  #追加
  #82 1 5 オイル 5 oil1 4000 2 20170613193650 20170613193650
  echo  ${NUM} ${SET_CATEGORY_NO} \
        ${PARTS_CATEGORY_NO} ${PARTS_CATEGORY_NM} \
        ${PARTS_NO} ${PARTS_NM} \
        ${PARTS_PRICE} ${PARTS_QTY} \
        ${CREATE_DATE} ${UPDATE_DATE} \
        >> $tmp-set-parts-tmp
  cat $tmp-set-parts-tmp > $tmp-set-parts
 ;;
EDIT)   #変更
  cat $tmp-set-parts-tmp  | 
  awk \
      -v row=${ROW} \
      -v set_no=${NUM} \
      -v set_cate_no=${SET_CATEGORY_NO} \
      -v ps_cate_no=${PARTS_CATEGORY_NO} \
      -v ps_cate_nm=${PARTS_CATEGORY_NM} \
      -v ps_no=${PARTS_NO} \
      -v ps_nm=${PARTS_NM} \
      -v price=${PARTS_PRICE} \
      -v qty=${PARTS_QTY} \
      -v cdt=${CREATE_DATE} \
      -v udt=${UPDATE_DATE} \
      'NR!=row{print} \
      NR==row{print( \
          set_no, \
          set_cate_no, \
          ps_cate_no, \
          ps_cate_nm, \
          ps_no, \
          ps_nm, \
          price, \
          qty, \
          cdt, \
          udt \
      )}' \
      > $tmp-set-parts
  ;;
DELETE) #削除
  cat $tmp-set-parts-tmp          | 
  awk -v d=${ROW} 'NR!=d{print}'  > $tmp-set-parts
  ;;
esac

########################################
#仮登録を作成
rm -f ${TEMPD}/setlist_parts
cat $tmp-set-parts > ${TEMPD}/setlist_parts

########################################
#部品カテゴリを取得
cat ${SYSD}/DATA/PARTS_CATEGORY/LISTS/LV3/*[^_d]    |
LANG=C sort -nk1,1                                  > $tmp-parts-category

########################################
#部品新規登録用の部品カテゴリ
# 1;カテゴリ番号 2;カテゴリ名
mojihame -lRECORDS ${SYSD}/APPLI/${CATEGORY}/${FUNC}/HTML/PARTS/PARTS_CATEGORY_NEW.HTML $tmp-parts-category > $tmp-parts-category-new

########################################
#カテゴリの改行文字を「\\n」という3文字の文字列に置換
CATEGORY_NEW=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-parts-category-new`

########################################
#部品レコード用の部品カテゴリ
# 1;カテゴリ番号 2;カテゴリ名
mojihame -lRECORDS ${SYSD}/APPLI/${CATEGORY}/${FUNC}/HTML/PARTS/PARTS_CATEGORY_LIST.HTML $tmp-parts-category > $tmp-parts-category-list

########################################
#部品カテゴリの改行文字を「\\n」という3文字の文字列に置換
CATEGORY_LIST=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-parts-category-list`

########################################
#仮登録の部品リストを取得
cat $tmp-set-parts         |
juni                       |                
LANG=C sort -nk1,1         > $tmp-records
mojihame -lRECORDS ${SYSD}/APPLI/${CATEGORY}/${FUNC}/HTML/PARTS/RECORDS.HTML $tmp-records > $tmp-table-records
cat $tmp-table-records | sed -e "s|###CATEGORY###|${CATEGORY_LIST}|g" > $tmp-table-records2

########################################
# 改行文字を「\\n」という3文字の文字列に置換
TABLE_RECORDS=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-table-records2`

########################################
#tableにrecordsを嵌め込む
cat ${SYSD}/APPLI/${CATEGORY}/${FUNC}/HTML/PARTS/TABLE.HTML |
sed -e "s|###CATEGORY###|${CATEGORY_NEW}|g"                 |
sed -e "s|###TABLE_RECORDS###|${TABLE_RECORDS}|g"           > $tmp-ajax-html

########################################
#ending
echo "OK"
exit 0
