#!/bin/bash -vx
#

########################################
# SET_LIST/EDIT/PARTS INPUT.CGI
#
#   $1:必須 $$
#
#	Written by hiramatsu


########################################
#基本設定
export LANG=ja_JP.utf8
echo $LANG
SYSD=$(cd $(dirname $0) && pwd | awk '{print substr($0, 0, index($0, "sureshotsystem")+13)}')
#exec 2> $SYSD/LOG/LOG.$(basename $0).$(date +%Y%m%d).$(date +%H%M%S).$$
tmp=/tmp/tmp_$1
LANG=ja_JP.UTF-8
#PATH=/home/:/home/UTL:/home/TOOL/open-usp-tukubai-2014061402/COMMANDS:$PATH
CATEGORY=`cat $tmp-category`
FUNC=`cat $tmp-func`
DATAD=${SYSD}/DATA/${CATEGORY}/LISTS

#######################################
#Check error
ERROR_CHECK(){
	[ $(plus ${PIPESTATUS[@]}) -eq 0 ] && return
cat <<- FIN
	Context-type: text/html
	NG input
FIN
	cat $tmp-result
	exit 1
}

########################################
#仮登録Dir
TEMPD=${SYSD}/TMP/$(cat ${SYSD}/SESSION/$(session_get 'sureshot_stuff_session_id'))/SET_LIST

########################################
#GETパラメータを取得
SET_CATEGORY_NO_ORG=$( cat $tmp-get | cut -d'&' -f1 | sed -e 's/SET_CATEGORY_NO_HID\=//' | ruby -r uri -ne 'print URI.unescape $_')
SET_NO=$( cat $tmp-get | cut -d'&' -f2 | sed -e 's/SET_NO_HID\=//' | ruby -r uri -ne 'print URI.unescape $_')

########################################
#部品カテゴリを取得
cat ${SYSD}/DATA/PARTS_CATEGORY/LISTS/LV3/*[^_d]    |
LANG=C sort -nk1,1                                      > $tmp-parts-category

########################################
#部品新規登録用の部品カテゴリ
# 1;カテゴリ番号 2;カテゴリ名
mojihame -lRECORDS ${SYSD}/APPLI/${CATEGORY}/${FUNC}/HTML/PARTS/PARTS_CATEGORY_NEW.HTML $tmp-parts-category > $tmp-parts-category-new

########################################
# セットカテゴリの改行文字を「\\n」という3文字の文字列に置換
CATEGORY_NEW=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-parts-category-new`

########################################
#部品レコード用の部品カテゴリ
# 1;カテゴリ番号 2;カテゴリ名
mojihame -lRECORDS ${SYSD}/APPLI/${CATEGORY}/${FUNC}/HTML/PARTS/PARTS_CATEGORY_LIST.HTML $tmp-parts-category > $tmp-parts-category-list

########################################
#部品カテゴリの改行文字を「\\n」という3文字の文字列に置換
CATEGORY_LIST=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-parts-category-list`

########################################
#Get records
if [ -e "${TEMPD}/setlist_parts" ]; then
  cat ${TEMPD}/setlist_parts > $tmp-set-parts
else
  #82 1 5 オイル 5 oil1 4000 2 20170613193650 20170613193650
  cat ${DATAD}/${SET_CATEGORY_NO_ORG}/LV3/${SET_NO}_setlist_parts_* > $tmp-set-parts
fi

########################################
#部品をテーブルへ
cat $tmp-set-parts    |
juni                  |
LANG=C sort -nk1,1    > $tmp-records
mojihame -lRECORDS ${SYSD}/APPLI/${CATEGORY}/${FUNC}/HTML/PARTS/RECORDS.HTML $tmp-records > $tmp-table-records

########################################
# 改行文字を「\\n」という3文字の文字列に置換
TABLE_RECORDS=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-table-records`

########################################
#tableにrecordsを嵌め込む
cat ${SYSD}/APPLI/${CATEGORY}/${FUNC}/HTML/PARTS/TABLE.HTML     |
sed -e "s|###TABLE_RECORDS###|${TABLE_RECORDS}|g"               |
sed -e "s|###CATEGORY###|${CATEGORY_NEW}|g"                     > $tmp-table-html

########################################
# 改行文字を「\\n」という3文字の文字列に置換
TABLE=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-table-html`

########################################
#tableをはめ込む、ページャーを差し込む
cat ${SYSD}/APPLI/${CATEGORY}/${FUNC}/HTML/PARTS/INPUT.HTML             |
sed -e "s|###INFO_MSG###|"セットに登録する部品を追加してください。"|g"  |
sed -e "s|###SET_CATEGORY_NO_ORG###|${SET_CATEGORY_NO_ORG}|g"           |
sed -e "s|###SET_NO###|${SET_NO}|g"                                     |
sed -e "s|###TABLE###|${TABLE}|g"                                       > $tmp-html

########################################
#page name
echo "Set Parts edit" > $tmp-pagename

########################################
echo "OK"
exit 0
