#!/bin/bash -evx
#

########################################
#	OUT.CGI
##
#       $1:session_id
#       $2:session lifetime (default 15min)
#
#	Written by hiramatsu


########################################
#Set basic
SYSD=/home/sureshotsystem
#exec 2> ${SYSD}/LOG/LOG.$(basename $0).$(date +%Y%m%d).$(date +%H%M%S).$$
tmp=/tmp/tmp_$1
LANG=ja_JP.UTF-8
PATH=/home/:/home/UTL:/usr/local/bin:/home/TOOL/open-usp-tukubai-2014061402/COMMANDS:$PATH
SESSION_FILED=${SYSD}/SESSION
EMP_SESS_ID='ss_employee_session_id'

########################################
#Check error
ERROR_CHECK(){
	[ $(plus ${PIPESTATUS[@]}) -eq 0 ] && return
cat <<- FIN
	Context-type: text/html
	NG input
FIN
	cat $tmp-result
	exit 1
}

########################################
#Make cookie words for session
COOK=`${SYSD}/CGI/SESSION/SESSION_SET ${EMP_SESS_ID} -2000`
echo $COOK > $tmp-cook
ERROR_CHECK

#######################################
#Get session
SESS=$(session_get ${EMP_SESS_ID})
ERROR_CHECK

########################################
#Delete session file
rm -f "${SESSION_FILED}/${SESS}"
ERROR_CHECK

#######################################
#HTMLの設定
cat ${SYSD}/HTML/index.html > $tmp-html 

#######################################
#ending
echo "OK"
exit 0



