#!/bin/bash
#

########################################
#	NUMBER.CGI
#
#   引数
#       $1:プロセスID
#
#	Written by hiramatsu


########################################
#基本設定
SYSD=$(cd $(dirname $0) && pwd | awk '{print substr($0, 0, index($0, "sureshotsystem")+13)}')
#exec 2> ${SYSD}/LOG/LOG.$(basename $0).$(date +%Y%m%d).$(date +%H%M%S).$$
tmp=/tmp/tmp_$1
LANG=ja_JP.UTF-8
#PATH=/home/:/home/UTL:/home/TOOL/open-usp-tukubai-2014061402/COMMANDS:$PATH
NUMBERSD=${SYSD}/DATA/NUMBERS/$2

########################################
#Check error
ERROR_CHECK(){
	[ $(plus ${PIPESTATUS[@]}) -eq 0 ] && return
    [ -z ${STATUS} ] && STATUS='LOCK_ERROR'
    cat ${SYSD}/HTML/ERROR/SYSTEM_ERROR.HTML                        |
    sed -e "s/###ERROR1_LABEL###/採番処理中にエラー/"               |
    sed -e "s/###ERROR2_LABEL###/${NUMBERSD}/"                      |
    sed -e "s|###ERROR3_LABEL###||"                                 |
    sed -e "s/###ERROR4_LABEL###//"                                 |
    sed -e "s/###ERROR5_LABEL###//"                                 > $tmp-html
    echo "ERROR"
    exit 2
}

########################################
#Args

CATEGORY=$(cat $tmp-category)

########################################
#カテゴリ番号の次のロットを追加する
LATEST_NUM=$(ls ${SYSD}/DATA/NUMBERS/${CATEGORY}/ORIGIN | sort -nr | head -n 1)
START=$((LATEST_NUM + 1))
END=$((START + 3))
SEQ_STATUS=`${SYSD}/CGI/NUMBER/NUMBER_SEQ $1 ${CATEGORY} ${START} ${END} `

########################################
#新規カテゴリ番号を確定する
NEW_NUM=`${SYSD}/CGI/NUMBER/NUMBERS $1 ${CATEGORY} `
echo ${NEW_NUM}

ERROR_CHECK

########################################
#正常終了
exit 0
