#!/bin/bash -vx
#

########################################
#	CUSTOMER NEW CONFIRM.CGI
#
#   Arg
#       $1:$$
#
#	Written by hiramatsu


########################################
#基本設定
SYSD=$(cd $(dirname $0) && pwd | awk '{print substr($0, 0, index($0, "sureshotsystem")+13)}')
#exec 2> $SYSD/LOG/LOG.$(basename $0).$(date +%Y%m%d).$(date +%H%M%S).$$
tmp=/tmp/tmp_$1
LANG=ja_JP.UTF-8
#PATH=/home/:/home/UTL:/usr/local/bin:/home/TOOL/open-usp-tukubai-2014061402/COMMANDS:$PATH
CATEGORY=`cat $tmp-category`
FUNC=`cat $tmp-func`
DATAD=${SYSD}/DATA/${CATEGORY}/LISTS

########################################
#Check error
ERROR_CHECK(){
	[ $(plus ${PIPESTATUS[@]}) -eq 0 ] && return
cat <<- FIN
	Context-type: text/html
	NG input
FIN
	cat $tmp-result
	exit 1
}

#######################################
#フォーム入力値を取得
TEMP_NO=$(cat $tmp-get | cut -d'&' -f1 | sed s/TEMP_NO=// )

########################################
#仮登録Dir
TEMPD=${SYSD}/TMP/$(cat ${SYSD}/SESSION/$(session_get 'sureshot_stuff_session_id'))/APPRAISAL/${TEMP_NO}

########################################
#Customerを取得
CUSTOMER_NO=$(cat ${TEMPD}/customer | cut -d' ' -f1)
CUSTOMER_NM=$(cat ${TEMPD}/customer | cut -d' ' -f2)
CUSTOMER_PH=$(cat ${TEMPD}/customer | cut -d' ' -f3)

#######################################
#TEMP_NOが取得出来なかった場合-->異常
if [ -z ${TEMP_NO} ]; then
  #CUSTOMER INPUTへ戻す
  REDIRECT_FORCE="/APP/APPRAISAL/NEW/CUSTOMER/INPUT"
else
  #ヘッダーインフォ設定
  INFO_MSG="見積内容を確認してください。"    
  APPRAISAL_INFO="査定番号 : "${TEMP_NO}  
  CUSTOMER_INFO="お客様 : "`echo ${CUSTOMER_NO} / ${CUSTOMER_NM} / ${CUSTOMER_PH}`
fi

########################################
#作業を取得
#1 オイル交換 2 oil1 3000 1
if [ -e "${TEMPD}/operation" ] ; then
  OPE_INFO="見積あり"
  OPE_LABEL="label-warning"
  cat ${TEMPD}/operation | sort > $tmp-operation
else  
  OPE_INFO="見積なし"
  OPE_LABEL="label-default"
fi
cat $tmp-operation    |
juni                  |
LANG=C sort -nk1,1    > $tmp-records-operation
mojihame -lRECORDS ${SYSD}/APPLI/${CATEGORY}/${FUNC}/HTML/CONFIRM/OPERATION_RECORDS.HTML $tmp-records-operation > $tmp-table-records-operation

########################################
# 改行文字を「\\n」という3文字の文字列に置換
TABLE_RECORDS_OPERATION=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-table-records-operation`

########################################
#部品を取得
#5 オイル 5 oil1 4000 2
if [ -e "${TEMPD}/parts" ] ; then
  PARTS_INFO="見積あり"
  PARTS_LABEL="label-warning"
  cat ${TEMPD}/parts | sort > $tmp-parts
else  
  PARTS_INFO="見積なし"
  PARTS_LABEL="label-default"
fi
cat $tmp-parts        |
juni                  |
LANG=C sort -nk1,1    > $tmp-records-parts
mojihame -lRECORDS ${SYSD}/APPLI/${CATEGORY}/${FUNC}/HTML/CONFIRM/PARTS_RECORDS.HTML $tmp-records-parts > $tmp-table-records-parts

########################################
# 改行文字を「\\n」という3文字の文字列に置換
TABLE_RECORDS_PARTS=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-table-records-parts`

########################################
#tableにrecordsを嵌め込む
cat ${SYSD}/APPLI/${CATEGORY}/${FUNC}/HTML/CONFIRM/TABLE.HTML         |
sed -e "s|###OPE_INFO###|${OPE_INFO}|g"                               |
sed -e "s|###PARTS_INFO###|${PARTS_INFO}|g"                           |
sed -e "s|###LABEL_OPE###|${OPE_LABEL}|g"                             |
sed -e "s|###LABEL_PARTS###|${PARTS_LABEL}|g"                         |
sed -e "s|###TABLE_RECORDS_OPERATION###|${TABLE_RECORDS_OPERATION}|g" |
sed -e "s|###TABLE_RECORDS_PARTS###|${TABLE_RECORDS_PARTS}|g"         > $tmp-table-html

########################################
# 改行文字を「\\n」という3文字の文字列に置換
TABLE=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-table-html`

########################################
#tableをはめ込む、ページャーを差し込む
cat ${SYSD}/APPLI/${CATEGORY}/${FUNC}/HTML/CONFIRM/INPUT.HTML         |
sed -e "s|###REDIRECT_FORCE###|${REDIRECT_FORCE}|"                    |
sed -e "s|###INFO_MSG###|${INFO_MSG}|"                                |
sed -e "s/###APPRAISAL_INFO###/${APPRAISAL_INFO}/"                    |
sed -e "s|###CUSTOMER_INFO###|${CUSTOMER_INFO}|"                      |
sed -e "s|###TEMP_NO###|${TEMP_NO}|g"                                 |
sed -e "s|###TABLE###|${TABLE}|g"                                     > $tmp-html

########################################
#page name
echo "Appraisal Confirm" > $tmp-pagename

###############################################################################
#ending
echo "OK"
exit 0
