#!/bin/bash -evx
#

########################################
#	EMPLOYEE NEW COMPLETE.CGI
#
#   引数
#       $1:プロセスID
#
#	Written by hiramatsu


########################################
#Set basic
SYSD=/home/sureshotsystem
#exec 2> ${SYSD}/LOG/LOG.$(basename $0).$(date +%Y%m%d).$(date +%H%M%S).$$
tmp=/tmp/tmp_$1
LANG=ja_JP.UTF-8
PATH=/home/:/home/UTL:/home/TOOL/open-usp-tukubai-2014061402/COMMANDS:$PATH
CATEGORY=`cat $tmp-category`
FUNC=`cat $tmp-func`
EMPLOYEED=${SYSD}/DATA/${CATEGORY}
LOGIND=${EMPLOYEED}/LOGIN
USERSD=${EMPLOYEED}/USERS
EMP_SESS_ID='ss_employee_session_id'

########################################
#Check error
ERROR_CHECK(){
	[ $(plus ${PIPESTATUS[@]}) -eq 0 ] && return
cat <<- FIN
	Context-type: text/html
	NG input
FIN
	cat $tmp-result
	exit 1
}

#######################################
#Get Form Data
VALUE1=$(nameread FAMILY_NAME $tmp-post)
VALUE2=$(nameread GIVEN_NAME $tmp-post)
VALUE3=$(nameread EMAIL $tmp-post)
VALUE4=$(nameread PASSWORD $tmp-post)
#VALUE5=$(nameread ADMIN_FLAG $tmp-post)
VALUE5=0

########################################
#新規の社員番号を確定する
EMPLOYEE_NUM=`${SYSD}/CGI/NUMBERS 'EMPLOYEES' `

########################################
#Set DATE
CREATE_DATE=$(date +%Y%m%d%H%M%S)
UPDATE_DATE=$CREATE_DATE

########################################
#Write login to tempolary file
#1.社員番号 3.EMAIL 2.PW 3.作成日時 4.更新日時 5.ADMINフラグ 6.削除フラグ
echo ${EMPLOYEE_NUM}" "${VALUE3}" "${VALUE4}" "${CREATE_DATE}" "${UPDATE_DATE}" "${VALUE5}" "0 > $tmp-login

########################################
#Write data to tempolary file
#1.社員番号 2.姓 3.名 4.EMAIL 5.TEL 6.作成日時 7.更新日時 8.ADMINフラグ 9.削除フラグ
echo ${EMPLOYEE_NUM}" "${VALUE1}" "${VALUE2}" "${VALUE3}" - "${CREATE_DATE}" "${UPDATE_DATE}" "${VALUE5}" "0 > $tmp-employee

########################################
#Data Saving for LOGIN
#LV1
$(mv $tmp-login ${LOGIND}/LV1/${EMPLOYEE_NUM}_loginpass_${CREATE_DATE})
#LV2
cat ${LOGIND}/LV1/${EMPLOYEE_NUM}_loginpass_${CREATE_DATE}  >> ${LOGIND}/LV2/LOGINPASSES
chmod 775 ${LOGIND}/LV2/LOGINPASSES
#LV3
cat ${LOGIND}/LV1/${EMPLOYEE_NUM}_loginpass_${CREATE_DATE}  >> ${LOGIND}/LV3/LOGINPASSES
chmod 775 ${LOGIND}/LV3/LOGINPASSES

########################################
#Data Saving for EMPLOYEE
#LV1
$(mv $tmp-employee ${USERSD}/LV1/${EMPLOYEE_NUM}_employee_${CREATE_DATE})
#LV2
cat ${USERSD}/LV1/${EMPLOYEE_NUM}_employee_${CREATE_DATE}   >> ${USERSD}/LV2/EMPLOYEES
chmod 775 ${USERSD}/LV2/EMPLOYEES
#LV3
cat ${USERSD}/LV1/${EMPLOYEE_NUM}_employee_${CREATE_DATE}   |
awk '{print sprintf("%d %s %s %s %s %s %s %d %d /APP/EMPLOYEE/USERS/SHOW/?id=%d /APP/EMPLOYEE/EDIT/INPUT/?id=%d /APP/EMPLOYEE/DELETE/CONFIRM/?id=%d",$1,$2,$3,$4,$5,$6,$7,$8,$9,$1,$1,$1)}'    >> ${USERSD}/LV3/EMPLOYEES
chmod 775 ${USERSD}/LV3/EMPLOYEES

########################################
#SET SESSION
COOK=`${SYSD}/CGI/SESSION/SESSION_SET ${EMP_SESS_ID} `
echo $COOK > $tmp-cook

########################################
#HTMLの設定
ACTION=`cat $tmp-action`
cat ${SYSD}/APPLI/${CATEGORY}/${FUNC}/HTML/${ACTION}.HTML   |
sed -e "s/###FAMILY_NAME_LABEL###/${VALUE1}/"               |
sed -e "s/###GIVEN_NAME_LABEL###/${VALUE2}/"                |
sed -e "s/###EMAIL_LABEL###/${VALUE3}/"                     > $tmp-html

###############################################################################
#ending
echo "employee new user OK"
#echo $COOK_SET
exit 0



