#!/bin/bash -vx
#

########################################
#	LOCK.CGI
#
#   引数
#       $1:プロセスID($$)
#       $2:カテゴリ名、またはロックファイルのパス(LOCK配下はデフォルト)
#
#	Written by hiramatsu


########################################
#Set basic
SYSD=/home/sureshotsystem
exec 2> ${SYSD}/LOG/LOG.$(basename $0).$(date +%Y%m%d).$(date +%H%M%S).$$
echo $1
tmp=/tmp/tmp_$1
LANG=ja_JP.UTF-8
PATH=/home/:/home/UTL:/home/TOOL/open-usp-tukubai-2014061402/COMMANDS:$PATH
LOCKD=${SYSD}/LOCK/$2

########################################
#Check error
ERROR_CHECK(){
	[ $(plus ${PIPESTATUS[@]}) -eq 0 ] && return
cat <<- FIN
	Context-type: text/html
	NG input
FIN
	cat $tmp-result
	exit 1
}

########################################
#
COUNT=1
while :
do
    if [ -z $( cat ${LOCKD}/* ) ]; then
        touch ${LOCKD}/locked_$1
        STATUS='LOCKED'
        PID=$$
        break
    else
        sleep 1s
        STATUS='WAITING'
    fi
    COUNT=$(( COUNT + 1 ))
    if [ ${COUNT} -gt 3 ] ; then
        STATUS='ERROR'
        break
    fi
done

if [ ${STATUS} = 'ERROR' ]; then
cat <<- FIN
	Context-type: text/html
	NG input
FIN
	cat $tmp-result
	exit 1
fi

########################################
#戻り値
echo ${PID}

########################################
#正常終了
#rm -f $tmp-*
exit 0
