#!/bin/bash -vx
#

########################################
#	UNLOCK.CGI
#
#   引数
#       $1:プロセスID
#       $2:カテゴリ名、またはロックファイルのパス(LOCK配下はデフォルト)
#       $3:任意 固有キー(社員番号など)
#   戻り値
#       ステータス
#
#	Written by hiramatsu


########################################
#基本設定
SYSD=$(cd $(dirname $0) && pwd | awk '{print substr($0, 0, index($0, "sureshotsystem")+13)}')
#exec 2> ${SYSD}/LOG/LOG.$(basename $0).$(date +%Y%m%d).$(date +%H%M%S).$$
tmp=/tmp/tmp_$1
LANG=ja_JP.UTF-8
PATH=/home/:/home/UTL:/home/TOOL/open-usp-tukubai-2014061402/COMMANDS:$PATH
LOCKD=${SYSD}/LOCK/$2
KEY=${3:-KEY}

########################################
#Check error
ERROR_CHECK(){
	[ $(plus ${PIPESTATUS[@]}) -eq 0 ] && return
    cat ${SYSD}/HTML/ERROR/SYSTEM_ERROR.HTML                        |
    sed -e "s/###ERROR1_LABEL###/データロック解除処理中にエラー/"   |
    sed -e "s/###ERROR2_LABEL###/処理ステータス:UNLOCK_ERROR/"      |
    sed -e "s/###ERROR3_LABEL###/${LOCKD}/"                      |
    sed -e "s/###ERROR4_LABEL###/${KEY}/"                           |
    sed -e "s/###ERROR5_LABEL###//"                                 > $tmp-html
    echo "UNLOCK_ERROR"
    exit 0
}

########################################
#ロック解除
if [ ${KEY} = 'KEY' ]; then
    rm -f ${LOCKD}/* 
else
    rm -f ${LOCKD}/*.${KEY}.lock
fi
ERROR_CHECK

########################################
#戻り値
echo "UNLOCK"

########################################
#正常終了
exit 0
