#!/bin/bash -vx
#

########################################
#	UNLOCK.CGI
#
#   引数
#       $1:カテゴリ名、またはロックファイルのパス(LOCK配下はデフォルト)
#       $2:任意 固有キー(社員番号など)
#   戻り値
#       ステータス
#
#	Written by hiramatsu


########################################
#Set basic
SYSD=/home/sureshotsystem
#exec 2> ${SYSD}/LOG/LOG.$(basename $0).$(date +%Y%m%d).$(date +%H%M%S).$$
LANG=ja_JP.UTF-8
PATH=/home/:/home/UTL:/home/TOOL/open-usp-tukubai-2014061402/COMMANDS:$PATH
LOCKD=${SYSD}/LOCK/$1
KEY=${2:-KEY}

########################################
#Check error
ERROR_CHECK(){
	[ $(plus ${PIPESTATUS[@]}) -eq 0 ] && return
    echo "UNLOCK_ERROR"
	exit 1
}

########################################
#ロック解除
if [ ${KEY} = 'KEY' ]; then
    rm -f ${LOCKD}/* 
else
    rm -f ${LOCKD}/*.${KEY}.lock
fi
ERROR_CHECK

########################################
#戻り値
echo "UNLOCK"

########################################
#正常終了
exit 0
