#!/bin/bash
#

########################################
#	GET_INFO.CGI
#
#   引数
#       $1:プロセスID
#       $2:必須 DFSのパス
#       $3:必須 GroupKey
#
#	Written by hiramatsu


########################################
#基本設定
SYSD=$(cd $(dirname $0) && pwd | awk '{print substr($0, 0, index($0, "sureshotsystem")+13)}')
#exec 2> ${SYSD}/LOG/LOG.$(basename $0).${DATE_TIME_PID}
tmp=/tmp/tmp_$1
LANG=ja_JP.UTF-8
#PATH=/home/:/home/UTL:/home/TOOL/open-usp-tukubai-2014061402/COMMANDS:$PATH

#作成日時
ls -1 $2/$3_* | cut -d'_' -f4 | LANG=C sort -nk1 | head -n1 > $tmp-create-dt

#作成者
ls -1 $2/$3_* | LANG=C sort -t$'_' -nk4 | cut -d'_' -f3 | head -n1 > $tmp-create-user

#最終更新日時
ls -1 $2/$3_* | cut -d'_' -f4 | LANG=C sort -nk1 | tail -n1 > $tmp-lastupdate-dt

#最終更新者
ls -1 $2/$3_* | LANG=C sort -t$'_' -nk4 | cut -d'_' -f3 | tail -n1 > $tmp-lastupdate-user

########################################
#戻り値
echo "OK" 

########################################
#正常終了
exit 0
