#!/bin/bash -vx
#

########################################
#	VALIDATION.CGI
# 設定されたバリデーションを実行する    
#     
#     $1:必須 セッションID
#
#	Written by hiramatsu
#
#
# 使用方法
# 　呼び出し元にて、バリデーションを行単位で指定し、
#   $tmp-validationをリダイレクトする
#   
#   バリデーションの指定方法
#     バリデーションをかける項目名を先頭、
#     /CGI/VALID/LISTS配下にあるバリデーションファイル名を中央、
#     バリデーションに必要な値(引数)を後方に配置する
#     これらをパイプ「|」をデリミタとして繋ぐ
#     また引数を複数指定したい場合には、デリミタとしてカンマ「，」を用いる
#     例：文字列の長さが3文字以上
#         FAMILY_NAME|LENGTH|AAA,3,0
#         

########################################
#基本設定
SYSD=$(cd $(dirname $0) && pwd | awk '{print substr($0, 0, index($0, "sureshotsystem")+13)}')
#exec 2> ${SYSD}/LOG/LOG.$(basename $0).$(date +%Y%m%d).$(date +%H%M%S).$$
tmp=/tmp/tmp_$1

#######################################
#呼び出し元で設定したバリデーションを横並びにして配列化の種を作成
cat $tmp-validation |
awk '
{ for (i=1; i<=NF; i++)  { a[NR,i] = $i } } NF>p { p = NF }
END {
for(j=1; j<=p; j++) { str=a[1,j]; for(i=2; i<=NR; i++){ str=str" "a[i,j]; }
print str
}
}' > $tmp-validation-list

#######################################
#上記で作った種を配列に変換
ARR=(`cat $tmp-validation-list`)

#######################################
#配列を回して、設定されたバリデーションを実行し、結果を書き込む
for valid in ${ARR[@]}; do
  NAME=$(echo $valid | cut -d'|' -f1)
  VALID=$(echo $valid | cut -d'|' -f2)
  ARGS=$(echo $valid | cut -d'|' -f3 | tr -s ',' ' ')
  result=`${SYSD}/CGI/VALID/LISTS/${VALID} ${ARGS}`
  echo $result >> $tmp-validation-result
done

#######################################
#バリデーションの結果と設定を結合してレポートを作成
#項目名|バリデーション名|結果
 paste -d '|' $tmp-validation $tmp-validation-result | awk 'BEGIN{FS="|"}{OFS="|"}{print $1,$2,$4}' > $tmp-valid-report

#EXAM
#cat $tmp-validation >/tmp/tmp-v
#cat $tmp-validation-list >/tmp/tmp-vlist
#cat $tmp-validation-result >/tmp/tmp-vresult

#######################################
#Return cookie words
exit 0

