#!/bin/bash -evx
#

########################################
#	SET_LIST/NEW ADD.CGI
#
#   引数
#       $1:プロセスID
#
#	Written by hiramatsu


########################################
#基本設定
SYSD=$(cd $(dirname $0) && pwd | awk '{print substr($0, 0, index($0, "sureshotsystem")+13)}')
#exec 2> ${SYSD}/LOG/LOG.$(basename $0).$(date +%Y%m%d).$(date +%H%M%S).$$
tmp=/tmp/tmp_$1
LANG=ja_JP.UTF-8
PATH=/home/:/home/UTL:/home/TOOL/open-usp-tukubai-2014061402/COMMANDS:$PATH
CATEGORY=`cat $tmp-category`
FUNC=`cat $tmp-func`
DATAD=${SYSD}/DATA/${CATEGORY}/LISTS

########################################
#Check error
ERROR_CHECK(){
	[ $(plus ${PIPESTATUS[@]}) -eq 0 ] && return
cat <<- FIN
	Context-type: text/html
	NG input
FIN
	cat $tmp-result
	exit 1
}

########################################
#マスタの更新中は、処理をさせない
#ls ${SYSD}/LOCK/SET_CATEGORY/* > $tmp-checker 2> /dev/null
#if [ -n cat $tmp-checker ] ; then
#    echo "333" > $tmp-ajax-html
#    exit 0
#fi

#######################################
#フォームの入力値を取得
cat $tmp-post
TYPE=$(nameread TYPE $tmp-post)
ROW=$(nameread ROW $tmp-post)
SET_CATEGORY_NO=$(nameread SET_CATEGORY_NO $tmp-post)
SET_CATEGORY_NM=$(nameread SET_CATEGORY_NM $tmp-post)
SET_NM=$(nameread SET_NM $tmp-post)
SET_PRICE=$(nameread SET_PRICE $tmp-post)
SET_REMARKS=$(nameread SET_REMARKS $tmp-post)
OPERATION_CATEGORY_NO=$(nameread OPERATION_CATEGORY_NO $tmp-post)
OPERATION_CATEGORY=$(nameread OPERATION_CATEGORY $tmp-post)
OPERATION_NO=$(nameread OPERATION_NO $tmp-post)
OPERATION_NM=$(nameread OPERATION_NM $tmp-post)
OPERATION_PRICE=$(nameread OPERATION_PRICE $tmp-post)
OPERATION_QTY=$(nameread OPERATION_QTY $tmp-post)
PARTS_CATEGORY_NO=$(nameread PARTS_CATEGORY_NO $tmp-post)
PARTS_CATEGORY_NM=$(nameread PARTS_CATEGORY_NM $tmp-post)
PARTS_NO=$(nameread PARTS_NO $tmp-post)
PARTS_NM=$(nameread PARTS_NM $tmp-post)
PARTS_PRICE=$(nameread PARTS_PRICE $tmp-post)
PARTS_QTY=$(nameread PARTS_QTY $tmp-post)

########################################
#仮登録ディレクトリ
SESSION=$(session_get 'sureshot_stuff_session_id') 
STUFF_ID=$(cat ${SYSD}/SESSION/${SESSION})
TMPD=${SYSD}/TMP/${STUFF_ID}

########################################
#セットの仮登録
echo ${SET_CATEGORY_NO} ${SET_CATEGORY_NM} ${SET_NM} ${SET_PRICE} ${SET_REMARKS} \
${OPERATION_CATEGORY_NO} ${OPERATION_CATEGORY_NM} ${OPERATION_NO} ${OPERATION_NM} ${OPERATION_PRICE} ${OPERATION_QTY} \
${PARTS_CATEGORY_NO} ${PARTS_CATEGORY_NM} ${PARTS_NO} ${PARTS_NM} ${PARTS_PRICE} ${PARTS_QTY} > $tmp-set-temporary
cat $tmp-set-temporary >> ${TMPD}/set_list

########################################
#セットカテゴリを取得
cat ${SYSD}/DATA/SET_CATEGORY/LISTS/LV3/*[^_d]    |
LANG=C sort -nk1,1                                > $tmp-set-category

########################################
#Page絞り込み用のセットカテゴリ
# 1;カテゴリ番号 2;カテゴリ名
mojihame -lRECORDS ${SYSD}/APPLI/${CATEGORY}/LISTS/HTML/SET_CATEGORY_PAGE.HTML $tmp-set-category > $tmp-set-category-page

########################################
#セットリスト用のセットカテゴリ
# 1;カテゴリ番号 2;カテゴリ名
mojihame -lRECORDS ${SYSD}/APPLI/${CATEGORY}/LISTS/HTML/SET_CATEGORY_LIST.HTML $tmp-set-category > $tmp-set-category-list

########################################
#セット新規登録用のセットカテゴリ
# 1;カテゴリ番号 2;カテゴリ名
mojihame -lRECORDS ${SYSD}/APPLI/${CATEGORY}/LISTS/HTML/SET_CATEGORY_NEW.HTML $tmp-set-category > $tmp-set-category-new

########################################
# セットカテゴリの改行文字を「\\n」という3文字の文字列に置換
SET_CATEGORY_PAGE=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-set-category-page`
SET_CATEGORY_LIST=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-set-category-list`
SET_CATEGORY_NEW=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-set-category-new`

########################################
#作業カテゴリを取得
cat ${SYSD}/DATA/OPERATION_CATEGORY/LISTS/LV3/*[^_d]    |
LANG=C sort -nk1,1                                  > $tmp-operation-category

########################################
#作業リスト用の作業カテゴリ
# 1;カテゴリ番号 2;カテゴリ名
mojihame -lRECORDS ${SYSD}/APPLI/${CATEGORY}/LISTS/HTML/OPERATION_CATEGORY_LIST.HTML $tmp-operation-category > $tmp-operation-category-list

########################################
#作業新規登録用の作業カテゴリ
# 1;カテゴリ番号 2;カテゴリ名
mojihame -lRECORDS ${SYSD}/APPLI/${CATEGORY}/LISTS/HTML/OPERATION_CATEGORY_NEW.HTML $tmp-operation-category > $tmp-operation-category-new

########################################
# 改行文字を「\\n」という3文字の文字列に置換
OPERATION_CATEGORY_LIST=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-operation-category-list`
OPERATION_CATEGORY_NEW=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-operation-category-new`

########################################
#パーツカテゴリを取得
cat ${SYSD}/DATA/PARTS_CATEGORY/LISTS/LV3/*[^_d]    |
LANG=C sort -nk1,1                                  > $tmp-parts-category

########################################
#パーツリスト用のパーツカテゴリ
# 1;カテゴリ番号 2;カテゴリ名
mojihame -lRECORDS ${SYSD}/APPLI/${CATEGORY}/LISTS/HTML/PARTS_CATEGORY_LIST.HTML $tmp-parts-category > $tmp-parts-category-list

########################################
#パーツ新規登録用のパーツカテゴリ
# 1;カテゴリ番号 2;カテゴリ名
mojihame -lRECORDS ${SYSD}/APPLI/${CATEGORY}/LISTS/HTML/PARTS_CATEGORY_NEW.HTML $tmp-parts-category > $tmp-parts-category-new

########################################
# 改行文字を「\\n」という3文字の文字列に置換
PARTS_CATEGORY_LIST=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-parts-category-list`
PARTS_CATEGORY_NEW=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-parts-category-new`

########################################
#セットリストを取得
cat ${TMPD}/set_list                                    |
juni                                                    |
LANG=C sort -nk2,1                                      > $tmp-records

mojihame -lRECORDS ${SYSD}/APPLI/${CATEGORY}/${FUNC}/HTML/RECORDS.HTML $tmp-records     > $tmp-table-records
cat $tmp-table-records                                                                  |
sed -e "s|###SET_CATEGORY###|${SET_CATEGORY_LIST}|g"                                    |
sed -e "s|###OPERATION_CATEGORY###|${OPERATION_CATEGORY_LIST}|g"                        | 
sed -e "s|###PARTS_CATEGORY###|${SET_CATEGORY_LIST}|g"                                  > $tmp-table-records2

########################################
# 改行文字を「\\n」という3文字の文字列に置換
TABLE_RECORDS=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-table-records2`

########################################
#tableにrecordsを嵌め込む　
cat ${SYSD}/APPLI/${CATEGORY}/NEW/HTML/TABLE.HTML               |
sed -e "s|###TABLE_RECORDS###|${TABLE_RECORDS}|g"               |
sed -e "s|###SET_CATEGORY###|${SET_CATEGORY_NEW}|g"             | 
sed -e "s|###OPERATION_CATEGORY###|${OPERATION_CATEGORY_NEW}|g" |
sed -e "s|###PARTS_CATEGORY###|${PARTS_CATEGORY_NEW}|g"         > $tmp-ajax-html

########################################
#ending
echo "OK"
exit 0
