#!/bin/bash -evx
#

########################################
#	SET_LIST/NEW COMPLETE.CGI
#
#   引数
#       $1:プロセスID
#
#	Written by hiramatsu


########################################
#基本設定
SYSD=$(cd $(dirname $0) && pwd | awk '{print substr($0, 0, index($0, "sureshotsystem")+13)}')
#exec 2> ${SYSD}/LOG/LOG.$(basename $0).$(date +%Y%m%d).$(date +%H%M%S).$$
tmp=/tmp/tmp_$1
LANG=ja_JP.UTF-8
PATH=/home/:/home/UTL:/home/TOOL/open-usp-tukubai-2014061402/COMMANDS:$PATH
CATEGORY=`cat $tmp-category`
FUNC=`cat $tmp-func`

########################################
#Check error
ERROR_CHECK(){
	[ $(plus ${PIPESTATUS[@]}) -eq 0 ] && return
cat <<- FIN
	Context-type: text/html
	NG input
FIN
	cat $tmp-result
	exit 1
}

########################################
#セットカテゴリ更新中は、処理をさせない
#ls ${SYSD}/LOCK/SET_CATEGORY/* > $tmp-checker 2> /dev/null
#if [ -n cat $tmp-checker ] ; then
#    echo "333" > $tmp-ajax-html
#    exit 0
#fi

########################################
#仮登録ディレクトリ
SESSION=$(session_get 'sureshot_stuff_session_id') 
STUFF_ID=$(cat ${SYSD}/SESSION/${SESSION})
TEMPD=${SYSD}/TMP/${STUFF_ID}/SET_LIST


########################################
#セットカテゴリ
SET_CATEGORY_NO=$(cat ${TEMPD}/set_list | awk '{print $1}')

########################################
#ディレクトリを作成する
if [ -e ${SYSD}/DATA/${CATEGORY}  ]; then
    :
else
    mkdir ${SYSD}/DATA/${CATEGORY}
    mkdir ${SYSD}/DATA/${CATEGORY}/LISTS
    cp -rp ${SYSD}/DATA/ORG_LV1-3/ ${SYSD}/DATA/${CATEGORY}/LISTS/${SET_CATEGORY_NO}
    chmod -R 770 ${SYSD}/DATA/${CATEGORY} #オーナーと権限を再帰的に設定
    #chown -R root:apache ${SYSD}/DATA/NUMBERS/${CATEGORY}
    ERROR_CHECK
fi

########################################
#DATAディレクトリ
DATAD=${SYSD}/DATA/${CATEGORY}/LISTS/${SET_CATEGORY_NO}

########################################
#セット番号の次のロットを追加する
LATEST_NUM=$(ls ${SYSD}/DATA/NUMBERS/${CATEGORY}/ORIGIN | sort -nr | head -n 1)
START=$((LATEST_NUM + 1))
END=$((START + 1))
SEQ_STATUS=`${SYSD}/CGI/NUMBER_SEQ $1 ${CATEGORY} ${START} ${END} `
[[ ${SEQ_STATUS} != 'SUCCESS' ]] && exit 0

########################################
#新規セット番号を確定する
NEW_NUM=`${SYSD}/CGI/NUMBERS $1 'SET_LIST' `
[ ${NEW_NUM} = 'ERROR' ] && exit 0 || :

########################################
#日付を設定
CREATE_DATE=$(date +%Y%m%d%H%M%S)
UPDATE_DATE=$CREATE_DATE

#######################################
#仮登録セットリストを取得
#SET_LISTのデータ構造  IDとyyyymmddhhmmssは一致
#SET_LIST/LIST/LV*/[ID]_setlist_[yyyymmddhhmmss]
#SET_LIST/LIST/LV*/[ID]_setlist_operation_[yyyymmddhhmmss]
#SET_LIST/LIST/LV*/[id]_setlist_parts_[yyyymmddhhmmss]
cat ${TEMPD}/set_list | awk -v cdt=${CREATE_DATE} -v udt=${UPDATE_DATE} '{print $0, cdt, udt}' > $tmp-set-list
cat ${TEMPD}/set_list_operation | awk -v cdt=${CREATE_DATE} -v udt=${UPDATE_DATE} '{print $0, cdt, udt}' > $tmp-set-list_operation
cat ${TEMPD}/set_list_parts | awk -v cdt=${CREATE_DATE} -v udt=${UPDATE_DATE} '{print $0, cdt, udt}' > $tmp-set-list_parts

########################################
#データ格納
#LV1
$(mv $tmp-set-list ${DATAD}/LV1/${NEW_NUM}_setlist_${CREATE_DATE})
$(mv $tmp-set-list_operation ${DATAD}/LV1/${NEW_NUM}_setlist_operation_${CREATE_DATE})
$(mv $tmp-set-list_parts ${DATAD}/LV1/${NEW_NUM}_setlist_parts_${CREATE_DATE})
#LV2
cat ${DATAD}/LV1/${NEW_NUM}_setlist_${CREATE_DATE} > ${DATAD}/LV2/${NEW_NUM}_setlist_${CREATE_DATE}
cat ${DATAD}/LV1/${NEW_NUM}_setlist_operation_${CREATE_DATE} > ${DATAD}/LV2/${NEW_NUM}_setlist_operation_${CREATE_DATE}
cat ${DATAD}/LV1/${NEW_NUM}_setlist_parts_${CREATE_DATE} > ${DATAD}/LV2/${NEW_NUM}_setlist_parts_${CREATE_DATE}
#LV3
cat ${DATAD}/LV2/${NEW_NUM}_setlist_${CREATE_DATE} > ${DATAD}/LV3/${NEW_NUM}_setlist_${CREATE_DATE}
cat ${DATAD}/LV2/${NEW_NUM}_setlist_operation_${CREATE_DATE} > ${DATAD}/LV3/${NEW_NUM}_setlist_operation_${CREATE_DATE}
cat ${DATAD}/LV2/${NEW_NUM}_setlist_parts_${CREATE_DATE} > ${DATAD}/LV3/${NEW_NUM}_setlist_parts_${CREATE_DATE}

#######################################
#仮登録セットリストを削除
rm -rf ${TEMPD}

########################################
#ending
echo "OK"
exit 0
