#!/bin/bash -vx
#

########################################
# SET_LIST/LIST SHOW.CGI
#
#   $1:必須 $$
#
#	Written by hiramatsu


########################################
#基本設定
export LANG=ja_JP.utf8
echo $LANG
SYSD=$(cd $(dirname $0) && pwd | awk '{print substr($0, 0, index($0, "sureshotsystem")+13)}')
#exec 2> $SYSD/LOG/LOG.$(basename $0).$(date +%Y%m%d).$(date +%H%M%S).$$
tmp=/tmp/tmp_$1
LANG=ja_JP.UTF-8
#PATH=/home/:/home/UTL:/home/TOOL/open-usp-tukubai-2014061402/COMMANDS:$PATH
CATEGORY=`cat $tmp-category`
FUNC=`cat $tmp-func`
DATAD=${SYSD}/DATA/${CATEGORY}/LISTS

#######################################
#Check error
ERROR_CHECK(){
	[ $(plus ${PIPESTATUS[@]}) -eq 0 ] && return
cat <<- FIN
	Context-type: text/html
	NG input
FIN
	cat $tmp-result
	exit 1
}

########################################
#セットカテゴリを取得
cat ${SYSD}/DATA/SET_CATEGORY/LISTS/LV3/*[^_d]    |
LANG=C sort -nk1,1                                  > $tmp-set-category

########################################
#Page絞り込み用のセットカテゴリ
# 1;カテゴリ番号 2;カテゴリ名
mojihame -lRECORDS ${SYSD}/APPLI/${CATEGORY}/LISTS/HTML/SET_CATEGORY_PAGE.HTML $tmp-set-category > $tmp-set-category-page

########################################
#セットリスト用のセットカテゴリ
# 1;カテゴリ番号 2;カテゴリ名
mojihame -lRECORDS ${SYSD}/APPLI/${CATEGORY}/LISTS/HTML/SET_CATEGORY_LIST.HTML $tmp-set-category > $tmp-set-category-list

########################################
#セット新規登録用のセットカテゴリ
# 1;カテゴリ番号 2;カテゴリ名
mojihame -lRECORDS ${SYSD}/APPLI/${CATEGORY}/LISTS/HTML/SET_CATEGORY_NEW.HTML $tmp-set-category > $tmp-set-category-new

########################################
# セットカテゴリの改行文字を「\\n」という3文字の文字列に置換
SET_CATEGORY_PAGE=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-set-category-page`
SET_CATEGORY_LIST=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-set-category-list`
SET_CATEGORY_NEW=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-set-category-new`

########################################
#作業カテゴリを取得
cat ${SYSD}/DATA/OPERATION_CATEGORY/LISTS/LV3/*[^_d]    |
LANG=C sort -nk1,1                                  > $tmp-operation-category

########################################
#作業リスト用の作業カテゴリ
# 1;カテゴリ番号 2;カテゴリ名
mojihame -lRECORDS ${SYSD}/APPLI/${CATEGORY}/LISTS/HTML/OPERATION_CATEGORY_LIST.HTML $tmp-operation-category > $tmp-operation-category-list

########################################
#作業新規登録用の作業カテゴリ
# 1;カテゴリ番号 2;カテゴリ名
mojihame -lRECORDS ${SYSD}/APPLI/${CATEGORY}/LISTS/HTML/OPERATION_CATEGORY_NEW.HTML $tmp-operation-category > $tmp-operation-category-new

########################################
# 改行文字を「\\n」という3文字の文字列に置換
OPERATION_CATEGORY_LIST=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-operation-category-list`
OPERATION_CATEGORY_NEW=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-operation-category-new`

########################################
#パーツカテゴリを取得
cat ${SYSD}/DATA/PARTS_CATEGORY/LISTS/LV3/*[^_d]    |
LANG=C sort -nk1,1                                  > $tmp-parts-category

########################################
#パーツリスト用のパーツカテゴリ
# 1;カテゴリ番号 2;カテゴリ名
mojihame -lRECORDS ${SYSD}/APPLI/${CATEGORY}/LISTS/HTML/PARTS_CATEGORY_LIST.HTML $tmp-parts-category > $tmp-parts-category-list

########################################
#パーツ新規登録用のパーツカテゴリ
# 1;カテゴリ番号 2;カテゴリ名
mojihame -lRECORDS ${SYSD}/APPLI/${CATEGORY}/LISTS/HTML/PARTS_CATEGORY_NEW.HTML $tmp-parts-category > $tmp-parts-category-new

########################################
# 改行文字を「\\n」という3文字の文字列に置換
PARTS_CATEGORY_LIST=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-parts-category-list`
PARTS_CATEGORY_NEW=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-parts-category-new`

########################################
#セットリストを取得 ※実際にはレコードの表示はない。HTMLの枠組みのために読み込む
if [ "${SET_PAGE_CATEGORY_NO}" -gt 0 ] ; then
    #ページフィルターにALL以外(空欄を除く)が選択された場合
    cat ${DATAD}/${SET_PAGE_CATEGORY_NO}*[^_d]/LV3/*[^_d]   |
    LANG=C sort -nk1,1                                      |
    awk -v s=${START} -v e=${END} 'NR>=s&&NR<=e&&$9!=1'     |
    juni                                                    > $tmp-records
else
    cat ${DATAD}/*[^_d]/LV3/*[^_d]                          |
    LANG=C sort -nk1,1                                      |
    awk -v s=${START} -v e=${END} 'NR>=s&&NR<=e&&$9!=1'     |
    juni                                                    > $tmp-records
fi

mojihame -lRECORDS ${SYSD}/APPLI/${CATEGORY}/${FUNC}/HTML/RECORDS.HTML $tmp-records     > $tmp-table-records
cat $tmp-table-records                                                                  |
sed -e "s|###SET_CATEGORY###|${SET_CATEGORY_LIST}|g"                                    |
sed -e "s|###OPERATION_CATEGORY###|${OPERATION_CATEGORY_LIST}|g"                        | 
sed -e "s|###PARTS_CATEGORY###|${SET_CATEGORY_LIST}|g"                                  > $tmp-table-records2

########################################
# 改行文字を「\\n」という3文字の文字列に置換
TABLE_RECORDS=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-table-records2`

########################################
#tableにrecordsを嵌め込む　
cat ${SYSD}/APPLI/${CATEGORY}/NEW/HTML/TABLE.HTML               |
sed -e "s|###TABLE_RECORDS###|${TABLE_RECORDS}|g"               |
sed -e "s|###SET_CATEGORY###|${SET_CATEGORY_NEW}|g"             | 
sed -e "s|###OPERATION_CATEGORY###|${OPERATION_CATEGORY_NEW}|g" |
sed -e "s|###PARTS_CATEGORY###|${PARTS_CATEGORY_NEW}|g"         > $tmp-table-html

########################################
# 改行文字を「\\n」という3文字の文字列に置換
TABLE=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-table-html`

########################################
#tableをはめ込む、ページャーを差し込む
cat ${SYSD}/APPLI/${CATEGORY}/NEW/HTML/INPUT.HTML               |
sed -e "s|###SET_CATEGORY_NM_PAGE###|${SET_PAGE_CATEGORY}|g"    |
sed -e "s|###SET_CATEGORY_NO_PAGE###|${SET_PAGE_CATEGORY_NO}|g" |
sed -e "s|###SET_CATEGORY###|${SET_CATEGORY_PAGE}|g"            |
sed -e "s|###TABLE###|${TABLE}|g"                               |
sed -e "s|###INFO_MSG###||g"                                    |
sed -e "s|###PAGER###|$(cat $tmp-pager-html)|g"                 > $tmp-html

########################################
#page name
echo "Set Input" > $tmp-pagename

########################################
echo "OK"
exit 0
