#!/bin/bash -vx
#

########################################
# SET_LIST/LIST SHOW.CGI
#
#   $1:必須 $$
#
#	Written by hiramatsu


########################################
#基本設定
export LANG=ja_JP.utf8
echo $LANG
SYSD=$(cd $(dirname $0) && pwd | awk '{print substr($0, 0, index($0, "sureshotsystem")+13)}')
#exec 2> $SYSD/LOG/LOG.$(basename $0).$(date +%Y%m%d).$(date +%H%M%S).$$
tmp=/tmp/tmp_$1
LANG=ja_JP.UTF-8
#PATH=/home/:/home/UTL:/home/TOOL/open-usp-tukubai-2014061402/COMMANDS:$PATH
CATEGORY=`cat $tmp-category`
FUNC=`cat $tmp-func`
DATAD=${SYSD}/DATA/${CATEGORY}/LISTS

#######################################
#Check error
ERROR_CHECK(){
	[ $(plus ${PIPESTATUS[@]}) -eq 0 ] && return
cat <<- FIN
	Context-type: text/html
	NG input
FIN
	cat $tmp-result
	exit 1
}

########################################
#セットカテゴリを取得
cat ${SYSD}/DATA/SET_CATEGORY/LISTS/LV3/*[^_d]    |
LANG=C sort -nk1,1                                  > $tmp-set-category

########################################
#Page絞り込み用のセットカテゴリ
# 1;カテゴリ番号 2;カテゴリ名
mojihame -lRECORDS ${SYSD}/APPLI/${CATEGORY}/LISTS/HTML/SET_CATEGORY_PAGE.HTML $tmp-set-category > $tmp-set-category-page

########################################
#セットリスト用のセットカテゴリ
# 1;カテゴリ番号 2;カテゴリ名
mojihame -lRECORDS ${SYSD}/APPLI/${CATEGORY}/LISTS/HTML/SET_CATEGORY_LIST.HTML $tmp-set-category > $tmp-set-category-list

########################################
#セット新規登録用のセットカテゴリ
# 1;カテゴリ番号 2;カテゴリ名
mojihame -lRECORDS ${SYSD}/APPLI/${CATEGORY}/LISTS/HTML/SET_CATEGORY_NEW.HTML $tmp-set-category > $tmp-set-category-new

########################################
# セットカテゴリの改行文字を「\\n」という3文字の文字列に置換
SET_CATEGORY_PAGE=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-set-category-page`
SET_CATEGORY_LIST=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-set-category-list`
SET_CATEGORY_NEW=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-set-category-new`

########################################
#作業カテゴリを取得
cat ${SYSD}/DATA/OPERATION_CATEGORY/LISTS/LV3/*[^_d]    |
LANG=C sort -nk1,1                                  > $tmp-operation-category

########################################
#作業リスト用の作業カテゴリ
# 1;カテゴリ番号 2;カテゴリ名
mojihame -lRECORDS ${SYSD}/APPLI/${CATEGORY}/LISTS/HTML/OPERATION_CATEGORY_LIST.HTML $tmp-operation-category > $tmp-operation-category-list

########################################
#作業新規登録用の作業カテゴリ
# 1;カテゴリ番号 2;カテゴリ名
mojihame -lRECORDS ${SYSD}/APPLI/${CATEGORY}/LISTS/HTML/OPERATION_CATEGORY_NEW.HTML $tmp-operation-category > $tmp-operation-category-new

########################################
# 改行文字を「\\n」という3文字の文字列に置換
OPERATION_CATEGORY_LIST=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-operation-category-list`
OPERATION_CATEGORY_NEW=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-operation-category-new`

########################################
#パーツカテゴリを取得
cat ${SYSD}/DATA/PARTS_CATEGORY/LISTS/LV3/*[^_d]    |
LANG=C sort -nk1,1                                  > $tmp-parts-category

########################################
#パーツリスト用のパーツカテゴリ
# 1;カテゴリ番号 2;カテゴリ名
mojihame -lRECORDS ${SYSD}/APPLI/${CATEGORY}/LISTS/HTML/PARTS_CATEGORY_LIST.HTML $tmp-parts-category > $tmp-parts-category-list

########################################
#パーツ新規登録用のパーツカテゴリ
# 1;カテゴリ番号 2;カテゴリ名
mojihame -lRECORDS ${SYSD}/APPLI/${CATEGORY}/LISTS/HTML/PARTS_CATEGORY_NEW.HTML $tmp-parts-category > $tmp-parts-category-new

########################################
# 改行文字を「\\n」という3文字の文字列に置換
PARTS_CATEGORY_LIST=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-parts-category-list`
PARTS_CATEGORY_NEW=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-parts-category-new`

########################################
#仮登録ディレクトリ
SESSION=$(session_get 'sureshot_stuff_session_id') 
STUFF_ID=$(cat ${SYSD}/SESSION/${SESSION})
TMPD=${SYSD}/TMP/${STUFF_ID}

########################################
#作業仮登録リストを取得
cat ${TMPD}/set_list_tmp_operation                      |
juni                                                    |
LANG=C sort -nk2,1                                      > $tmp-operation-records

########################################
#作業仮登録リストをHTMLに書き込む
mojihame -lRECORDS ${SYSD}/APPLI/${CATEGORY}/${FUNC}/HTML/OPERATION_RECORDS.HTML $tmp-operation-records > $tmp-table-records-operation

########################################
#作業仮登録リストのHTMLにSETと作業のカテゴリを書き込む
cat $tmp-table-records-operation                                  |
sed -e "s|###OPERATION_CATEGORY###|${OPERATION_CATEGORY_LIST}|g"  > $tmp-table-records-operation2

########################################
#作業仮登録リストのHTMLの改行文字を「\\n」という3文字の文字列に置換
OPERATION_TABLE_RECORDS=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-table-records-operation2`

########################################
#部品仮登録リストをHTMLに書き込む
cat ${TMPD}/set_list_tmp_parts                          |
juni                                                    |
LANG=C sort -nk2,1                                      > $tmp-parts-records

########################################
#部品仮登録リストをHTMLに書き込む
mojihame -lRECORDS ${SYSD}/APPLI/${CATEGORY}/${FUNC}/HTML/PARTS_RECORDS.HTML $tmp-parts-records > $tmp-table-records-parts

########################################
#部品仮登録リストのHTMLに部品のカテゴリを書き込む
cat $tmp-table-records-parts                                      |
sed -e "s|###PARTS_CATEGORY###|${PARTS_CATEGORY_LIST}|g"  > $tmp-table-records-parts2

########################################
#部品仮登録リストのHTMLの改行文字を「\\n」という3文字の文字列に置換
PARTS_TABLE_RECORDS=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-table-records-parts2`

########################################
#tableにrecordsを嵌め込む　
cat ${SYSD}/APPLI/${CATEGORY}/NEW/HTML/TABLE.HTML                     |
sed -e "s|###SET_CATEGORY###|${SET_CATEGORY_NEW}|g"                   | 
sed -e "s|###OPERATION_CATEGORY###|${OPERATION_CATEGORY_NEW}|g"       |
sed -e "s|###OPERATION_TABLE_RECORDS###|${OPERATION_TABLE_RECORDS}|g" |
sed -e "s|###PARTS_CATEGORY###|${PARTS_CATEGORY_NEW}|g"               |
sed -e "s|###PARTS_TABLE_RECORDS###|${PARTS_TABLE_RECORDS}|g"         > $tmp-table-html

########################################
# 改行文字を「\\n」という3文字の文字列に置換
TABLE=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-table-html`

########################################
#tableをはめ込む、ページャーを差し込む
cat ${SYSD}/APPLI/${CATEGORY}/NEW/HTML/INPUT.HTML               |
sed -e "s|###INFO_MSG###||g"                                    |
sed -e "s|###SET_CATEGORY_NM_PAGE###|${SET_PAGE_CATEGORY}|g"    |
sed -e "s|###SET_CATEGORY_NO_PAGE###|${SET_PAGE_CATEGORY_NO}|g" |
sed -e "s|###SET_CATEGORY###|${SET_CATEGORY_PAGE}|g"            |
sed -e "s|###TABLE###|${TABLE}|g"                               > $tmp-html

########################################
#page name
echo "Set Input" > $tmp-pagename

########################################
echo "OK"
exit 0
