#!/bin/bash -vx
##


# ===引数 sec session_id session_value
expire_sec=$1
session_id=$2
session_value=$3

# ===== Cookie文字列生成時に必要な材料を作成 =========================
#
# --- Cookieの有効期限を設定する -------------------------------------
s1=$(TZ=UTC+0 date +'%s'                    )
s2=$(echo $s1 |        awk -v s=$expire_sec '{print $1+s}')
s3=$(echo $s2 |        awk '{ print strftime("%c", $1); }'     )
expire=$(echo $s3 | awk '{ printf("%s, %02d-%s-%04d %s GMT", $1, $3, $2, $5, $4) }')
#+ s3='Mon Jul 18 22:06:12 2016'




#expire=$(TZ=UTC+0 date +'%s'                    |
#        awk -v s=$expire_sec '{print $1+s}'     |
#        awk '{ print strftime("%c", $1); }'     |
##        awk '{                                 #   RFC850形式に変換
#                split("Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec",monthname);
#                split("Sun Mon Tue Wed Thu Fri Sat",weekname);
#                Y = substr($1, 1,4)*1; M = substr($1, 6,2)*1; D = substr($1, 9,2)*1;
#                h = substr($2, 1,2)*1; m = substr($2,4,2)*1; s = substr($2,7,2)*1;
#                Y2 = (M<3) ? Y-1 : Y; M2 = (M<3)? M+12 : M;
#                w = (Y2+int(Y2/4)-int(Y2/100)+int(Y2/400)+int((M2*13+8)/5)+D)%7;
#                printf("%s, %02d-%s-%04d %02d:%02d:%02d GMT\n",
#                weekname[w+1], D, monthname[M], Y, h, m, s);
#            }'  )

# --- Cookieの有効なパスを設定する -----------------------------------
mypath='/APP'  # これは例なので実際はちゃんとしたものを設定すること
#
# --- このCGIが動いているのはHTTPか、それともHTTPSか -----------------
case "${HTTPS:-off}" in
    [Oo][Nn]) secure='; secure';;
    *)        secure=''        ;;
esac

# ===== Cookie文字列生成 =============================================
#
# "sessionid"や"timestamp"は例なので、必要なものを自分で設定しておく
cookie_id=$(printf "\nSet-Cookie: ${session_id}=%s; expires=%s; path=%s%s" \
                   "${session_value}" "${expire}" "${mypath}" "${secure}")

#cookie_ts=$(printf '\nSet-Cookie: timestamp=%s; expires=%s; path=%s%s' \
#                   "$timestamp" "$expire" "$mypath" "$secure"          )

echo ${cookie_id}${cookie_ts}
