#!/bin/bash -vx
#

########################################
#	DUPLICATE.CGI
#
#       $1:検索するDFSのCATEGORYディレクト名
#       $2:検索するDFSのFUNCディレクト名(LV2の直上)
#       $3:検索するDFSのGK番号
#       $4:検索するDFSのPK番号
#       $5:重複を検証する文字列や数値
#       
#	Written by hiramatsu


########################################
#基本設定
SYSD=$(cd $(dirname $0) && pwd | awk '{print substr($0, 0, index($0, "sureshotsystem")+13)}')
LANG=ja_JP.UTF-8

#######################################
#Validation
#OKの場合、OK|OKメッセージ、
#NGの場合、NG|NGメッセージを返す
CATEGORY=$1
FUNC=$2
GK=${3:-0}
PK=$4
VALUE=$5
DATAD=${SYSD}/DATA/${CATEGORY}/${FUNC}

#######################################
#Validation
VALID=$(cat ${DATAD}/LV3/*[^_d] | awk -v gk=${GK} -v pk=${PK} -v val=${VALUE} '$1!=gk&&$'"pk"'==val{print $1}')
[ -n "${VALID}" ] && echo "NG|Duplicated." || echo "OK|Not_Duplicate."

#######################################
#Return cookie words
exit 0

