#!/bin/bash
#

########################################
#	ISEN_ISJP.CGI
#
#   $1:”EN” or JP”
#       ”EN”を指定した場合、1バイト文字以外はNG
#       ”JP”を指定した場合、文字数とバイト数が同じ場合、NG 
#   $2:検証する文字列や数値
#       
#	Written by hiramatsu


#######################################
LANG=ja_JP.UTF-8

#Validation
#OKの場合、OK|OKメッセージ、
#NGの場合、NG|NGメッセージを返す
STR_LEN=${#2}
STR_BYT=$(echo -n $2 | wc -c)

case $1 in
  EN):
    [ "${STR_LEN}" -eq "${STR_BYT}" ] && echo "OK|Is_EN." || echo "NG|Is_EN." 
    ;;
  JP):
    [ "${STR_LEN}" -eq "${STR_BYT}" ] && echo "NG|Is_Not_JP." || echo "OK|Is_JP." 
    ;;
esac


#######################################
#Return cookie words
exit 0

