#!/bin/bash -vx
#

########################################
#	LENGTH.CGI
#
#       $1:検証する文字列や数値
#       $2:最小文字数(0を指定した場合、$4の最大文字数のみを評価) 
#       $3:最大文字数(0を指定した場合、$3の最初文字数のみを評価)
#       
#	Written by hiramatsu


########################################
#基本設定
SYSD=$(cd $(dirname $0) && pwd | awk '{print substr($0, 0, index($0, "sureshotsystem")+13)}')
tmp=/tmp/tmp_$1
LANG=ja_JP.UTF-8

#######################################
#Validation
case $2:$3 in
  *:0)  #最小文字数チェック($3文字以上ならOK)
    [ ${#1} -ge $2 ] && echo "'Len Min OK'" || echo "'Len Min NG'" 
    ;;
  0:*)  #最大文字数チェック($4文字以下ならOK)
    [ ${#1} -le $3 ] && echo "'Len Max OK'" || echo "'Max Len Max NG'" 
    ;;
  *)    #文字数範囲チェック($3文字以上、$4文字以下ならOK)
    [ ${#1} -ge $2 ] && [ ${#1} -le $3 ] && echo "'Len Range OK'" || echo "'Len Range NG'" 
    ;;
esac

#######################################
#Return cookie words
exit 0

