#!/bin/bash
#

########################################
#	DFS_NEW.CGI
#
#   引数
#       $1:プロセスID
#       $2:必須 ディレクトリパス(複数階層の場合、そのすべて:/DATA/AAA/LIST)
#       $3:任意 LV1-LV3を配置するDirパス
#   戻り値
#       YYYYMMDD.HHMMSS.プロセスID.ステータス.固有キー
#
#	Written by hiramatsu


########################################
#基本設定
SYSD=$(cd $(dirname $0) && pwd | awk '{print substr($0, 0, index($0, "sureshotsystem")+13)}')
#exec 2> ${SYSD}/LOG/LOG.$(basename $0).${DATE_TIME_PID}
tmp=/tmp/tmp_$1
LANG=ja_JP.UTF-8
#PATH=/home/:/home/UTL:/home/TOOL/open-usp-tukubai-2014061402/COMMANDS:$PATH

########################################
##Check error
#ERROR_CHECK(){
#	[ $(plus ${PIPESTATUS[@]}) -eq 0 ] && return
#cat <<- FIN
#	Context-type: text/html
#	NG input
#FIN
#	cat $tmp-result
#	exit 1
#}

########################################
#Dirを分解して、すべての階層のDirをチェックして、なければ作成
ARR=(`echo $2 | tr -s '/' ' '`)
for fld in ${ARR[@]}; do
  DIR+=/$fld
  if [ -e ${DIR} ]; then
    :
  else
    [ -z ${TOPD} ] && TOPD=${DIR} || : 
    mkdir ${DIR} 
    CNT+=1
  fi
done

########################################
#mkdirがなければここで離脱
[ -z "${CNT}" ] && exit 0 || :

########################################
#LV-3を配置
[ -n $3 ] && cp -rp ${SYSD}/DATA/ORG_LV1-3/* $3/ || :

########################################
#権限を付与
chmod -R 770 ${TOPD}

########################################
#戻り値
echo "OK" 

########################################
#正常終了
exit 0
