#!/bin/bash -evx
#

########################################
#	SET_LIST/EDIT/OPERATION/COMPLETE.CGI
#
#   引数
#       $1:プロセスID
#
#	Written by hiramatsu


########################################
#基本設定
SYSD=$(cd $(dirname $0) && pwd | awk '{print substr($0, 0, index($0, "sureshotsystem")+13)}')
#exec 2> ${SYSD}/LOG/LOG.$(basename $0).$(date +%Y%m%d).$(date +%H%M%S).$$
tmp=/tmp/tmp_$1
LANG=ja_JP.UTF-8
#PATH=/home/:/home/UTL:/home/TOOL/open-usp-tukubai-2014061402/COMMANDS:$PATH
CATEGORY=`cat $tmp-category`
FUNC=`cat $tmp-func`

########################################
#Check error
ERROR_CHECK(){
	[ $(plus ${PIPESTATUS[@]}) -eq 0 ] && return
cat <<- FIN
	Context-type: text/html
	NG input
FIN
	cat $tmp-result
	exit 1
}

########################################
#セットカテゴリ更新中は、処理をさせない
#ls ${SYSD}/LOCK/PARTS_CATEGORY/* > $tmp-checker 2> /dev/null
#if [ -n cat $tmp-checker ] ; then
#    echo "333" > $tmp-ajax-html
#    exit 0
#fi

#######################################
#フォームの入力値を取得
ACTION=$(nameread ACTION $tmp-post)
ROW=$(nameread ROW $tmp-post)
NUM=$(nameread SET_NO $tmp-post)
SET_CATEGORY_NO=$(nameread SET_CATEGORY_NO $tmp-post)
OPERATION_CATEGORY_NO=$(nameread OPERATION_CATEGROY_NO $tmp-post)
OPERATION_CATEGORY_NM=$(nameread OPERATION_CATEGROY_NM $tmp-post)
OPERATION_NM=$(nameread OPERATION_NM $tmp-post)
OPERATION_NM_NX=$(nameread OPERATION_NM_NX $tmp-post)
OPERATION_PRICE=$(nameread OPERATION_PRICE $tmp-post)
OPERATION_QTY=$(nameread OPERATION_QTY $tmp-post)

########################################
#DATAディレクトリ
DATAD=${SYSD}/DATA/${CATEGORY}/LISTS/${SET_CATEGORY_NO}

########################################
#重複確認
if [ "${OPERATION_NM}" != "${OPERATION_NM_NX}" ] ; then
  cat ${DATAD}/LV3/${NUM}_setlist_operation_* | 
  awk -v nm=${OPERATION_NM} '$6==nm{print $1}' > $tmp-valid1
  if [ -n "$(cat $tmp-valid1)" ] ; then
    echo 2222 > $tmp-ajax-html
    exit 0
  fi
fi

########################################
#LV1の最新の作業を取得
#セット番号、セットカテゴリ番号、作業カテゴリ番号、作業カテゴリ名、作業番号、作業名、作業価格、作成日、更新日
  cat $( ls ${DATAD}/LV1/${NUM}_setlist_operation_*[^_d] | sort | tail -n 1) > $tmp-lv1-set-operation

########################################
#既存データから作成日時取得、現在日時を更新日時とする
ls $tmp-set-operation | cut -d'_' -f4 | sort -nk1,1 | head -n 1 > $tmp-create
CREATE_DATE=$(cat $tmp-create)
UPDATE_DATE=$(date +%Y%m%d%H%M%S)

########################################
#ACTIONで振り分け
case ${ACTION} in
ADD)    
  #追加
  echo ${NUM} ${SET_CATEGORY_NO} ${OPERATION_CATEGORY_NO} ${OPERATION_CATEGORY_NM} ${OPERATION_NO} ${OPERATION_NM} ${OPERATION_PRICE} ${OPERATION_QTY} ${CREATE_DATE} ${UPDATE_DATE} >> $tmp-lv1-set-operation
  cat $tmp-set-operation
  ;;
EDIT)   #変更
  cat $tmp-lv1-set-operation  | 
  awk \
      -v row=${ROW} \
      -v set_no=${NUM} \
      -v set_cate_no=${SET_CATEGORY_NO} \
      -v op_cate_no=${OPERATION_CATEGORY_NO} \ 
      -v op_cate_nm=${OPERATION_CATEGORY_NM} \
      -v op_no=${OPERATION_NO} \ 
      -v op_nm=${OPERATION_NM} \ 
      -v parts_nm=${PARTS_NM} \
      -v price=${OPERATION_PRICE} \
      -v qty=${OPERATION_QTY} \
      -v cdt=${CREATE_DATE} \
      -v udt=${UPDATE_DATE} \
      'NR!=row{print} \
      NR==row{print(set_no, set_cate_no, op_cate_no, op_cate_nm, op_no, op_nm, price, qty, cdt, udt)}' \
      > $tmp-set-operation
  ;;
DELETE) #削除
  cat $tmp-lv1-set-operation      | 
  awk -v d=${ROW} 'NR!=d{print}'  > $tmp-set-operation
  ;;
esac

########################################
#作業カテゴリを取得
cat ${SYSD}/DATA/OPERATION_CATEGORY/LISTS/LV3/*[^_d]    |
LANG=C sort -nk1,1                                      > $tmp-category

########################################
#登録済パーツ用のパーツカテゴリ
# 1;カテゴリ番号 2;カテゴリ名
mojihame -lRECORDS ${SYSD}/APPLI/${CATEGORY}/${FUNC}/HTML/OPERATION/CATEGORY_LIST.HTML $tmp-category > $tmp-operation-category-list

#######################################
# 改行文字を「\\n」という3文字の文字列に置換
CATEGORY_LIST=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-operation-category-list`

########################################
#該当のデータ操作をロック
LOCK=`${SYSD}/CGI/LOCK/LOCK $1 'SET_LIST' ${NUM}`
LOCK_STATUS=$(echo $LOCK | cut -d'.' -f4)
[ ${LOCK_STATUS} != 'LOCKED' ] && exit 0 || :

#######################################
#データ格納
#LV1:原始データとして、ファイル追加のみを行う
mv $tmp-set-operation ${DATAD}/LV1/${NUM}_setlist_operation_${UPDATE_DATE}
#LV3:LV2を更新ファイルと入れ替え
rm -f ${DATAD}/LV2/${NUM}_setlist_operation_*
cp -fp ${DATAD}/LV1/${NUM}_setlist_operation_${UPDATE_DATE} ${DATAD}/LV2/
rm -f ${DATAD}/LV3/${NUM}_setlist_operation_*
cp -fp ${DATAD}/LV2/${NUM}_setlist_operation_${UPDATE_DATE} ${DATAD}/LV3/

########################################
#データ操作ロックを解除
UNLOCK_STATUS=`${SYSD}/CGI/LOCK/UNLOCK $1 'SET_LIST' ${NUM}`
[ ${UNLOCK_STATUS} != 'UNLOCK'] && exit 0 || :

########################################
#ending
echo "OK"
exit 0
