#!/bin/bash -evx
#

########################################
#	SET_LIST/NEW/OPERATION/COMPLETE.CGI
#
#   引数
#       $1:プロセスID
#
#	Written by hiramatsu


########################################
#基本設定
SYSD=$(cd $(dirname $0) && pwd | awk '{print substr($0, 0, index($0, "sureshotsystem")+13)}')
#exec 2> ${SYSD}/LOG/LOG.$(basename $0).$(date +%Y%m%d).$(date +%H%M%S).$$
tmp=/tmp/tmp_$1
LANG=ja_JP.UTF-8
#PATH=/home/:/home/UTL:/home/TOOL/open-usp-tukubai-2014061402/COMMANDS:$PATH
CATEGORY=`cat $tmp-category`
FUNC=`cat $tmp-func`

########################################
#Check error
ERROR_CHECK(){
	[ $(plus ${PIPESTATUS[@]}) -eq 0 ] && return
cat <<- FIN
	Context-type: text/html
	NG input
FIN
	cat $tmp-result
	exit 1
}

########################################
#パーツカテゴリ更新中は、処理をさせない
#ls ${SYSD}/LOCK/PARTS_CATEGORY/* > $tmp-checker 2> /dev/null
#if [ -n cat $tmp-checker ] ; then
#    echo "333" > $tmp-ajax-html
#    exit 0
#fi

########################################
#仮登録ディレクトリ
SESSION=$(session_get 'sureshot_stuff_session_id') 
STUFF_ID=$(cat ${SYSD}/SESSION/${SESSION})
TEMPD=${SYSD}/TMP/${STUFF_ID}/SET_LIST

#######################################
#フォームの入力値を取得
ACTION=$(nameread ACTION $tmp-post)
ROW=$(nameread ROW $tmp-post)
OPERATION_CATEGORY_NO=$(nameread OPERATION_CATEGORY_NO $tmp-post)
OPERATION_CATEGORY_NM=$(nameread OPERATION_CATEGORY_NM $tmp-post)
OPERATION_NO=$(nameread OPERATION_NO $tmp-post)
OPERATION_NM=$(nameread OPERATION_NM $tmp-post)
OPERATION_PRICE=$(nameread OPERATION_PRICE $tmp-post)
OPERATION_QTY=$(nameread OPERATION_QTY $tmp-post)

######################################t#
#ACTIONで振り分け
case ${ACTION} in
ADD)    #追加
  #重複確認
  cat ${TEMPD}/set_list_operation | awk -v pid=${OPERATION_NO} '$3==pid {print}' > $tmp-valid1
  if [ -n "$(cat $tmp-valid1)" ] ; then
      echo 2222 > $tmp-ajax-html
      exit 0
  fi
  #1:カテゴリ番号、2:カテゴリ名、3:作業番号、4:作業名、5:価格、6:数量
  echo ${OPERATION_CATEGORY_NO} ${OPERATION_CATEGORY_NM} ${OPERATION_NO} ${OPERATION_NM} ${OPERATION_PRICE} ${OPERATION_QTY} >> ${TEMPD}/set_list_operation
  #空行を削除
  cat ${TEMPD}/set_list_operation | awk /./ > $tmp-set-list-operation
  ;;
EDIT)   #変更
  cat ${TEMPD}/set_list_operation | 
  awk \
      -v row=${ROW} \
      -v category_no=${OPERATION_CATEGORY_NO} \
      -v category_nm=${OPERATION_CATEGORY_NM} \
      -v operation_no=${OPERATION_NO} \
      -v operation_nm=${OPERATION_NM} \
      -v price=${OPERATION_PRICE} \
      -v qty=${OPERATION_QTY} \
      'NR!=row{print} \
      NR==row{print(category_no, category_nm, operation_no, operation_nm, price, qty)}' \
      > $tmp-set-list-operation
  ;;
DELETE) #削除
  cat ${TEMPD}/set_list_operation | awk -v d=${ROW} 'NR!=d{print}' > $tmp-set-list-operation
  ;;
esac

#######################################
#入力値を仮登録
#作業カテゴリ番号、作業カテゴリ名、作業番号、作業名、作業価格、作業数量
cat $tmp-set-list-operation > ${TEMPD}/set_list_operation

########################################
#作業カテゴリを取得
cat ${SYSD}/DATA/OPERATION_CATEGORY/LISTS/LV3/*[^_d]    |
LANG=C sort -nk1,1                                      > $tmp-operation-category

########################################
#作業新規登録用の作業カテゴリ
# 1;カテゴリ番号 2;カテゴリ名
mojihame -lRECORDS ${SYSD}/APPLI/${CATEGORY}/${FUNC}/HTML/OPERATION/OPERATION_CATEGORY_NEW.HTML $tmp-operation-category > $tmp-operation-category-new

########################################
#カテゴリの改行文字を「\\n」という3文字の文字列に置換
CATEGORY_NEW=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-operation-category-new`

########################################
#作業レコード用の作業カテゴリ
# 1;カテゴリ番号 2;カテゴリ名
mojihame -lRECORDS ${SYSD}/APPLI/${CATEGORY}/${FUNC}/HTML/OPERATION/OPERATION_CATEGORY_LIST.HTML $tmp-operation-category > $tmp-operation-category-list

########################################
#作業カテゴリの改行文字を「\\n」という3文字の文字列に置換
CATEGORY_LIST=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-operation-category-list`

########################################
#仮登録の作業リストを取得
cat ${TEMPD}/set_list_operation      |
juni                                |                
LANG=C sort -nk1,1                  > $tmp-records
mojihame -lRECORDS ${SYSD}/APPLI/${CATEGORY}/NEW/HTML/OPERATION/RECORDS.HTML $tmp-records > $tmp-table-records

########################################
#登録済レコードに作業カテゴリリストを嵌め込む
cat $tmp-table-records                         |
sed -e "s|###CATEGORY###|${CATEGORY_LIST}|g"   > $tmp-table

########################################
# 改行文字を「\\n」という3文字の文字列に置換
TABLE_RECORDS=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-table`

########################################
#tableにrecordsを嵌め込む
cat ${SYSD}/APPLI/${CATEGORY}/NEW/HTML/OPERATION/TABLE.HTML |
sed -e "s|###CATEGORY###|${CATEGORY_NEW}|g"                 |
sed -e "s|###TABLE_RECORDS###|${TABLE_RECORDS}|g"           > $tmp-ajax-html

########################################
#ending
echo "OK"
exit 0
