#!/bin/bash -evx
#

########################################
#	SET_LIST/EDIT/OPERATION/COMPLETE.CGI
#
#   引数
#       $1:プロセスID
#
#	Written by hiramatsu


########################################
#基本設定
SYSD=$(cd $(dirname $0) && pwd | awk '{print substr($0, 0, index($0, "sureshotsystem")+13)}')
#exec 2> ${SYSD}/LOG/LOG.$(basename $0).$(date +%Y%m%d).$(date +%H%M%S).$$
tmp=/tmp/tmp_$1
LANG=ja_JP.UTF-8
#PATH=/home/:/home/UTL:/home/TOOL/open-usp-tukubai-2014061402/COMMANDS:$PATH
CATEGORY=`cat $tmp-category`
FUNC=`cat $tmp-func`

########################################
#Check error
ERROR_CHECK(){
	[ $(plus ${PIPESTATUS[@]}) -eq 0 ] && return
cat <<- FIN
	Context-type: text/html
	NG input
FIN
	cat $tmp-result
	exit 1
}

########################################
#セットカテゴリ更新中は、処理をさせない
#ls ${SYSD}/LOCK/PARTS_CATEGORY/* > $tmp-checker 2> /dev/null
#if [ -n cat $tmp-checker ] ; then
#    echo "333" > $tmp-ajax-html
#    exit 0
#fi

########################################
#仮登録Dir
TEMPD=${SYSD}/TMP/$(cat ${SYSD}/SESSION/$(session_get 'sureshot_stuff_session_id'))/SET_LIST

#######################################
#フォームの入力値を取得
ACTION=$(nameread ACTION $tmp-post)
ROW=$(nameread ROW $tmp-post)
NUM=$(nameread SET_NO $tmp-post)
SET_CATEGORY_NO=$(nameread SET_CATEGORY_NO $tmp-post)
OPERATION_CATEGORY_NO=$(nameread OPERATION_CATEGORY_NO $tmp-post)
OPERATION_CATEGORY_NM=$(nameread OPERATION_CATEGORY_NM $tmp-post)
OPERATION_NO=$(nameread OPERATION_NO $tmp-post)
OPERATION_NM=$(nameread OPERATION_NM $tmp-post)
OPERATION_NM_NX=$(nameread OPERATION_NM_NX $tmp-post)
OPERATION_PRICE=$(nameread OPERATION_PRICE $tmp-post)
OPERATION_QTY=$(nameread OPERATION_QTY $tmp-post)

########################################
#DATAディレクトリ
DATAD=${SYSD}/DATA/${CATEGORY}/LISTS/${SET_CATEGORY_NO}

########################################
#作業を取得
#セット番号、セットカテゴリ番号、作業カテゴリ番号、作業カテゴリ名、作業番号、作業名、作業価格、作成日、更新日
if [ -e "${TEMPD}/setlist_operation" ]; then
  cat ${TEMPD}/setlist_operation > $tmp-set-operation-tmp
else
  cat ${DATAD}/LV3/${NUM}_setlist_operation_*  > $tmp-set-operation-tmp
fi

########################################
#重複確認
if [ "${OPERATION_NM}" != "${OPERATION_NM_NX}" ] ; then
  cat $tmp-set-operation-tmp                    | 
  awk -v nm=${OPERATION_NM} '$6==nm{print $1}'  > $tmp-valid1
  if [ -n "$(cat $tmp-valid1)" ] ; then
    echo 2222 > $tmp-ajax-html
    exit 0
  fi
fi

########################################
#既存データから作成日時取得、現在日時を更新日時とする
ls ${DATAD}/LV1/${NUM}_setlist_operation_* | sort -nk1,1 | head -n 1 | cut -d'_' -f5 > $tmp-create
CREATE_DATE=$(cat $tmp-create)
UPDATE_DATE=$(date +%Y%m%d%H%M%S)

########################################
#ACTIONで振り分け
case ${ACTION} in
ADD)    
  #追加
  #82 1 1 オイル交換 2 oil1 3000 1 20170613193650 20170613193650
  echo  ${NUM} ${SET_CATEGORY_NO} \
        ${OPERATION_CATEGORY_NO} ${OPERATION_CATEGORY_NM} \
        ${OPERATION_NO} ${OPERATION_NM} \
        ${OPERATION_PRICE} ${OPERATION_QTY} \
        ${CREATE_DATE} ${UPDATE_DATE} \
        >> $tmp-set-operation-tmp
  cat $tmp-set-operation-tmp > $tmp-set-operation
  ;;
EDIT)   #変更
  cat $tmp-set-operation-tmp  | 
  awk \
      -v row=${ROW} \
      -v set_no=${NUM} \
      -v set_cate_no=${SET_CATEGORY_NO} \
      -v op_cate_no=${OPERATION_CATEGORY_NO} \
      -v op_cate_nm=${OPERATION_CATEGORY_NM} \
      -v op_no=${OPERATION_NO} \
      -v op_nm=${OPERATION_NM} \
      -v price=${OPERATION_PRICE} \
      -v qty=${OPERATION_QTY} \
      -v cdt=${CREATE_DATE} \
      -v udt=${UPDATE_DATE} \
      'NR!=row{print} \
      NR==row{print( \
          set_no, \
          set_cate_no, \
          op_cate_no, \
          op_cate_nm, \
          op_no, \
          op_nm, \
          price, \
          qty, \
          cdt, \
          udt \
      )}' \
      > $tmp-set-operation
  ;;
DELETE) #削除
  cat $tmp-set-operation-tmp      | 
  awk -v d=${ROW} 'NR!=d{print}'  > $tmp-set-operation
  ;;
esac

########################################
#仮登録を作成
rm -f ${TEMPD}/setlist_operation
cat $tmp-set-operation > ${TEMPD}/setlist_operation

########################################
#作業カテゴリを取得
cat ${SYSD}/DATA/OPERATION_CATEGORY/LISTS/LV3/*         |
LANG=C sort -nk1,1                                      > $tmp-operation-category

########################################
#作業新規登録用の作業カテゴリ
# 1;カテゴリ番号 2;カテゴリ名
mojihame -lRECORDS ${SYSD}/APPLI/${CATEGORY}/${FUNC}/HTML/OPERATION/OPERATION_CATEGORY_NEW.HTML $tmp-operation-category > $tmp-set-operation-category-new

########################################
#作業カテゴリの改行文字を「\\n」という3文字の文字列に置換
CATEGORY_NEW=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-set-operation-category-new`

########################################
#登録済パーツ用のパーツカテゴリ
# 1;カテゴリ番号 2;カテゴリ名
mojihame -lRECORDS ${SYSD}/APPLI/${CATEGORY}/${FUNC}/HTML/OPERATION/OPERATION_CATEGORY_NEW.HTML $tmp-operation-category > $tmp-set-operation-category-list

#######################################
# 改行文字を「\\n」という3文字の文字列に置換
CATEGORY_LIST=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-set-operation-category-list`

########################################
#作業をテーブルへ
#順位、セット番号、セットカテゴリ番号、作業カテゴリ番号、作業カテゴリ名、作業番号、作業名、作業価格、作成日、更新日
cat $tmp-set-operation      |
juni                        |
LANG=C sort -nk1,1          > $tmp-records
mojihame -lRECORDS ${SYSD}/APPLI/${CATEGORY}/${FUNC}/HTML/OPERATION/RECORDS.HTML $tmp-records > $tmp-table-records
cat $tmp-table-records | sed -e "s|###CATEGORY###|${CATEGORY_LIST}|g" > $tmp-table-records2

########################################
# 改行文字を「\\n」という3文字の文字列に置換
TABLE_RECORDS=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-table-records2`

########################################
#tableにrecordsを嵌め込む
cat ${SYSD}/APPLI/${CATEGORY}/${FUNC}/HTML/OPERATION/TABLE.HTML |
sed -e "s|###CATEGORY###|${CATEGORY_NEW}|g"                     |
sed -e "s|###TABLE_RECORDS###|${TABLE_RECORDS}|g"               > $tmp-ajax-html

########################################
#ending
echo "OK"
exit 0
