#!/bin/bash -vx
#

########################################
# SET_LIST/EDIT/OPERATION INPUT.CGI
#
#   $1:必須 $$
#
#	Written by hiramatsu


########################################
#基本設定
export LANG=ja_JP.utf8
echo $LANG
SYSD=$(cd $(dirname $0) && pwd | awk '{print substr($0, 0, index($0, "sureshotsystem")+13)}')
#exec 2> $SYSD/LOG/LOG.$(basename $0).$(date +%Y%m%d).$(date +%H%M%S).$$
tmp=/tmp/tmp_$1
LANG=ja_JP.UTF-8
#PATH=/home/:/home/UTL:/home/TOOL/open-usp-tukubai-2014061402/COMMANDS:$PATH
CATEGORY=`cat $tmp-category`
FUNC=`cat $tmp-func`
DATAD=${SYSD}/DATA/${CATEGORY}/LISTS

#######################################
#Check error
ERROR_CHECK(){
	[ $(plus ${PIPESTATUS[@]}) -eq 0 ] && return
cat <<- FIN
	Context-type: text/html
	NG input
FIN
	cat $tmp-result
	exit 1
}

########################################
#セットのバリデーション。NGならばセットに戻す。
#RESULT=`${SYSD}/APPLI/${CATEGORY}/${FUNC}/CGI/SET/CONFIRM $1`
#if [ "${RESULT}" != 'OK' ]; then
#    echo "NG"
#    exit 0
#fi

########################################
#仮登録を削除
TEMPD=${SYSD}/TMP/$(cat ${SYSD}/SESSION/$(session_get 'sureshot_stuff_session_id'))/SET_LIST

########################################
#GETパラメータを取得
SET_CATEGORY_NO_ORG=$( cat $tmp-get | cut -d'&' -f1 | sed -e 's/SET_CATEGORY_NO_HID\=//' | ruby -r uri -ne 'print URI.unescape $_')
SET_NO=$( cat $tmp-get | cut -d'&' -f2 | sed -e 's/SET_NO_HID\=//' | ruby -r uri -ne 'print URI.unescape $_')

########################################
#作業カテゴリを取得
cat ${SYSD}/DATA/OPERATION_CATEGORY/LISTS/LV3/*         |
LANG=C sort -nk1,1                                      > $tmp-operation-category

########################################
#作業新規登録用の作業カテゴリ
# 1;カテゴリ番号 2;カテゴリ名
mojihame -lRECORDS ${SYSD}/APPLI/${CATEGORY}/${FUNC}/HTML/OPERATION/OPERATION_CATEGORY_NEW.HTML $tmp-operation-category > $tmp-set-operation-category-new

########################################
#作業カテゴリの改行文字を「\\n」という3文字の文字列に置換
CATEGORY_NEW=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-set-operation-category-new`

########################################
#作業登録済用の作業カテゴリ
# 1;カテゴリ番号 2;カテゴリ名
mojihame -lRECORDS ${SYSD}/APPLI/${CATEGORY}/${FUNC}/HTML/OPERATION/OPERATION_CATEGORY_LIST.HTML $tmp-operation-category > $tmp-set-operation-category-list

########################################
#作業カテゴリの改行文字を「\\n」という3文字の文字列に置換
CATEGORY_LIST=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-set-operation-category-list`

########################################
#Get records
if [ -e "${TEMPD}/setlist_operation" ]; then
  cat ${TEMPD}/setlist_operation > $tmp-set-operation
else
  cat ${DATAD}/${SET_CATEGORY_NO_ORG}/LV3/${SET_NO}_setlist_operation_* > $tmp-set-operation
fi

########################################
#作業をテーブルへ
#順位、セット番号、セットカテゴリ番号、作業カテゴリ番号、作業カテゴリ名、作業番号、作業名、作業価格、作成日、更新日
cat $tmp-set-operation      |
juni                        |
LANG=C sort -nk1,1          > $tmp-records
mojihame -lRECORDS ${SYSD}/APPLI/${CATEGORY}/${FUNC}/HTML/OPERATION/RECORDS.HTML $tmp-records > $tmp-table-records
cat $tmp-table-records | sed -e "s|###CATEGORY###|${CATEGORY_LIST}|g" > $tmp-table-records2

########################################
# 改行文字を「\\n」という3文字の文字列に置換
TABLE_RECORDS=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-table-records2`

########################################
#tableにrecordsを嵌め込む
cat ${SYSD}/APPLI/${CATEGORY}/${FUNC}/HTML/OPERATION/TABLE.HTML |
sed -e "s|###CATEGORY###|${CATEGORY_NEW}|g"                     |
sed -e "s|###TABLE_RECORDS###|${TABLE_RECORDS}|g"               > $tmp-table-html

########################################
# 改行文字を「\\n」という3文字の文字列に置換
TABLE=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-table-html`

########################################
#tableをはめ込む
cat ${SYSD}/APPLI/${CATEGORY}/EDIT/HTML/OPERATION/INPUT.HTML            |
sed -e "s|###INFO_MSG###|"セットに登録する作業を更新してください。"|g"  |
sed -e "s|###SET_CATEGORY_NO_ORG###|${SET_CATEGORY_NO_ORG}|g"           |
sed -e "s|###SET_NO###|${SET_NO}|g"                                     |
sed -e "s|###TABLE###|${TABLE}|g"                                       > $tmp-html

########################################
#page name
echo "Set Operation edit" > $tmp-pagename

########################################
echo "OK"
exit 0
