#!/bin/bash -vx
#

########################################
#	SET_LIST NEW SET CONFIRM.CGI
#
#   Arg
#       $1:$$
#
#	Written by hiramatsu


########################################
#基本設定
SYSD=$(cd $(dirname $0) && pwd | awk '{print substr($0, 0, index($0, "sureshotsystem")+13)}')
#exec 2> $SYSD/LOG/LOG.$(basename $0).$(date +%Y%m%d).$(date +%H%M%S).$$
tmp=/tmp/tmp_$1
LANG=ja_JP.UTF-8
#PATH=/home/:/home/UTL:/usr/local/bin:/home/TOOL/open-usp-tukubai-2014061402/COMMANDS:$PATH
CATEGORY=`cat $tmp-category`
FUNC=`cat $tmp-func`
SUBFUNC=`cat $tmp-subfunc`

########################################
#仮登録ディレクトリ
SESSION=$(session_get 'sureshot_stuff_session_id') 
STUFF_ID=$(cat ${SYSD}/SESSION/${SESSION})
TEMPD=${SYSD}/TMP/${STUFF_ID}/SET_LIST

########################################
#Check error
ERROR_CHECK(){
	[ $(plus ${PIPESTATUS[@]}) -eq 0 ] && return
cat <<- FIN
	Context-type: text/html
	NG input
FIN
	cat $tmp-result
	exit 1
}

########################################
#フォーム値の設定
SET_CATEGORY_NO=$(nameread SET_CATEGORY_NO $tmp-post)
SET_CATEGORY_NM=$(nameread SET_CATEGORY_NM $tmp-post)
SET_NM=$(nameread SET_NM $tmp-post)
SET_PRICE=$(nameread SET_PRICE $tmp-post)
SET_REMARKS=$(nameread SET_REMARKS $tmp-post)

########################################
#バリデーション(重複確認)
#ファイル名の先頭にセット番号
#カテゴリ番号、カテゴリ名、セット番号、セット名、セット価格、備考
cat ${SYSD}/DATA/SET_LIST/LIST/${SET_CATEGORY_NO}/LV3/*_setlist_base_* | 
awk '$4=="${SET_NM}" {print}' > $tmp-dup-valid
if [ -n "$(cat $tmp-dup-valid)" ] ; then
    echo 2222 > $tmp-ajax-html
    exit 0
fi

########################################
#仮登録
rm -f ${TEMPD}/setlist_base
echo ${SET_CATEGORY_NO} ${SET_CATEGORY_NM} ${SET_NM} ${SET_PRICE} ${SET_REMARKS} > ${TEMPD}/setlist_base
echo ${NUM} ${SET_CATEGORY_NO} ${SET_CATEGORY_NM} ${SET_NM} ${SET_PRICE} ${SET_REMARKS} > ${TEMPD}/setlist_base

###############################################################################
#ending
echo "OK"
exit 0
