#!/bin/bash -vx
#

########################################
# SET_LIST/NEW/SET INPUT.CGI
#
#   $1:必須 $$

#	Written by hiramatsu


########################################
#基本設定
export LANG=ja_JP.utf8
echo $LANG
SYSD=$(cd $(dirname $0) && pwd | awk '{print substr($0, 0, index($0, "sureshotsystem")+13)}')
#exec 2> $SYSD/LOG/LOG.$(basename $0).$(date +%Y%m%d).$(date +%H%M%S).$$
tmp=/tmp/tmp_$1
LANG=ja_JP.UTF-8
#PATH=/home/:/home/UTL:/home/TOOL/open-usp-tukubai-2014061402/COMMANDS:$PATH
CATEGORY=`cat $tmp-category`
FUNC=`cat $tmp-func`
DATAD=${SYSD}/DATA/${CATEGORY}/LISTS

#######################################
#Check error
ERROR_CHECK(){
	[ $(plus ${PIPESTATUS[@]}) -eq 0 ] && return
cat <<- FIN
	Context-type: text/html
	NG input
FIN
	cat $tmp-result
	exit 1
}

########################################
#仮登録を削除
SESSION=$(session_get 'sureshot_stuff_session_id') 
STUFF_ID=$(cat ${sysd}/session/${session})
TEMPD=${SYSD}/tmp/${STUFF_ID}/set_list

########################################
#SET_LISTディレクトリを作成
if [ -e "${TEMPD}" ]; then
  :
else
  mkdir ${TEMPD}
  chmod 770 -R ${TEMPD}
fi

########################################
#仮登録を取得
#SET_ARRY=(`cat ${TEMPD}/set_list`)
SET_CATEGORY_NO=$(cat ${TEMPD}/set_list | cut -d' ' -f1)
SET_CATEGORY_NM=$(cat ${TEMPD}/set_list | cut -d' ' -f2)
SET_NM=$(cat ${TEMPD}/set_list | cut -d' ' -f3)
SET_PRICE=$(cat ${TEMPD}/set_list | cut -d' ' -f4)
SET_REMARKS=$(cat ${TEMPD}/set_list | cut -d' ' -f5)

########################################
#セットカテゴリを取得
cat ${SYSD}/DATA/SET_CATEGORY/LISTS/LV3/*[^_d]    |
LANG=C sort -nk1,1                                  > $tmp-set-category

########################################
#セット新規登録用のセットカテゴリ
# 1;カテゴリ番号 2;カテゴリ名
mojihame -lRECORDS ${SYSD}/APPLI/${CATEGORY}/NEW/HTML/SET/SET_CATEGORY_NEW.HTML $tmp-set-category > $tmp-set-category-new

########################################
# セットカテゴリの改行文字を「\\n」という3文字の文字列に置換
CATEGORY_NEW=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-set-category-new`

########################################
#tableにrecordsを嵌め込む
cat ${SYSD}/APPLI/${CATEGORY}/NEW/HTML/SET/TABLE.HTML   |
sed -e "s|###SET_CATEGORY_NM###|${SET_CATEGORY_NM}|g"   |
sed -e "s|###SET_CATEGORY_NO###|${SET_CATEGORY_NO}|g"   |
sed -e "s|###SET_NM###|${SET_NM}|g"                     |
sed -e "s|###SET_PRICE###|${SET_PRICE}|g"               |
sed -e "s|###SET_REMARKS###|${SET_REMARKS}|g"           |
sed -e "s|###CATEGORY###|${CATEGORY_NEW}|g"             > $tmp-table-html

########################################
# 改行文字を「\\n」という3文字の文字列に置換
TABLE=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-table-html`

#tableをはめ込む、ページャーを差し込む
cat ${SYSD}/APPLI/${CATEGORY}/NEW/HTML/SET/INPUT.HTML               |
sed -e "s|###INFO_MSG###|"登録するセット名を入力してください。"|g"  |
sed -e "s|###TABLE###|${TABLE}|g"                                   > $tmp-html

########################################
#page name
echo "Set Name input" > $tmp-pagename

########################################
echo "OK"
exit 0
