#!/bin/bash -evx
#

########################################
#	OPERATION_LIST/NEW COMPLETE.CGI
#
#   引数
#       $1:プロセスID
#
#	Written by hiramatsu


########################################
#基本設定
SYSD=$(cd $(dirname $0) && pwd | awk '{print substr($0, 0, index($0, "sureshotsystem")+13)}')
#exec 2> ${SYSD}/LOG/LOG.$(basename $0).$(date +%Y%m%d).$(date +%H%M%S).$$
tmp=/tmp/tmp_$1
LANG=ja_JP.UTF-8
PATH=/home/:/home/UTL:/home/TOOL/open-usp-tukubai-2014061402/COMMANDS:$PATH
CATEGORY=`cat $tmp-category`
FUNC=`cat $tmp-func`
DATAD=${SYSD}/DATA/${CATEGORY}/LISTS

########################################
#Check error
ERROR_CHECK(){
	[ $(plus ${PIPESTATUS[@]}) -eq 0 ] && return
cat <<- FIN
	Context-type: text/html
	NG input
FIN
	cat $tmp-result
	exit 1
}

########################################
#作業カテゴリ更新中は、処理をさせない
#ls ${SYSD}/LOCK/OPERATION_CATEGORY/* > $tmp-checker 2> /dev/null
#if [ -n cat $tmp-checker ] ; then
#    echo "333" > $tmp-ajax-html
#    exit 0
#fi

########################################
#作業番号の次のロットを追加する
LATEST_NUM=$(ls ${SYSD}/DATA/NUMBERS/${CATEGORY}/ORIGIN | sort -nr | head -n 1)
START=$((LATEST_NUM + 1))
END=$((START + 1))
SEQ_STATUS=`${SYSD}/CGI/NUMBER_SEQ $1 ${CATEGORY} ${START} ${END} `
[[ ${SEQ_STATUS} != 'SUCCESS' ]] && exit 0

########################################
#新規作業番号を確定する
NEW_NUM=`${SYSD}/CGI/NUMBERS $1 'OPERATION_LIST' `
[ ${NEW_NUM} = 'ERROR' ] && exit 0 || :

#######################################
#フォームの入力値を取得
cat $tmp-post
PAGE_FILTER=$(nameread CATEGORY_PAGE_HIDDEN $tmp-post)
PAGE_CATEGORY_NO=$(nameread CATEGORY_NO_PAGE_HIDDEN $tmp-post)
VALUE1=$(nameread CATEGORY_NEW_HIDDEN $tmp-post)        #作業カテゴリ名
VALUE2=$(nameread NEW_OPERATION_NAME $tmp-post)             #作業名(EN)
VALUE3=$(nameread NEW_OPERATION_PRICE $tmp-post)            #プライス

#新規追加
VALUE4=$(nameread CATEGORY_NO_NEW_HIDDEN $tmp-post)     #作業カテゴリ番号
VALUE5=$(nameread NEW_OPERATION_NAME_JP $tmp-post)          #作業名(JP)
VALUE6=$(nameread NEW_OPERATION_REMARKS $tmp-post)          #備考

########################################
#重複確認
cat ${DATAD}/${VALUE4}*[^_d]/LV3/* | awk -v cat=${VALUE4} -v nm=${VALUE2} '$2==cat&&$4==nm{print $1}' > $tmp-valid1
if [ -n "$(cat $tmp-valid1)" ] ; then
    echo 2222 > $tmp-ajax-html
    exit 0
fi

########################################
#日付を設定
CREATE_DATE=$(date +%Y%m%d%H%M%S)
UPDATE_DATE=$CREATE_DATE

########################################
#入力値を一時ファイル化
#1.作業番号 2.作業カテゴリ番号 3.作業カテゴリ名 4.作業名(EN) 5.作業名(JP) 6.価格 7.備考 8.作成日時 9.更新日時 10.削除フラグ
echo ${NEW_NUM}" "${VALUE4}" "${VALUE1}" "${VALUE2}" "${VALUE5}" "${VALUE3}" "${VALUE6}" "${CREATE_DATE}" "${UPDATE_DATE}" "0 > $tmp-operation

########################################
#データ格納
#LV1
$(mv $tmp-operation ${DATAD}/${VALUE4}/LV1/${NEW_NUM}_operation_${CREATE_DATE})
#LV2
cat ${DATAD}/${VALUE4}/LV1/${NEW_NUM}_operation_${CREATE_DATE} > ${DATAD}/${VALUE4}/LV2/${NEW_NUM}_operation_${CREATE_DATE}
#LV3
cat ${DATAD}/${VALUE4}/LV2/${NEW_NUM}_operation_${CREATE_DATE} > ${DATAD}/${VALUE4}/LV3/${NEW_NUM}_operation_${CREATE_DATE}

########################################
#作業カテゴリを取得
cat ${SYSD}/DATA/OPERATION_CATEGORY/LISTS/LV3/*[^_d]    |
LANG=C sort -nk1,1                                  > $tmp-category

########################################
#Page絞り込み用の作業カテゴリ
# 1;カテゴリ番号 2;カテゴリ名
mojihame -lRECORDS ${SYSD}/APPLI/${CATEGORY}/LISTS/HTML/CATEGORY_PAGE.HTML $tmp-category > $tmp-operation-category-page

########################################
#登録済作業用の作業カテゴリ
# 1;カテゴリ番号 2;カテゴリ名
mojihame -lRECORDS ${SYSD}/APPLI/${CATEGORY}/LISTS/HTML/CATEGORY_LIST.HTML $tmp-category > $tmp-operation-category-list

########################################
#新規登録作業用の作業カテゴリ
# 1;カテゴリ番号 2;カテゴリ名
mojihame -lRECORDS ${SYSD}/APPLI/${CATEGORY}/LISTS/HTML/CATEGORY_NEW.HTML $tmp-category > $tmp-operation-category-new

########################################
# 改行文字を「\\n」という3文字の文字列に置換
CATEGORY_PAGE=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-operation-category-page`
CATEGORY_LIST=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-operation-category-list`
CATEGORY_NEW=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-operation-category-new`

########################################
#作業リストを取得
if [ "${PAGE_CATEGORY_NO}" -gt 0 ] ; then
    cat ${DATAD}/${PAGE_CATEGORY_NO}*[^_d]/LV3/*[^_d]   |
    LANG=C sort -nk1,1                                  |
    juni                                                > $tmp-records
else
    cat ${DATAD}/*[^_d]/LV3/*[^_d]                      |
    LANG=C sort -nk1,1                                  |
    juni                                                > $tmp-records
fi
#
mojihame -lRECORDS ${SYSD}/APPLI/${CATEGORY}/LISTS/HTML/RECORDS.HTML $tmp-records > $tmp-table-records

########################################
#登録済レコードに作業カテゴリリストを嵌め込む
cat $tmp-table-records                                      |
sed -re "s|###CATEGORY###|${CATEGORY_LIST}|g"   > $tmp-table

########################################
# 改行文字を「\\n」という3文字の文字列に置換
TABLE_RECORDS=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-table`

########################################
#tableにrecordsを嵌め込む
cat ${SYSD}/APPLI/${CATEGORY}/LISTS/HTML/TABLE.HTML         |
sed -e "s|###CATEGORY###|${CATEGORY_NEW}|g"                 |
sed -e "s|###TABLE_RECORDS###|${TABLE_RECORDS}|g"           > $tmp-ajax-html

########################################
#ending
echo "OK"
exit 0
