#!/bin/bash -vx
#

########################################
# SET_DETAIL/LIST SHOW.CGI
#
#   $1:必須 $$
#
#	Written by hiramatsu


########################################
#基本設定
export LANG=ja_JP.utf8
echo $LANG
SYSD=$(cd $(dirname $0) && pwd | awk '{print substr($0, 0, index($0, "sureshotsystem")+13)}')
#exec 2> $SYSD/LOG/LOG.$(basename $0).$(date +%Y%m%d).$(date +%H%M%S).$$
tmp=/tmp/tmp_$1
LANG=ja_JP.UTF-8
#PATH=/home/:/home/UTL:/home/TOOL/open-usp-tukubai-2014061402/COMMANDS:$PATH
CATEGORY=`cat $tmp-category`
FUNC=`cat $tmp-func`
SUBFUNC=`cat $tmp-sub-func`
DATAD=${SYSD}/DATA/${CATEGORY}/LISTS

#######################################
#Check error
ERROR_CHECK(){
	[ $(plus ${PIPESTATUS[@]}) -eq 0 ] && return
cat <<- FIN
	Context-type: text/html
	NG input
FIN
	cat $tmp-result
	exit 1
}

########################################
#GETパラメーターを取得
#GETパラメーターの順番は、action,page,serach,category-nm,category-no, id が前提
[ -n "$(cat $tmp-get | grep 'page=')" ] && \
QRY_PAGE=$(cat $tmp-get | awk '{split($0,ary,"&"); print ary[2]}' | sed 's/page\=//') || \
QRY_PAGE=1
[ -n "$(cat $tmp-get | grep 'search=')" ] && \
SEARCH=$(cat $tmp-get | awk '{split($0,ary,"&"); print ary[3]}') || \
SEARCH='search=0'
CATEGORY_NM=$(cat $tmp-get | awk '{split($0,ary,"&"); print ary[4]}' | sed 's/category-nm\=//')
CATEGORY_NO=$(cat $tmp-get | awk '{split($0,ary,"&"); print ary[5]}' | sed 's/category-no\=//')
SET_NO=$(cat $tmp-get | awk '{split($0,ary,"&"); print ary[6]}' | sed 's/id\=//')


########################################
#セット
########################################

########################################
#セットリストを取得
cat ${SYSD}/DATA/SET_LIST/LISTS/LV3/set_* |
awk -v no=${SET_NO} '$1==no {print}' > $tmp-set
cat $tmp-set | awk '{print $3}' > $tmp-category-nm-set
cat $tmp-set | awk '{print $4}' > $tmp-set-nm-set
cat $tmp-set | awk '{print $5}' > $tmp-price-set

########################################
#セット詳細を取得
cat ${DATAD}/LV3/${SET_NO}_set-detail_* > $tmp-records-set
mojihame -lRECORDS ${SYSD}/APPLI/${CATEGORY}/LISTS/HTML/SET/RECORDS.HTML $tmp-records-set > $tmp-table-set

########################################
# 改行文字を「\\n」という3文字の文字列に置換
TABLE_RECORDS=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-table-set`

########################################
#tableにrecordsを嵌め込む
cat ${SYSD}/APPLI/${CATEGORY}/LISTS/HTML/SET/TABLE.HTML |
sed -e "s|###TABLE_RECORDS###|${TABLE_RECORDS}|g"       > $tmp-table-html-set

########################################
# 改行文字を「\\n」という3文字の文字列に置換
TABLE_SET=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-table-html-set`   


########################################
#作業
########################################

########################################
#作業カテゴリを取得
cat ${SYSD}/DATA/OPERATION_CATEGORY/LISTS/LV3/*[^_d]        |
LANG=C sort -nk1,1                                          > $tmp-category-operation

########################################
#作業カテゴリドロップダウン
mojihame -lRECORDS ${SYSD}/APPLI/${CATEGORY}/${FUNC}/HTML/OPERATION/CATEGORY_LIST.HTML $tmp-category-operation > $tmp-operation-category

########################################
# 改行文字を「\\n」という3文字の文字列に置換
OPERATION_CATEGORY=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-operation-category`

########################################
#セットに登録した作業リストを取得
cat ${DATAD}/LV3/${SET_NO}_set-operation_*[^_d] > $tmp-records-operation

########################################
#作業リストをテーブルにはめ込む
mojihame -lRECORDS ${SYSD}/APPLI/${CATEGORY}/${FUNC}/HTML/OPERATION/RECORDS.HTML $tmp-records-operation > $tmp-table-records-operation

########################################
# 改行文字を「\\n」という3文字の文字列に置換
cat $tmp-table-records-operation | awk -F\n -v ORS='\\\\n' '{print}' > $tmp-table-operation
cat $tmp-table-operation > /tmp/ggggg

########################################
#tableにrecordsを嵌め込む
cat ${SYSD}/APPLI/${CATEGORY}/LISTS/HTML/OPERATION/TABLE.HTML         |
sed -e "s|###OPERATION_TABLE_RECORDS###|$(cat $tmp-table-operation)|" |
sed -e "s|###OPERATION_CATEGORY###|${OPERATION_CATEGORY}|g"           > $tmp-table-html-operation

########################################
# 改行文字を「\\n」という3文字の文字列に置換
TABLE_OPERATION=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-table-html-operation`   


########################################
#部品
########################################

########################################
#部品カテゴリを取得
cat ${SYSD}/DATA/PARTS_CATEGORY/LISTS/LV3/*[^_d]  |
LANG=C sort -nk1,1                                > $tmp-category-parts

########################################
#部品追加用の部品カテゴリ
# 1;カテゴリ番号 2;カテゴリ名
mojihame -lRECORDS ${SYSD}/APPLI/${CATEGORY}/LISTS/HTML/PARTS/CATEGORY_NEW.HTML $tmp-category-parts > $tmp-parts-category-new

########################################
# 改行文字を「\\n」という3文字の文字列に置換
PARTS_CATEGORY_NEW=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-parts-category-new`

########################################
#セットに登録した作業リストを取得
cat ${DATAD}/LV3/parts_*[^_d] > $tmp-records-parts

########################################
#作業リストをテーブルにはめ込む
mojihame -lRECORDS ${SYSD}/APPLI/${CATEGORY}/${FUNC}/HTML/PARTS/RECORDS.HTML $tmp-records-parts > $tmp-table-records-parts

########################################
# 改行文字を「\\n」という3文字の文字列に置換
`awk -F\n -v ORS='\\\\n' '{print}' $tmp-table-records-parts` > $tmp-table-parts

########################################
#tableにrecordsを嵌め込む
cat ${SYSD}/APPLI/${CATEGORY}/LISTS/HTML/PARTS/TABLE.HTML |
sed -e "s|###TABLE_RECORDS###|$(cat $tmp-table-parts)|g"  |
sed -e "s|###PARTS_CATEGORY###|${PARTS_CATEGORY_NEW}|g"         > $tmp-table-html-parts

########################################
# 改行文字を「\\n」という3文字の文字列に置換
TABLE_PARTS=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-table-html-parts`   


########################################
#tableをはめ込む
cat ${SYSD}/APPLI/${CATEGORY}/LISTS/HTML/SHOW.HTML                  |
sed -e "s|###SET_NO###|${SET_NO}|g"                                 |
sed -e "s|###SET_CATEGORY_NM###|$(cat $tmp-category-nm-set)|g"      |
sed -e "s|###SET_NM###|$(cat $tmp-set-nm-set)|g"                    |
sed -e "s|###SET_PRICE###|$(cat $tmp-price-set)|g"                  |
sed -e "s|###CATEGORY_NM###|${CATEGORY_NM}|g"                       |
sed -e "s|###CATEGORY_NO###|${CATEGORY_NO}|g"                       |
sed -e "s|###PAGE###|${QRY_PAGE}|g"                                 |
sed -e "s|###SEARCH###|${SEARCH}|g"                                 |
sed -e "s|###SET_LIST###|${TABLE_SET}|"                             |
sed -e "s|###OPERATION_LIST###|${TABLE_OPERATION}|"                 |
sed -e "s|###PARTS_LIST###|${TABLE_PARTS}|"                         |
sed -e "s|###INFO_MSG###||g"                                        > $tmp-html

########################################
#page name
echo "Set detail" > $tmp-pagename

########################################
echo "OK"
exit 0
