#!/bin/bash -evx
#

########################################
#	PARTS_CATEGORY DELETE COMPLETE.CGI
#
#   引数
#       $1:プロセスID
#
#	Written by hiramatsu


########################################
#基本設定
SYSD=$(cd $(dirname $0) && pwd | awk '{print substr($0, 0, index($0, "sureshotsystem")+13)}')
#exec 2> ${SYSD}/LOG/LOG.$(basename $0).$(date +%Y%m%d).$(date +%H%M%S).$$
tmp=/tmp/tmp_$1
LANG=ja_JP.UTF-8
PATH=/home/:/home/UTL:/home/TOOL/open-usp-tukubai-2014061402/COMMANDS:$PATH
CATEGORY=`cat $tmp-category`
FUNC=`cat $tmp-func`
DATAD=${SYSD}/DATA/${CATEGORY}/LISTS

########################################
#Check error
ERROR_CHECK(){
	[ $(plus ${PIPESTATUS[@]}) -eq 0 ] && return
cat <<- FIN
	Context-type: text/html
	NG input
FIN
	cat $tmp-result
	exit 1
}
#
########################################
#フォームの入力値を取得
NUM=$(nameread PARTS_CATEGORY_ID $tmp-post)
NAME=$(nameread PARTS_CATEGORY_NAME $tmp-post)
#
########################################
#既存データから作成日時取得、現在日時を更新日時とする
ls ${DATAD}/LV1/${NUM}_parts_category_* | sort -nk1,1 | tail -n 1 | cut -d'/' -f8 | cut -d'_' -f4 > $tmp-create
CREATE_DATE=$(cat $tmp-create)
UPDATE_DATE=$(date +%Y%m%d%H%M%S)


########################################
#　　パーツカテゴリのデータ操作
########################################

########################################
#該当のデータ操作をロック
LOCK=`${SYSD}/CGI/LOCK/LOCK $1 'PARTS_CATEGORY' ${NUM}`
LOCK_STATUS=$(echo $LOCK | cut -d'.' -f4)
[ ${LOCK_STATUS} != 'LOCKED' ] && exit 0 || :

########################################
#入力値を一時ファイル化
#1.パーツカテゴリ番号 2.パーツカテゴリ名 3.作成日時 4.更新日時 5.削除フラグ
echo ${NUM}" "${NAME}" "${CREATE_DATE}" "${UPDATE_DATE}" "1 > $tmp-parts-category

########################################
#データ格納
#LV1:原始データとして、ファイル追加のみを行う
$(mv $tmp-parts-category ${DATAD}/LV1/${NUM}_parts_category_${UPDATE_DATE})

#LV2:変更されたデータとファイルを入れ替える
cp -ip ${DATAD}/LV1/${NUM}_parts_category_${UPDATE_DATE} ${DATAD}/LV2/${NUM}_parts_category_${UPDATE_DATE}_d
ls ${DATAD}/LV2/${NUM}_* | sort -nk1 | head -n 1 > $tmp-delete
rm -f $(cat $tmp-delete)

#LV3:LV2のコピー
cp -ip ${DATAD}/LV2/${NUM}_parts_category_${UPDATE_DATE}_d ${DATAD}/LV3/${NUM}_parts_category_${UPDATE_DATE}_d
ls ${DATAD}/LV3/${NUM}_* | sort -nk1 | head -n 1 > $tmp-delete
rm -f $(cat $tmp-delete)

########################################
#データ操作ロックを解除
UNLOCK_STATUS=`${SYSD}/CGI/LOCK/UNLOCK $1 'PARTS_CATEGORY' ${NUM}`
[ ${UNLOCK_STATUS} != 'UNLOCK'] && exit 0 || :


########################################
#　　パーツのデータ操作
########################################
PARTSD=${SYSD}/DATA/PARTS_LIST/LISTS
#削除するカテゴリーで登録されているパーツに対して、
# 1.カテゴリを999 未選択、更新日を現在にして999ディレクトリにコピー
for file in `find ${PARTSD}/${NUM}/LV3/*[^_d] -maxdepth 1 -type f`; do

    #パーツ番号取得
    num=$(echo $file | cut -d'/' -f9 | cut -d'_' -f1) 
    update=$(echo $file | cut -d'/' -f9 | cut -d'_' -f3) 
    ARR+=($num)

    #該当のデータ操作をロック
    LOCK=`${SYSD}/CGI/LOCK/LOCK $1 'PARTS_LIST' ${num}`
    LOCK_STATUS=$(echo $LOCK | cut -d'.' -f4)
    [ ${LOCK_STATUS} != 'LOCKED' ] && exit 0 || :
    
    #LV1:原始データとして、ファイル追加のみを行う
    destiny=${PARTSD}/999/LV1/${num}_parts_${UPDATE_DATE}
    cat ${PARTSD}/${NUM}/LV1/${num}_parts_${update} | awk -v ud=${UPDATE_DATE} '{print $1, "999", "未選択", $4, $5, $6, $7, $8, ud, "0"}' > $destiny

    #LV2:変更されたデータとファイルを入れ替える
    cp -fp ${PARTSD}/999/LV1/${num}_parts_${UPDATE_DATE} ${PARTSD}/999/LV2/${num}_parts_${UPDATE_DATE}

    #LV3:LV2のコピー
    cp -fp ${PARTSD}/999/LV2/${num}_parts_${UPDATE_DATE} ${PARTSD}/999/LV3/${num}_parts_${UPDATE_DATE}

    #データ操作ロックを解除
    UNLOCK_STATUS=`${SYSD}/CGI/LOCK/UNLOCK $1 'PARTS_LIST' ${num}`
    [ ${UNLOCK_STATUS} != 'UNLOCK'] && exit 0 || :
done
# 2.ディレクトリ名の末尾に_dをつける
mv ${PARTSD}/${NUM} ${PARTSD}/${NUM}_${UPDATE_DATE}_d

########################################
#
echo "111" > $tmp-ajax-html

########################################
#ending
echo "OK"
exit 0
