#!/bin/bash -evx
#

########################################
# SET_DETAIL SEARCH INPUT.CGI
#
#   引数
#       $1:プロセスID
#
#	Written by hiramatsu


########################################
#基本設定
SYSD=$(cd $(dirname $0) && pwd | awk '{print substr($0, 0, index($0, "sureshotsystem")+13)}')
#exec 2> ${SYSD}/LOG/LOG.$(basename $0).$(date +%Y%m%d).$(date +%H%M%S).$$
tmp=/tmp/tmp_$1
LANG=ja_JP.UTF-8
#PATH=/home/:/home/UTL:/home/TOOL/open-usp-tukubai-2014061402/COMMANDS:$PATH
CATEGORY=`cat $tmp-category`
FUNC=`cat $tmp-func`
SUBFUNC=`cat $tmp-sub-func`
DATAD=${SYSD}/DATA/OPERATION_LIST/LISTS

########################################
#Check error
ERROR_CHECK(){
	[ $(plus ${PIPESTATUS[@]}) -eq 0 ] && return
cat <<- FIN
	Context-type: text/html
	NG input
FIN
	cat $tmp-result
	exit 1
}

#######################################
#フォームの入力値を取得
CATE_NO=$(nameread CATEGORY_NO $tmp-post)
ROW=$(nameread ROW $tmp-post)

########################################
#カテゴリを取得
cat ${DATAD}/LV3/*[^_d]                   |
awk -v cat=${CATE_NO} '$2==cat {print}'   |
LANG=C sort -nk1,1                        > $tmp-operation

########################################
#Operation
#作業番号、カテゴリ番号、作業名EN、作業名JP、金額、CDT、UDT、CUSR、UUSR
mojihame -lRECORDS ${SYSD}/APPLI/${CATEGORY}/${FUNC}/HTML/${SUBFUNC}/DROPDOWN_LIST.HTML $tmp-operation > $tmp-operation-row

########################################
#選択行を設定
cat $tmp-operation-row        |
sed -e "s/###ROW###/${ROW}/"  > $tmp-ajax-html

########################################
# 改行文字を「\\n」という3文字の文字に置換
#OPERATION=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-operation-html`

########################################
#ending
echo "OK"
exit 0
