#!/bin/bash -evx
#

########################################
#	SET_LIST/NEW/OPERATION/COMPLETE.CGI
#
#   引数
#       $1:プロセスID
#
#	Written by hiramatsu


########################################
#基本設定
SYSD=$(cd $(dirname $0) && pwd | awk '{print substr($0, 0, index($0, "sureshotsystem")+13)}')
#exec 2> ${SYSD}/LOG/LOG.$(basename $0).$(date +%Y%m%d).$(date +%H%M%S).$$
tmp=/tmp/tmp_$1
LANG=ja_JP.UTF-8
#PATH=/home/:/home/UTL:/home/TOOL/open-usp-tukubai-2014061402/COMMANDS:$PATH
CATEGORY=`cat $tmp-category`
FUNC=`cat $tmp-func`

########################################
#Check error
ERROR_CHECK(){
	[ $(plus ${PIPESTATUS[@]}) -eq 0 ] && return
cat <<- FIN
	Context-type: text/html
	NG input
FIN
	cat $tmp-result
	exit 1
}

########################################
#パーツカテゴリ更新中は、処理をさせない
#ls ${SYSD}/LOCK/PARTS_CATEGORY/* > $tmp-checker 2> /dev/null
#if [ -n cat $tmp-checker ] ; then
#    echo "333" > $tmp-ajax-html
#    exit 0
#fi
########################################
#仮登録ディレクトリ
SESSION=$(session_get 'sureshot_stuff_session_id') 
STUFF_ID=$(cat ${SYSD}/SESSION/${SESSION})
TMPD=${SYSD}/TMP/${STUFF_ID}

#######################################
#フォームの入力値を取得
cat $tmp-post
OPERATION_CATEGORY_NO=$(nameread OPERATION_CATEGORY_NO $tmp-post)
OPERATION_CATEGORY_NM=$(nameread OPERATION_CATEGORY_NM $tmp-post)
OPERATION_NO=$(nameread OPERATION_NO $tmp-post)
OPERATION_NM=$(nameread OPERATION_NM $tmp-post)
OPERATION_PRICE=$(nameread OPERATION_PRICE $tmp-post)
OPERATION_QTY=$(nameread OPERATION_QTY $tmp-post)

########################################
#重複確認
cat ${TMPD}/set_list_operation | awk -v pid=${OPERATION_NO} '$3==pid {print}' > $tmp-valid1
if [ -n "$(cat $tmp-valid1)" ] ; then
    echo 2222 > $tmp-ajax-html
    exit 0
fi

########################################
#入力値を仮登録
#パーツカテゴリ番号、パーツカテゴリ名、パーツ番号、パーツ名、パーツ価格、パーツ数量
echo ${OPERATION_CATEGORY_NO} ${OPERATION_CATEGORY_NM} ${OPERATION_NO} ${OPERATION_NM} ${OPERATION_PRICE} ${OPERATION_QTY} > $tmp-parts
cat $tmp-parts >> ${TMPD}/set_list_operation

########################################
#パーツカテゴリを取得
cat ${SYSD}/DATA/SET_LIST/LISTS/LV3/*[^_d]    |
LANG=C sort -nk1,1                            > $tmp-category

########################################
#新規登録パーツ用のパーツカテゴリ
# 1;カテゴリ番号 2;カテゴリ名
mojihame -lRECORDS ${SYSD}/APPLI/${CATEGORY}/NEW/HTML/OPERATION/OPERATION_CATEGORY_NEW.HTML $tmp-category > $tmp-operation-category-new

########################################
#登録済パーツ用のパーツカテゴリ
# 1;カテゴリ番号 2;カテゴリ名
mojihame -lRECORDS ${SYSD}/APPLI/${CATEGORY}/NEW/HTML/OPERATION/OPERATION_CATEGORY_LIST.HTML $tmp-category > $tmp-operation-category-list

########################################
# 改行文字を「\\n」という3文字の文字列に置換
CATEGORY_LIST=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-operation-category-list`
CATEGORY_NEW=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-operation-category-new`

########################################
#パーツリストを取得
cat ${TMPD}/set_list_operation   |
juni                                |                
LANG=C sort -nk1,1                  > $tmp-records
mojihame -lRECORDS ${SYSD}/APPLI/${CATEGORY}/NEW/HTML/OPERATION/RECORDS.HTML $tmp-records > $tmp-table-records

########################################
#登録済レコードにパーツカテゴリリストを嵌め込む
cat $tmp-table-records                         |
sed -e "s|###CATEGORY###|${CATEGORY_LIST}|g"   > $tmp-table

########################################
# 改行文字を「\\n」という3文字の文字列に置換
TABLE_RECORDS=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-table`

########################################
#tableにrecordsを嵌め込む
cat ${SYSD}/APPLI/${CATEGORY}/NEW/HTML/OPERATION/TABLE.HTML |
sed -e "s|###CATEGORY###|${CATEGORY_NEW}|g"                 |
sed -e "s|###TABLE_RECORDS###|${TABLE_RECORDS}|g"           > $tmp-ajax-html

########################################
#ending
echo "OK"
exit 0
