#!/bin/bash -vx
#

########################################
# SET_LIST/NEW/OPERATION INPUT.CGI
#
#   $1:必須 $$
#
#	Written by hiramatsu


########################################
#基本設定
export LANG=ja_JP.utf8
echo $LANG
SYSD=$(cd $(dirname $0) && pwd | awk '{print substr($0, 0, index($0, "sureshotsystem")+13)}')
#exec 2> $SYSD/LOG/LOG.$(basename $0).$(date +%Y%m%d).$(date +%H%M%S).$$
tmp=/tmp/tmp_$1
LANG=ja_JP.UTF-8
#PATH=/home/:/home/UTL:/home/TOOL/open-usp-tukubai-2014061402/COMMANDS:$PATH
CATEGORY=`cat $tmp-category`
FUNC=`cat $tmp-func`
DATAD=${SYSD}/DATA/${CATEGORY}/LISTS

#######################################
#Check error
ERROR_CHECK(){
	[ $(plus ${PIPESTATUS[@]}) -eq 0 ] && return
cat <<- FIN
	Context-type: text/html
	NG input
FIN
	cat $tmp-result
	exit 1
}

########################################
#セットのバリデーション。NGならばセットに戻す。
RESULT=`${SYSD}/APPLI/${CATEGORY}/${FUNC}/CGI/SET/CONFIRM $1`
if [ "${RESULT}" != 'OK' ]; then
    echo "NG"
    exit 0
fi

########################################
#作業カテゴリを取得
cat ${SYSD}/DATA/OPERATION_CATEGORY/LISTS/LV3/*[^_d]    |
LANG=C sort -nk1,1                                      > $tmp-operation-category

########################################
#作業新規登録用の作業カテゴリ
# 1;カテゴリ番号 2;カテゴリ名
mojihame -lRECORDS ${SYSD}/APPLI/${CATEGORY}/${FUNC}/HTML/OPERATION/OPERATION_CATEGORY_NEW.HTML $tmp-operation-category > $tmp-operation-category-new

########################################
# セットカテゴリの改行文字を「\\n」という3文字の文字列に置換
CATEGORY_NEW=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-operation-category-new`

########################################
#作業レコード用の作業カテゴリ
# 1;カテゴリ番号 2;カテゴリ名
mojihame -lRECORDS ${SYSD}/APPLI/${CATEGORY}/${FUNC}/HTML/OPERATION/OPERATION_CATEGORY_LIST.HTML $tmp-operation-category > $tmp-operation-category-list

########################################
#作業カテゴリの改行文字を「\\n」という3文字の文字列に置換
CATEGORY_LIST=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-operation-category-list`

########################################
#仮登録ディレクトリ
#SESSION=$(session_get 'sureshot_stuff_session_id') 
#STUFF_ID=$(cat ${SYSD}/SESSION/${SESSION}
#TMPD=${SYSD}/TMP/${STUFF_ID}
TMP_STUFFD=${SYSD}/TMP/$(cat ${SYSD}/SESSION/$(session_get 'sureshot_stuff_session_id'))

########################################
#作業仮登録リストを取得
cat ${TMP_STUFFD}/${CATEGORY}/operation   |
juni                                      | 
LANG=C sort -nk1,1                        > $tmp-records
mojihame -lRECORDS ${SYSD}/APPLI/${CATEGORY}/${FUNC}/HTML/OPERATION/RECORDS.HTML $tmp-records > $tmp-table-records
cat $tmp-table-records                        |
sed -e "s|###CATEGORY###|${CATEGORY_LIST}|g"  > $tmp-table-records2

########################################
# 改行文字を「\\n」という3文字の文字列に置換
TABLE_RECORDS=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-table-records2`

########################################
#tableにrecordsを嵌め込む
cat ${SYSD}/APPLI/${CATEGORY}/${FUNC}/HTML/OPERATION/TABLE.HTML |
sed -e "s|###TABLE_RECORDS###|${TABLE_RECORDS}|g"               |
sed -e "s|###CATEGORY###|${CATEGORY_NEW}|g"                     > $tmp-table-html

########################################
# 改行文字を「\\n」という3文字の文字列に置換
TABLE=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-table-html`

########################################
#新規ではなくバリデーションNGで戻ってきた場合、$tmpから値を取得
[ -e $tmp-valid-operation-category-no-nm ] && VALID=NG || echo 'hidden' > $tmp-valid-operation-category-no-nm 
[ -e $tmp-valid-operation-nm ] && VALID=NG || echo 'hidden' > $tmp-valid-operation-nm 
[ -e $tmp-valid-operation-price ] && VALID=NG || echo 'hidden' > $tmp-valid-operation-price 
[ -e $tmp-valid-operation-duplicate ] && VALID=NG || echo 'hidden' > $tmp-valid-operation-duplicate 

#tableをはめ込む、ページャーを差し込む
cat ${SYSD}/APPLI/${CATEGORY}/NEW/HTML/OPERATION/INPUT.HTML               |
sed -e "s|###INFO_MSG###||g"                                              |
sed -e "s/###CATEGORY_ERR###/$(cat $tmp-valid-operation-category-no-nm)/" |
sed -e "s/###NAME_ERR###/$(cat $tmp-valid-operation-nm)/"                 |
sed -e "s/###PRICE_ERR###/$(cat $tmp-valid-operation-price)/"             |
sed -e "s/###ITEM_DUPLECATED###/$(cat $tmp-valid-operation-duplicate)/"   |
sed -e "s|###TABLE###|${TABLE}|g"                                         > $tmp-html

########################################
#page name
echo "Set Operation input" > $tmp-pagename

########################################
echo "OK"
exit 0
