#!/bin/bash -evx
#

########################################
#	SET_LIST SEARCH INPUT.CGI
#
#   引数
#       $1:プロセスID
#
#	Written by hiramatsu


########################################
#基本設定
SYSD=$(cd $(dirname $0) && pwd | awk '{print substr($0, 0, index($0, "sureshotsystem")+13)}')
#exec 2> ${SYSD}/LOG/LOG.$(basename $0).$(date +%Y%m%d).$(date +%H%M%S).$$
tmp=/tmp/tmp_$1
LANG=ja_JP.UTF-8
#PATH=/home/:/home/UTL:/home/TOOL/open-usp-tukubai-2014061402/COMMANDS:$PATH
CATEGORY=`cat $tmp-category`
FUNC=`cat $tmp-func`
DATAD=${SYSD}/DATA/${CATEGORY}/LISTS

########################################
#Check error
ERROR_CHECK(){
	[ $(plus ${PIPESTATUS[@]}) -eq 0 ] && return
cat <<- FIN
	Context-type: text/html
	NG input
FIN
	cat $tmp-result
	exit 1
}

#######################################
#フォームの入力値を取得
CATE_NO=$(nameread SET_CATEGORY_NO $tmp-post)
ROW=$(nameread ROW $tmp-post)

########################################
#セットカテゴリを取得
cat ${SYSD}/DATA/SET_LIST/LISTS/${CATE_NO}/LV3/*[^_d]  |
LANG=C sort -nk1,1                                      > $tmp-set

########################################
#Set
# 部品番号、カテゴリ番号、カテゴリ名、部品名(EN)、部品名(JP)、単価、UD、CD
mojihame -lRECORDS ${SYSD}/APPLI/${CATEGORY}/${FUNC}/HTML/DROPDOWN_LIST.HTML $tmp-set > $tmp-set-row

########################################
#選択行を設定
cat $tmp-set-row  |
sed -e "s/###ROW###/${ROW}/" > $tmp-ajax-html

########################################
# 改行文字を「\\n」という3文字の文字に置換
#SET=`awk -F\n -v ORS='\\\\n' '{print}' $tmp-set-html`

########################################
#ending
echo "OK"
exit 0
