#!/bin/bash -evx
#

########################################
# OPERATION_CATEGORY DELETE COMPLETE.CGI
#
#   引数
#       $1:プロセスID
#
#	Written by hiramatsu


########################################
#基本設定
SYSD=$(cd $(dirname $0) && pwd | awk '{print substr($0, 0, index($0, "sureshotsystem")+13)}')
#exec 2> ${SYSD}/LOG/LOG.$(basename $0).$(date +%Y%m%d).$(date +%H%M%S).$$
tmp=/tmp/tmp_$1
LANG=ja_JP.UTF-8
#PATH=/home/:/home/UTL:/home/TOOL/open-usp-tukubai-2014061402/COMMANDS:$PATH
CATEGORY=`cat $tmp-category`
FUNC=`cat $tmp-func`
DATAD=${SYSD}/DATA/${CATEGORY}/LISTS

########################################
#Check error
ERROR_CHECK(){
	[ $(plus ${PIPESTATUS[@]}) -eq 0 ] && return
cat <<- FIN
	Context-type: text/html
	NG input
FIN
	cat $tmp-result
	exit 1
}
#
########################################
#フォームの入力値を取得
nameread OPERATION_CATEGORY_ID    $tmp-post > $tmp-pk-1
NUM=$(cat $tmp-pk-1)
nameread OPERATION_CATEGORY_NM_EN $tmp-post > $tmp-pk-2
nameread OPERATION_CATEGORY_NM_JP $tmp-post > $tmp-pk-3

########################################
#作成日時、作成者、最終更新日時、更新者を取得
result=`${SYSD}/CGI/DFS_INFO/CREATE_LASTUPDATE $1 ${DATAD}/LV1 ${NUM}`
CREATE_DATE=$(cat $tmp-create-dt)
CREATE_USER=$(cat $tmp-create-user)
LASTUPDATE_DT=$(cat $tmp-lastupdate-dt)
LASTUPDATE_USER=$(cat $tmp-lastupdate-user)

########################################
#更新日時を設定
UPDATE_DATE=$(date +%Y%m%d%H%M%S)

########################################
#更新者の取得
UPDATE_USER=$(cat ${SYSD}/SESSION/$(session_get 'sureshot_stuff_session_id'))

########################################
#　　作業カテゴリのデータ操作
########################################

########################################
#該当のデータ操作をロック
LOCK=`${SYSD}/CGI/LOCK/LOCK $1 'OPERATION_CATEGORY' ${NUM}`
LOCK_STATUS=$(echo $LOCK | cut -d'.' -f4)
[ ${LOCK_STATUS} != 'LOCKED' ] && exit 0 || :

########################################
#データ配置
#LV1
cat $tmp-pk-1 > ${DATAD}/LV1/${NUM}_1_${UPDATE_USER}_${UPDATE_DATE}_d
cat $tmp-pk-2 > ${DATAD}/LV1/${NUM}_2_${UPDATE_USER}_${UPDATE_DATE}_d
cat $tmp-pk-3 > ${DATAD}/LV1/${NUM}_3_${UPDATE_USER}_${UPDATE_DATE}_d

#LV2
rm -f ${DATAD}/LV2/${NUM}_*
cp -fp ${DATAD}/LV1/${NUM}_*_${UPDATE_DATE}_d ${DATAD}/LV2/

#LV3
rm -f ${DATAD}/LV3/${NUM}_*
for file in $(ls ${DATAD}/LV2/${NUM}_* | sort -t$'_' -nk1);
do
  VALUE=$(echo $VALUE `cat $file`)
done
echo ${VALUE} ${CREATE_DATE} ${UPDATE_DATE} ${CREATE_USER} ${UPDATE_USER} \
> ${DATAD}/LV3/${NUM}_operation-category_${UPDATE_DATE}_d

########################################
#データ操作ロックを解除
UNLOCK_STATUS=`${SYSD}/CGI/LOCK/UNLOCK $1 'OPERATION_CATEGORY' ${NUM}`
[ ${UNLOCK_STATUS} != 'UNLOCK'] && exit 0 || :

########################################
#   作業のデータ操作
#   削除する作業カテゴリに属している作業をすべて999に移動する操作
########################################

#削除するカテゴリーで登録されている作業に対して、
#未登録カテゴリーが存在していなければ作成(0)
# 0ディレクトリに移動

#オペリストDir
OPERATIOND=${SYSD}/DATA/OPERATION_LIST/LISTS

#############################
#0未登録カテゴリを作成
if [ -e "${DATAD}/LV1/0_*" ]; then
    :
else
    #LV1
    echo 0              > ${DATAD}/LV1/0_1_${UPDATE_USER}_${UPDATE_DATE}
    echo '未登録'       > ${DATAD}/LV1/0_2_${UPDATE_USER}_${UPDATE_DATE}
    echo 'Unregistered' > ${DATAD}/LV1/0_3_${UPDATE_USER}_${UPDATE_DATE}

    #LV2
    cp -fp ${DATAD}/LV1/0_* ${DATAD}/LV2/

    #LV3
    for file in $(ls ${DATAD}/LV2/0_* | sort -t$'_' -nk1);
    do
      VALUE=$(echo $VALUE `cat $file`)
    done
    echo ${VALUE} ${CREATE_DATE} ${UPDATE_DATE} ${CREATE_USER} ${UPDATE_USER} \
    > ${DATAD}/LV3/0_operation_category_${UPDATE_DATE}
fi

############################
#OPERATION_LISTにカテゴリ0ディレクトリを作成
if [ -e "${OPERATIOND}/0" ]; then
    :
else
    result=`${SYSD}/CGI/DATA/DFS_NEW $$ ${OPERATIOND}/0 ${OPERATIOND}/0`
fi

#削除されるカテゴリのディレクトリから、身寄りが無くなったので、0ディレクトリにオペリストをすべて移動
for file in `find ${OPERATIOND}/${NUM}/LV3/*[^_d] -maxdepth 1 -type f`; do

    #作業番号取得
    OPE_NO=$(echo $file | awk 'BEGIN{FS="/"}{print $NF}' | cut -d'_' -f1) 
    #ARR+=($OPE_NO)

    #該当のデータ操作をロック
    LOCK=`${SYSD}/CGI/LOCK/LOCK $1 'OPERATION_LIST' ${OPE_NO}`
    LOCK_STATUS=$(echo $LOCK | cut -d'.' -f4)
    [ ${LOCK_STATUS} != 'LOCKED' ] && exit 0 || :
    
    #LV1
    mv ${OPERATIOND}/${NUM}/LV1/${OPE_NO}_* ${OPERATIOND}/0/LV1/
    #LV2
    mv ${OPERATIOND}/${NUM}/LV2/${OPE_NO}_* ${OPERATIOND}/0/LV2/
    #LV3
    mv ${OPERATIOND}/${NUM}/LV3/${OPE_NO}_* ${OPERATIOND}/0/LV3/

    #データ操作ロックを解除
    UNLOCK_STATUS=`${SYSD}/CGI/LOCK/UNLOCK $1 'OPERATION_LIST' ${OPE_NO}`
    [ ${UNLOCK_STATUS} != 'UNLOCK'] && exit 0 || :
done

# 2.ディレクトリ名の末尾に_dをつける
mv ${OPERATIOND}/${NUM} ${OPERATIOND}/${NUM}_${UPDATE_DATE}_d

########################################
#LV3一覧3データ配置
#なにがしかのカテゴリNoの下にあるLV3データをかき集め、
#ファイルパスからカテゴリNoを、
#ファイルデータからオペ番号を

#紐付けたマップを作成
ls ${SYSD}/DATA/OPERATION_LIST/LISTS/*/LV3/*[^_d] | awk '{split($0,ary,"/"); print ary[7], ary[9]}' | cut -d'_' -f1 | LANG=C sort -k1 > $tmp-cate-list-map

#オペカテゴリ一覧
cat ${SYSD}/DATA/OPERATION_CATEGORY/LISTS/LV3/*[^_d] | awk '{print $1,$2}' | LANG=C sort -k1 > $tmp-cate-all

#オペ一覧
cat ${SYSD}/DATA/OPERATION_LIST/LISTS/*/LV3/*[^_d] | LANG=C sort -k1 > $tmp-ope-all

#JOIN
#マップとカテゴリ
LANG=C join -1 1 -2 1 $tmp-cate-list-map $tmp-cate-all | LANG=C sort -k2 > $tmp-ope-category

#カテゴリとオペ一覧
LANG=C join -1 2 -2 1 $tmp-ope-category $tmp-ope-all > $tmp-operations

#カテゴリ情報とマッピングしたオペ一覧をLISTS/LV3へ配置
rm -f ${SYSD}/DATA/OPERATION_LIST/LISTS/LV3/operations_*
mv $tmp-operations ${SYSD}/DATA/OPERATION_LIST/LISTS/LV3/operations_${UPDATE_DATE}

########################################
#
echo "111" > $tmp-ajax-html

########################################
#ending
echo "OK"
exit 0
